committee_data = [
    {"name": "Albrecht Schmidt", "affiliation": "LMU Munich"},
    {"name": "Kaisa Väänänen", "affiliation": "Tampere University"},
    {"name": "Tesh Goyal", "affiliation": "Google Research"},
    {"name": "Per Ola Kristensson", "affiliation": "University of Cambridge"},
    {"name": "Anicia Peters", "affiliation": "University of Namibia"},
    {"name": "Stefanie Mueller", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Julie R. Williamson", "affiliation": "University of Glasgow"},
    {"name": "Max L. Wilson", "affiliation": "University of Nottingham"},
    {"name": "Alisa Burova", "affiliation": "Tampere University"},
    {"name": "Passant Elagroudy", "affiliation": "German Centre for Artificial Intelligence (DFKI)"},
    {"name": "Jie Cai", "affiliation": "Penn State University"},
    {"name": "Gionnieve Lim", "affiliation": "Singapore University of Technology and Design"},
    {"name": "Andrii Matviienko", "affiliation": "Technical University of Darmstadt"},
    {"name": "Callum Berger", "affiliation": "University of Nottingham"},
    {"name": "Faraz Faruqi", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Megan Hofmann", "affiliation": "Northeastern University"},
    {"name": "Yue Jiang", "affiliation": "Aalto University"},
    {"name": "Claudia Loitsch", "affiliation": "TU Dresden"},
    {"name": "Benjamin Tannert", "affiliation": "City University of Applied Sciences Bremen"},
    {"name": "Matthew Louis Mauriello", "affiliation": "University of Delaware"},
    {"name": "Gözel Shakeri", "affiliation": "Carl von Ossietzky University of Oldenburg"},
    {"name": "Jonah-Noël Kaiser", "affiliation": "Carl von Ossietzky University of Oldenburg"},
    {"name": "Thu Marianski", "affiliation": "Carl von Ossietzky University of Oldenburg"},
    {"name": "Sven Mayer", "affiliation": "LMU Munich"},
    {"name": "Fiona Draxler", "affiliation": "LMU Munich"},
    {"name": "Julian Frommel", "affiliation": "Utrecht University"},
    {"name": "Thomas Kosch", "affiliation": "Utrecht University"},
    {"name": "Alexander G. Mirnig", "affiliation": "University of Salzburg"},
    {"name": "Diego Muñoz", "affiliation": "Swinburne University of Technology"},
    {"name": "Raphael Wimmer", "affiliation": "University of Regensburg"},
    {"name": "Frank Bentley", "affiliation": "Google"},
    {"name": "Abiodun Ogunyemi", "affiliation": "Tallinn University"},
    {"name": "Eunice Sari", "affiliation": "UX Indonesia"},
    {"name": "Daniela Busse", "affiliation": "Meta"},
    {"name": "Bastian Pfleging", "affiliation": "TU Bergakademie Freiberg"},
    {"name": "Margaret Burnett", "affiliation": "Oregon State University"},
    {"name": "Kasper Hornbæk", "affiliation": "University of Copenhagen"},
    {"name": "Bradley Rey", "affiliation": "University of British Columbia"},
    {"name": "Lars Erik Holmquist", "affiliation": "Northumbria University"},
    {"name": "Jaeyeon Lee", "affiliation": "Ulsan National Institute of Science and Technology"},
    {"name": "David Lindlbauer", "affiliation": "Carnegie Mellon University"},
    {"name": "Yomna Abdelrahmen", "affiliation": "Bundeswehr University Munich"},
    {"name": "Anirudha Joshi", "affiliation": "Indian Institute of Technology Bombay"},
    {"name": "Cosmin Munteanu", "affiliation": "University of Waterloo"},
    {"name": "Tanja Döring", "affiliation": "University of Bremen"},
    {"name": "Frank Steinicke", "affiliation": "Universität Hamburg"},
    {"name": "Julian Rasch", "affiliation": "LMU Munich"},
    {"name": "Oliver Haimson", "affiliation": "University of Michigan"},
    {"name": "Shaimaa Lazem", "affiliation": "City of Scientific Research and Technological Applications (SRTA-City)"},
    {"name": "Abdallah El Ali", "affiliation": "Centrum Wiskunde & Informatica (CWI)"},
    {"name": "Vinoba Vinayagamoorthy", "affiliation": "Samsung"},
    {"name": "Anke Brock", "affiliation": "ENAC, Université Toulouse"},
    {"name": "Jessica Cauchard", "affiliation": "Ben Gurion University of the Negev"},
    {"name": "Mario Alberto Moreno Rocha", "affiliation": "Universidad Tecnológica de la Mixteca"},
    {"name": "Niels Henze", "affiliation": "University of Regensburg"},
    {"name": "Jakob Karolus", "affiliation": "German Research Center for Artificial Intelligence (DFKI)"},
    {"name": "Ville Mäkelä", "affiliation": "University of Waterloo"},
    {"name": "Christian Sturm", "affiliation": "Technische Hochschule Ingolstadt"},
    {"name": "Chat Wacharamanotham", "affiliation": "Swansea University"},
    {"name": "Ciabhan Connely", "affiliation": "Georgia Institute of Technology"},
    {"name": "Julia Dunbar", "affiliation": "University of Washington"},
    {"name": "Maximiliane Windl", "affiliation": "LMU Munich"},
    {"name": "John Wenskovitch", "affiliation": "Pacific Northwest National Laboratory"},
    {"name": "Johannes Zagermann", "affiliation": "University of Konstanz"},
    {"name": "Thomas Olsson", "affiliation": "Tampere University"},
    {"name": "Dakuo Wang", "affiliation": "Northeastern University"},
    {"name": "Heike Winschiers-Theophilus", "affiliation": "Namibia University of Science and Technology"},
    {"name": "Lynne Baillie", "affiliation": "Heriot-Watt University"},
    {"name": "Wilko Heuten", "affiliation": "OFFIS – Institute for IT"},
    {"name": "Maryam Mustafa", "affiliation": "Lahore University of Management"},
    {"name": "Tawfiq Ammari", "affiliation": "Rutgers University School of Communication and Information"},
    {"name": "Anna Maria Feit", "affiliation": "Saarland University"},
    {"name": "Heloisa de Souza Pereira Candello", "affiliation": "IBM Brazil"},
    {"name": "Amon Rapp", "affiliation": "University of Torino"},
    {"name": "Rob Comber", "affiliation": "KTH Royal Institute of Technology"},
    {"name": "Konstantinos Koumaditis", "affiliation": "Aarhus University"},
    {"name": "Yi Chi Liao", "affiliation": "Aalto University"},
    {"name": "Christina Zaga", "affiliation": "University of Twente"},
    {"name": "Carol Klyver", "affiliation": "Foundations of Excellence"},
    {"name": "Elizabeth Churchill", "affiliation": "Google"},
    {"name": "Christine Bauer", "affiliation": "Utrecht University"},
    {"name": "Siobahn Day Grady", "affiliation": "North Carolina Central University"},
    {"name": "Anouk van Kasteren", "affiliation": "Utrecht University"},
    {"name": "Jordan Deja", "affiliation": "University of Primorska"},
    {"name": "Cuauhtémoc Rivera Loaiza", "affiliation": "Universidad Michoacana"},
    {"name": "Marisol Wong-Villacres", "affiliation": "Escuela Superior Politécnica del Litoral"},
    {"name": "João Moreira", "affiliation": "INESC-ID: Instituto de Engenharia de Sistemas e Computadores, Investigação e Desenvolvimento em Lisboa"}
]

committee_data_1 = [
    {"name": "Cliff Lampe", "affiliation": "University of Michigan"},
    {"name": "Simone Barbosa", "affiliation": "PUC-Rio"},
    {"name": "David A. Shamma", "affiliation": "Toyota Research Institute"},
    {"name": "Caroline Appert", "affiliation": "Université Paris-Saclay"},
    {"name": "Katta Spiel", "affiliation": "TU Wien"},
    {"name": "Christina Harrington", "affiliation": "Carnegie Mellon University"},
    {"name": "Danilo Gasques", "affiliation": "UC San Diego"},
    {"name": "Ihudiya Finda Williams", "affiliation": "University of Michigan"},
    {"name": "Monica Pereira", "affiliation": "Brunel University London"},
    {"name": "Dominic DiFranzo", "affiliation": "Lehigh University"},
    {"name": "Hugo Romat", "affiliation": "Microsoft"},
    {"name": "Anupriya Tuli", "affiliation": "IIIT Delhi, India"},
    {"name": "Cayley MacArthur", "affiliation": "University of Waterloo, Canada"},
    {"name": "Steven Drucker", "affiliation": "Microsoft Research"},
    {"name": "Julie Williamson", "affiliation": "University of Glasgow"},
    {"name": "Koji Yatani", "affiliation": "University of Tokyo"},
    {"name": "Nikita Samarin", "affiliation": "University of California, Berkeley"},
    {"name": "Zhongyi Zhou", "affiliation": "University of Tokyo"},
    {"name": "David Lindlbauer", "affiliation": "CMU"},
    {"name": "Heloisa Candello", "affiliation": "IBM"},
    {"name": "Vinoba Vinayagamoorthy", "affiliation": "BBC"},
    {"name": "Pedro Lopes", "affiliation": "University of Chicago"},
    {"name": "Frank Bentley", "affiliation": "Google"},
    {"name": "Catherine Letondal", "affiliation": "Ecole Nationale Aviation Civile"},
    {"name": "Anicia Peters", "affiliation": "University of Namibia"},
    {"name": "Kathryn Ringland", "affiliation": "University of California"},
    {"name": "Norman Makoto Su", "affiliation": "University of California, Santa Cruz"},
    {"name": "Oliver Haimson", "affiliation": "University of Michigan"},
    {"name": "Nicolai Marquardt", "affiliation": "University College London"},
    {"name": "Eunice Sari", "affiliation": "UX Indonesia"},
    {"name": "Louise Barkhuus", "affiliation": "IT University of Copenhagen"},
    {"name": "Shaimaa Lazem", "affiliation": "City for Scientific Research and Technological Applications"},
    {"name": "Simon Perrault", "affiliation": "Singapore University of Technology and Design"},
    {"name": "Kashyap Todi", "affiliation": "Facebook Reality Labs"},
    {"name": "Pablo Cesar", "affiliation": "CWI"},
    {"name": "Stephanie Jordan", "affiliation": "Michigan State University"},
    {"name": "Makayla Lewis", "affiliation": "Kingston University London"},
    {"name": "Sameer Patil", "affiliation": "University of Utah"},
    {"name": "Cynthia Bennett", "affiliation": "CMU"},
    {"name": "Nova Ahmed", "affiliation": "North South University"},
    {"name": "Maryam Mustafa", "affiliation": "Lahore University of Management Sciences"},
    {"name": "Anusha Withana", "affiliation": "The University of Sydney"},
    {"name": "Pei-Yi (Patricia) Kuo", "affiliation": "National Tsing Hua University"},
    {"name": "Z Toups", "affiliation": "New Mexico State University"},
    {"name": "Jakob Karolus", "affiliation": "LMU Munich"},
    {"name": "Vicky McArthur", "affiliation": "Carleton University"},
    {"name": "Jasmine Jones", "affiliation": "Berea College"},
    {"name": "Can Liu", "affiliation": "City University of Hong Kong"},
    {"name": "Jorge Goncalves", "affiliation": "University of Melbourne, Australia"},
    {"name": "Dakuo Wang", "affiliation": "IBM"},
    {"name": "Sheena Erete", "affiliation": "DePaul University"},
    {"name": "Rita Orji", "affiliation": "Dalhousie University"},
    {"name": "Raimund Dachselt", "affiliation": "Technische Universität Dresden"},
    {"name": "Melissa Densmore", "affiliation": "University of Cape Town"},
    {"name": "Julie Kientz", "affiliation": "University of Washington"},
    {"name": "Eva Hornecker", "affiliation": "Bauhaus-Universität Weimar"},
    {"name": "Nathalie Riche", "affiliation": "Microsoft Research"},
    {"name": "Casey Fiesler", "affiliation": "University of Colorado Boulder"},
    {"name": "Jude Yew", "affiliation": "Google"},
    {"name": "Max Van Kleek", "affiliation": "University of Oxford"},
    {"name": "Fanny Chevalier", "affiliation": "University of Toronto"},
    {"name": "Carrie Cai", "affiliation": "Google"},
    {"name": "Emmanuel Pietriga", "affiliation": "Inria"},
    {"name": "Paula Lago", "affiliation": "Concordia University"},
    {"name": "Vanessa Peña-Araya", "affiliation": "Inria"},
    {"name": "Sven Mayer", "affiliation": "LMU Munich"},
    {"name": "Thomas Kosch", "affiliation": "TU Darmstadt"},
    {"name": "Raphael Wimmer", "affiliation": "University of Regensburg"},
    {"name": "Diego Muñoz", "affiliation": "Swinburne University of Technology"},
    {"name": "Alexander Mirnig", "affiliation": "University of Salzburg"},
    {"name": "Anhong Guo", "affiliation": "University of Michigan"},
    {"name": "Rob Comber", "affiliation": "KTH"},
    {"name": "Cristina Zaga", "affiliation": "University of Twente, Design Lab"},
    {"name": "Yi-Chi Liao", "affiliation": "Aalto University"},
    {"name": "Bingjie Yu", "affiliation": "NetEase"},
    {"name": "Ciabhan Connely", "affiliation": "Georgia Tech"},
    {"name": "Julia Dunbar", "affiliation": "University of Washington"},
    {"name": "Pranjal Jain", "affiliation": "theUXWhale, India"},
    {"name": "Emeline Brulé", "affiliation": "University of Sussex"},
    {"name": "Simone Kriglstein", "affiliation": "University of Vienna & AIT Austrian Institute of Technology GmbH"},
    {"name": "John Wenskovitch", "affiliation": "Pacific Northwest National Laboratory"},
    {"name": "Toni-Jan Keith Monserrat", "affiliation": "University of the Philippines Los Banos"},
    {"name": "Jie Li", "affiliation": "CWI"},
    {"name": "Dhruv Jain", "affiliation": "University of Washington"},
    {"name": "Garreth Tigwell", "affiliation": "Rochester Institute of Technology"},
    {"name": "Zainab AlMeraj", "affiliation": "Kuwait University"},
    {"name": "Kotaro Hara", "affiliation": "Singapore Management University"},
    {"name": "Venkatesh Potluri", "affiliation": "University of Washington"},
    {"name": "Shercole K.", "affiliation": "VIA LINK"},
    {"name": "Jaelle Scheuerman", "affiliation": "U.S. Naval Research Laboratory"},
    {"name": "Minha Lee", "affiliation": "Eindhoven University of Technology"},
    {"name": "Patrick Gage Kelley", "affiliation": "Google"},
    {"name": "Rua Williams", "affiliation": "Purdue University"},
    {"name": "Gopinaath Kannabiran", "affiliation": "IT University of Copenhagen"},
    {"name": "Siobahn Day Grady", "affiliation": "North Carolina Central University"},
    {"name": "Rina Wehbe", "affiliation": "University of Waterloo"},
    {"name": "Cale Passmore", "affiliation": "University of Saskatchewan"},
    {"name": "Christine Bauer", "affiliation": "Utrecht University"},
    {"name": "Annu Sible Prabhakar", "affiliation": "University of Cincinnati"},
    {"name": "Cuauhtémoc Rivera Loaiza", "affiliation": "Universidad Michoacana de San Nicolás de Hidalgo"},
    {"name": "Eiad Yafi", "affiliation": "University of Technology Sydney & Institute of Business, Timor-Leste"},
    {"name": "Susan Dray", "affiliation": "Dray & Associates"},
    {"name": "Marisol Wong-Villacres", "affiliation": "Georgia Tech"},
    {"name": "Parisa Eslambolchilar", "affiliation": "University of Cardiff"},
    {"name": "Kristin Williams", "affiliation": "CMU"},
    {"name": "Pedro Reynolds-Cuéllar", "affiliation": "MIT Media Lab"},
    {"name": "Jason Jacques", "affiliation": "University of Cambridge"},
]

chairs_2 = [
    {"name": "Yoshifumi Kitamura", "affiliation": "Tohoku University"},
    {"name": "Aaron Quigley", "affiliation": "University of New South Wales, Australia"},
    {"name": "Kaori Ikematsu", "affiliation": "Yahoo Japan Corporation"},
    {"name": "Thomas Kosch", "affiliation": "TU Darmstadt"},
    {"name": "Katherine Isbister", "affiliation": "University of California Santa Cruz"},
    {"name": "Takeo Igarashi", "affiliation": "The University of Tokyo"},
    {"name": "Yuki Koyama", "affiliation": "National Institute of Advanced Industrial Science and Technology (AIST)"},
    {"name": "Elena Márquez Segura", "affiliation": "Universidad Carlos III de Madrid"},
    {"name": "Pernille Bjørn", "affiliation": "University of Copenhagen"},
    {"name": "Steven Drucker", "affiliation": "Microsoft Research"},
    {"name": "Claudine Tinsman", "affiliation": "University of Oxford"},
    {"name": "Earl Huff", "affiliation": "Clemson University"},
    {"name": "Danielle Wilde", "affiliation": "University of Southern Denmark"},
    {"name": "Nova Ahmed", "affiliation": "North South University, Bangladesh"},
    {"name": "Pierre Dragicevic", "affiliation": "Inria, France"},
    {"name": "Haley MacLeod", "affiliation": "Facebook"},
    {"name": "Stefan Manojlovic", "affiliation": "TomTom"},
    {"name": "Carine Lallemand", "affiliation": "Eindhoven University of Technology"},
    {"name": "Antti Oulasvirta", "affiliation": "Aalto University"},
    {"name": "Pedro Lopes", "affiliation": "University of Chicago"},
    {"name": "Sylvain Malacria", "affiliation": "Inria, France"},
    {"name": "Yuta Sugiura", "affiliation": "Keio University"},
    {"name": "Yang Li", "affiliation": "Google Research"},
    {"name": "Wendy Mackay", "affiliation": "Inria, Université Paris-Saclay"},
    {"name": "Wendy Ju", "affiliation": "Cornell Tech"},
    {"name": "Leah Findlater", "affiliation": "University of Washington"},
    {"name": "Edward Melcer", "affiliation": "University of California, Santa Cruz"},
    {"name": "Katrin Wolf", "affiliation": "Beuth University of Applied Sciences Berlin"},
    {"name": "Juho Kim", "affiliation": "KAIST"},
    {"name": "Leila Takayama", "affiliation": "University of California, Santa Cruz"},
    {"name": "Dan Russell", "affiliation": "Google"},
    {"name": "Germán Leiva", "affiliation": "Aarhus University"},
    {"name": "Emeline Brulé", "affiliation": "University of Sussex"},
    {"name": "Jofish Kaye", "affiliation": "Mozilla"},
    {"name": "Hideaki Kuzuoka", "affiliation": "The University of Tokyo"},
    {"name": "Jun Kato", "affiliation": "National Institute of Advanced Industrial Science and Technology (AIST) & Arch Inc., Japan"},
    {"name": "Nolwenn Maudet", "affiliation": "University of Strasbourg"}
]


chairs_2020 = [
    {"name": "Regina Bernhaupt", "affiliation": "Eindhoven University of Technology, Netherlands"},
    {"name": "Florian 'Floyd' Mueller", "affiliation": "Monash University, Melbourne, Australia"},
    {"name": "David Verweij", "affiliation": "Open Lab, Newcastle University, Newcastle, UK"},
    {"name": "Josh Andres", "affiliation": "IBM Research & Exertion Games Lab RMIT, Melbourne, Australia"},
    {"name": "Joanna McGrenere", "affiliation": "University of British Columbia, Vancouver, Canada"},
    {"name": "Andy Cockburn", "affiliation": "University of Canterbury, Christchurch, New Zealand"},
    {"name": "Ignacio (Nacho) Avellino", "affiliation": "University of Maryland Baltimore County, MD, USA"},
    {"name": "Alix Goguey", "affiliation": "Grenoble Alpes University, Grenoble, France"},
    {"name": "Pernille Bjorn", "affiliation": "University of Copenhagen, Copenhagen, Denmark"},
    {"name": "Shengdong Zhao", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Briane Paul Samson", "affiliation": "Future University Hakodate, Japan"},
    {"name": "Rafal Kocielnik", "affiliation": "University of Washington, Seattle, USA"},
    {"name": "Ann Light", "affiliation": "University of Sussex, UK"},
    {"name": "Katta Spiel", "affiliation": "KU Leuven, Belgium"},
    {"name": "Danielle Wilde", "affiliation": "University of Southern Denmark, Denmark"},
    {"name": "Maja Vukovic", "affiliation": "IBM, Yorktown Heights, USA"},
    {"name": "Stefan Manojlovic", "affiliation": "Philips, Amsterdam, Netherlands"},
    {"name": "Daniela Busse", "affiliation": "eBay Inc., CA, USA"},
    {"name": "Rajan Vaish", "affiliation": "Snap Research, Santa Monica, USA"},
    {"name": "Ian Oakley", "affiliation": "Ulsan National Institute of Science and Technology, South Korea"},
    {"name": "Sylvain Malacria", "affiliation": "Inria, France"},
    {"name": "Walter Lasecki", "affiliation": "University of Michigan, Ann Arbor, USA"},
    {"name": "Koji Yatani", "affiliation": "University of Tokyo, Japan"},
    {"name": "Leah Findlater", "affiliation": "University of Washington, Seattle, USA"},
    {"name": "Duncan Brumby", "affiliation": "University College London, UK"},
    {"name": "Madeline Balaam", "affiliation": "KTH Royal Institute of Technology, Stockholm, Sweden"},
    {"name": "Neha Kumar", "affiliation": "Georgia Institute of Technology, Atlanta, USA"},
    {"name": "Stacey Kuznetsov", "affiliation": "Arizona State University, Tempe, USA"},
    {"name": "Jeni Paay", "affiliation": "Swinburne University of Technology, Melbourne, Australia"},
    {"name": "David Flatla", "affiliation": "University of Guelph, Canada"},
    {"name": "Zhanna Sarsenbayeva", "affiliation": "University of Melbourne, Australia"},
    {"name": "Carla Griggio", "affiliation": "The University of Tokyo, Japan"},
    {"name": "Jorge Goncalves", "affiliation": "University of Melbourne, Australia"},
    {"name": "Jonna Häkkilä", "affiliation": "University of Lapland, Rovaniemi, Finland"},
    {"name": "Katrin Wolf", "affiliation": "University of Hamburg, Germany"},
    {"name": "Bastian Pfleging", "affiliation": "Eindhoven University of Technology, Netherlands"},
    {"name": "Rob Comber", "affiliation": "KTH Royal Institute of Technology, Sweden"},
    {"name": "Mike Hazas", "affiliation": "Lancaster University, Lancashire, UK"},
    {"name": "Alexander Eiselmayer", "affiliation": "University of Zurich, Switzerland"},
    {"name": "Wanyu 'Abby' Liu", "affiliation": "IRCAM Centre Pompidou, Paris, France"},
    {"name": "Jessica Colnago", "affiliation": "Carnegie Mellon University, USA"},
    {"name": "Nicole Sultanum", "affiliation": "University of Toronto, Canada"},
    {"name": "Duncan Brumby", "affiliation": "University College London, UK"},
    {"name": "Tovi Grossman", "affiliation": "University of Toronto, Canada"},
    {"name": "Parmit Chilana", "affiliation": "Simon Fraser University, Canada"},
    {"name": "Niels van Berkel", "affiliation": "Aalborg University, Denmark"},
    {"name": "Katarzyna (Kathy) Stawarz", "affiliation": "University of Bristol, UK"},
    {"name": "Tom Horak", "affiliation": "Technische Universität Dresden, Germany"},
    {"name": "Sven Mayer", "affiliation": "Carnegie Mellon University, PA, USA"},
    {"name": "Michael Stewart", "affiliation": "James Madison University, VA, USA"},
    {"name": "Sandy Gould", "affiliation": "University of Birmingham, United Kingdom"},
    {"name": "Rakesh Patibanda", "affiliation": "Exertion Games Lab, RMIT University, Australia"},
    {"name": "Lila Bozgeyikli", "affiliation": "University of Arizona, USA"},
    {"name": "Jeffrey Bardzell", "affiliation": "Indiana University, USA"},
    {"name": "Scott Robertson", "affiliation": "University of Hawai'i, Honolulu, Hawai'i, USA"},
    {"name": "Rick Kazman", "affiliation": "University of Hawai'i, Honolulu, Hawai'i, USA"},
    {"name": "Kyle Rector", "affiliation": "University of Iowa, USA"},
    {"name": "Shari Trewin", "affiliation": "IBM Research, Yorktown, USA"},
    {"name": "Juho Kim", "affiliation": "Korea Advanced Institute of Science and Technology, South Korea"},
    {"name": "Cristina Zaga", "affiliation": "University of Twente, Netherlands"},
    {"name": "Simone Kriglstein", "affiliation": "AIT Austrian Institute of Technology, Austria"},
    {"name": "Rina Wehbe", "affiliation": "University of Waterloo, Canada"},
    {"name": "Maria Wolters", "affiliation": "Alan Turing Institute, London, UK"},
    {"name": "Robin Brewer", "affiliation": "University of Michigan, Ann Arbor, USA"},
    {"name": "Jed Brubaker", "affiliation": "University of Colorado Boulder, USA"},
    {"name": "Roman Rädle", "affiliation": "Facebook, USA"},
    {"name": "David Lindlbauer", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Kashyap Todi", "affiliation": "Aalto University, Finland"},
    {"name": "Rohit Ashok Khot", "affiliation": "RMIT University, Australia"},
    {"name": "Elisa Mekler", "affiliation": "Aalto University, Finland"},
    {"name": "Dong-Bach Vo", "affiliation": "University of Glasgow, UK"},
    {"name": "Bill Hamilton", "affiliation": "New Mexico State University, USA"},
    {"name": "Renee Noortman", "affiliation": "Eindhoven University of Technology, Netherlands"},
    {"name": "David Verweij", "affiliation": "Newcastle University, UK"},
    {"name": "Adrian Friday", "affiliation": "Lancaster University, UK"},
    {"name": "Christian Remy", "affiliation": "Aarhus University, Denmark"},
    {"name": "Mike Hazas", "affiliation": "Lancaster University, Lancashire, UK"},
    {"name": "Samuel Mann", "affiliation": "Otago Polytechnic, New Zealand"},
    {"name": "Elisabeth Churchill", "affiliation": "Google, Mountain View, USA"},
    {"name": "Masa Inakage", "affiliation": "Keio University, Japan"},
    {"name": "Max van Kleek", "affiliation": "University of Oxford, UK"},
    {"name": "Suranga Nanayakkara", "affiliation": "University of Auckland, New Zealand"},
    {"name": "Anusha Withana", "affiliation": "The University of Sydney, Australia"},
    {"name": "Mingrui Ray Zhang", "affiliation": "University of Washington, USA"},
    {"name": "Steven Rick", "affiliation": "University of California San Diego, USA"},
    {"name": "Philippe Palanque", "affiliation": "Université Toulouse III Paul Sabatier, France"}
]

chairs_2019 = [
    {"name": "Anna Cox", "affiliation": "University College London, UK"},
    {"name": "Vassilis Kostakos", "affiliation": "University of Melbourne, Australia"},
    {"name": "Katarzyna Stawarz", "affiliation": "Bristol University, UK"},
    {"name": "Niels van Berkel", "affiliation": "University of Melbourne, Australia"},
    {"name": "Anind Dey", "affiliation": "University of Washington, US"},
    {"name": "Shengdong Zhao", "affiliation": "National University of Singapore, Singapore"},
    {"name": "Briane Paul V. Samson", "affiliation": "Future University Hakodate, Japan"},
    {"name": "Sonali R. Mishra", "affiliation": "University of Washington, US"},
    {"name": "Jorge Goncalves", "affiliation": "University of Melbourne, Australia"},
    {"name": "Sandy Gould", "affiliation": "University of Birmingham, UK"},
    {"name": "Xinru Page", "affiliation": "Bentley University, US"},
    {"name": "Graham Wilson", "affiliation": "University of Strathclyde, UK"},
    {"name": "Frank Vetere", "affiliation": "University of Melbourne, Australia"},
    {"name": "Katrin Wolf", "affiliation": "Hamburg University of Applied Sciences, Germany"},
    {"name": "Rob Comber", "affiliation": "RISE Research Institutes of Sweden, Sweden"},
    {"name": "Lindsay Reynolds", "affiliation": "Facebook, US"},
    {"name": "Katie A. Siek", "affiliation": "Indiana University, US"},
    {"name": "Nazanin Andalibi", "affiliation": "University of Michigan, US"},
    {"name": "Jessica Colnago", "affiliation": "Carnegie Mellon University, US"},
    {"name": "Haley MacLeod", "affiliation": "Indiana University, US"},
    {"name": "Tovi Grossman", "affiliation": "Autodesk Research, Canada"},
    {"name": "Frederik Brudy", "affiliation": "University College London, UK"},
    {"name": "Tom Horak", "affiliation": "TU Dresden, Germany"},
    {"name": "Danula Hettiachchi", "affiliation": "University of Melbourne, Australia"},
    {"name": "Duncan Brumby", "affiliation": "University College London, UK"},
    {"name": "Cosmin Munteanu", "affiliation": "University of Toronto Mississauga, Canada"},
    {"name": "Sharon Oviatt", "affiliation": "Monash University, Australia"},
    {"name": "Marilyn Lennon", "affiliation": "University of Strathclyde, UK"},
    {"name": "Martin Halvey", "affiliation": "University of Strathclyde, UK"},
    {"name": "Lynne Hall", "affiliation": "University of Sunderland, UK"},
    {"name": "Jennefer Hart", "affiliation": "BBC, UK"},
    {"name": "Cayley MacArthur", "affiliation": "University of Waterloo, Canada"},
    {"name": "Cale Passmore", "affiliation": "University of Saskatchewan, Canada"},
    {"name": "Sunyoung Kim", "affiliation": "Rutgers University, US"},
    {"name": "Edith Law", "affiliation": "University of Waterloo, Canada"},
    {"name": "Louise Barkhuus", "affiliation": "IT University of Copenhagen, Denmark"},
    {"name": "David Flatla", "affiliation": "University of Guelph, Canada"},
    {"name": "Anicia Peters", "affiliation": "Namibia University of Science and Technology, Namibia"},
    {"name": "Anke Brock", "affiliation": "Ecole Nationale de l’Aviation Civie, France"},
    {"name": "Nitesh Goyal", "affiliation": "Google, US"},
    {"name": "Gopinaath Kannabiran", "affiliation": "Aarhus University, Denmark"},
    {"name": "Sue Fussell", "affiliation": "Cornell University, US"},
    {"name": "Hao-Chuan Wang", "affiliation": "University of California Davis, US"},
    {"name": "Naomi Yamashita", "affiliation": "Nippon Telegraph and Telephone Corporation, Japan"},
    {"name": "Daria Loi", "affiliation": "Intel Labs, US"},
    {"name": "Jofish Kaye", "affiliation": "Mozilla, US"},
    {"name": "Oliver Bates", "affiliation": "Lancaster University, UK"},
    {"name": "Adrian Friday", "affiliation": "Lancaster University, UK"},
    {"name": "Mike Hazas", "affiliation": "Lancaster University, UK"},
    {"name": "Christian Remy", "affiliation": "Aarhus University, Denmark"},
    {"name": "Maria Wolters", "affiliation": "University of Edinburgh, UK"},
    {"name": "Dakuo Wang", "affiliation": "IBM Research, US"},
    {"name": "Fatma Meawad", "affiliation": "University of Glasgow, Singapore"},
    {"name": "Rina R. Wehbe", "affiliation": "University of Waterloo, Canada"},
    {"name": "Cristina Zaga", "affiliation": "University of Twente, The Netherlands"},
    {"name": "Carman Neustaedter", "affiliation": "Simon Fraser University, Canada"},
    {"name": "Tony Tang", "affiliation": "University of Calgary, Canada"},
    {"name": "William (Bill) Hamilton", "affiliation": "New Mexico State University, US"},
    {"name": "Euan Freeman", "affiliation": "University of Glasgow, UK"},
    {"name": "Irina Shklovski", "affiliation": "IT University of Copenhagen, Denmark"},
    {"name": "Mark Handel", "affiliation": "Facebook, US"},
    {"name": "Elizabeth Churchill", "affiliation": "Google, US"},
    {"name": "Matt Jones", "affiliation": "Swansea University, UK"},
    {"name": "David McGookin", "affiliation": "Aalto University, Finland"},
    {"name": "Joanna Bergström-Lehtovirta", "affiliation": "University of Copenhagen, Denmark"},
    {"name": "Anusha Withana", "affiliation": "Saarland University, Germany"},
    {"name": "Elizabeth Buie", "affiliation": "Northumbria University, UK"},
    {"name": "Lisa Tweedie", "affiliation": "TIBCO, UK"},
    {"name": "Alan Dix", "affiliation": "Swansea University, UK"},
    {"name": "David Lindlbauer", "affiliation": "ETH Zurich, Switzerland"},
    {"name": "Roman Rädle", "affiliation": "Aarhus University, Denmark"},
    {"name": "Carol Klyver", "affiliation": "Foundations of Excellence"},
    {"name": "Roxane Rose", "affiliation": "Executivevents"},
    {"name": "Taylor Vick", "affiliation": "Executivevents"}
]
