siggraph_data = [
    {"name": "Erik Brunvand", "affiliation": "SIGGRAPH 2023 Conference Chair"},
    {"name": "Yoon Chung Han", "affiliation": "SIGGRAPH 2023 Art Gallery Chair"},
    {"name": "Nicolas Henchoz", "affiliation": "SIGGRAPH 2023 Art Papers Chair"},
    {"name": "Chris Wyman", "affiliation": "SIGGRAPH 2023 Courses Chair"},
    {"name": "Eveline Falcão", "affiliation": "SIGGRAPH 2023 Creative Development Director"},
    {"name": "Nick Jushchyshyn", "affiliation": "SIGGRAPH 2023 Education Chair"},
    {"name": "Kalina Borkiewicz", "affiliation": "SIGGRAPH 2023 Electronic Theater Director"},
    {"name": "Mashhuda Glencross", "affiliation": "SIGGRAPH 2023 Emerging Technologies Chair"},
    {"name": "Ginger Alford", "affiliation": "SIGGRAPH 2023 Frontiers Chair"},
    {"name": "Josef Spjut", "affiliation": "SIGGRAPH 2023 Games Focus Area Chair"},
    {"name": "Susan Reiser", "affiliation": "SIGGRAPH 2023 General Submissions Chair"},
    {"name": "Joseph Cychosz", "affiliation": "SIGGRAPH 2023 GraphicsNet Chair"},
    {"name": "Bonnie Mitchell", "affiliation": "SIGGRAPH 2023 History Chair"},
    {"name": "Anna Carolina Muller Queiroz", "affiliation": "SIGGRAPH 2023 Immersive Pavilion Chair"},
    {"name": "Asiya Gizatulina", "affiliation": "SIGGRAPH 2023 International Resources Committee Chair"},
    {"name": "Courtney Starrett", "affiliation": "SIGGRAPH 2023 Labs Chair"},
    {"name": "James Tompkin", "affiliation": "SIGGRAPH 2023 Posters Chair"},
    {"name": "Christine Holmes", "affiliation": "SIGGRAPH 2023 Production Sessions Chair"},
    {"name": "Cem Yuksel", "affiliation": "SIGGRAPH 2023 Real-Time Live! Chair"},
    {"name": "Meaghan Long", "affiliation": "SIGGRAPH 2023 Student Volunteer Chair"},
    {"name": "Alla Sheffer", "affiliation": "SIGGRAPH 2023 Technical Papers Chair"},
    {"name": "Julia Read", "affiliation": "SIGGRAPH 2023 VR Theater Director"},
    {"name": "Andres Burbano", "affiliation": "SIGGRAPH 2024 Conference Chair"}
]

siggraph_2022_data = [
    {"name": "Munkhtsetseg Nandigjav", "affiliation": "SIGGRAPH 2022 Conference Chair (she/her)"},
    {"name": "Daria Tsoupikova", "affiliation": "SIGGRAPH 2022 Art Gallery Chair (she/her)"},
    {"name": "Daniel Cardoso Llach", "affiliation": "SIGGRAPH 2022 Art Papers Chair (he/him)"},
    {"name": "Courtney Starrett", "affiliation": "SIGGRAPH 2022 Community Engagement Chair (she/her)"},
    {"name": "Tamar Shinar", "affiliation": "SIGGRAPH 2022 Courses Chair"},
    {"name": "Eveline Falcão", "affiliation": "SIGGRAPH 2022 Creative Development Director (she/her)"},
    {"name": "Monica Cappiello", "affiliation": "SIGGRAPH 2022 Education Liaison (she/her)"},
    {"name": "Darin Kyoichi Grant", "affiliation": "SIGGRAPH 2022 Electronic Theater Director (he/him)"},
    {"name": "MK Haley", "affiliation": "SIGGRAPH 2022 Emerging Technologies Chair"},
    {"name": "Vathsal Veena Shashidhar", "affiliation": "SIGGRAPH 2022 Frontiers Chair (he/him)"},
    {"name": "Elizabeth Baumel", "affiliation": "SIGGRAPH 2022 Games Focus Area Chair (they/them)"},
    {"name": "Chris Redmann", "affiliation": "SIGGRAPH 2022 General Submissions Chair (he/him)"},
    {"name": "Stanley Chan", "affiliation": "SIGGRAPH 2022 GraphicsNet Chair (he/him)"},
    {"name": "Derek Ham", "affiliation": "SIGGRAPH 2022 Immersive Pavilion Chair (he/him)"},
    {"name": "June Kim", "affiliation": "SIGGRAPH 2022 International Resources Committee Chair (she/her)"},
    {"name": "Kristy Pron", "affiliation": "SIGGRAPH 2022 Labs Chair"},
    {"name": "Olga Diamanti", "affiliation": "SIGGRAPH 2022 Posters Chair (she/her)"},
    {"name": "Stephanie Eisenberg", "affiliation": "SIGGRAPH 2022 Production Sessions Chair (she/her)"},
    {"name": "Yibing Jiang", "affiliation": "SIGGRAPH 2022 Real-Time Live! Chair (she/her)"},
    {"name": "Ben Lok", "affiliation": "SIGGRAPH 2022 Retrospective Chair"},
    {"name": "Roy C. Anthony", "affiliation": "SIGGRAPH 2022 Special Projects Chair"},
    {"name": "Diana Arellano", "affiliation": "SIGGRAPH 2022 Student Volunteers Chair (she/her)"},
    {"name": "Niloy J. Mitra", "affiliation": "SIGGRAPH 2022 Technical Papers Chair (he/him)"},
    {"name": "Yangos Hadjiyannis", "affiliation": "SIGGRAPH 2022 VR Theater Director (he/him)"},
    {"name": "Erik Brunvand", "affiliation": "SIGGRAPH 2023 Conference Chair"},
]

siggraph_2021_data = [
    {"name": "Jeremias Pol Jeremias-Vila", "affiliation": "SIGGRAPH 2021 Conference Chair"},
    {"name": "Tomasz Bednarz", "affiliation": "ACM SIGGRAPH Frontiers Chair"},
    {"name": "Angus Forbes", "affiliation": "SIGGRAPH 2021 Art Gallery Chair"},
    {"name": "Daria Tsoupikova", "affiliation": "SIGGRAPH 2021 Art Papers Chair"},
    {"name": "Ana Cecilia Balliache", "affiliation": "SIGGRAPH 2021 Attendee Experience Manager"},
    {"name": "Fernando de Goes", "affiliation": "SIGGRAPH 2021 Courses Chair"},
    {"name": "Vib Soundrarajah", "affiliation": "SIGGRAPH 2021 Creative Development Director"},
    {"name": "Monica Cappiello", "affiliation": "SIGGRAPH 2021 Education Liaison"},
    {"name": "Mark Elendt", "affiliation": "SIGGRAPH 2021 Electronic Theater Director"},
    {"name": "Paul Dietz", "affiliation": "SIGGRAPH 2021 Emerging Technologies Chair"},
    {"name": "Carlos Gonzalez-Ochoa", "affiliation": "SIGGRAPH 2021 Games Focus Area Chair"},
    {"name": "Chris Redmann", "affiliation": "SIGGRAPH 2021 General Submissions Chair"},
    {"name": "Callie Holderman", "affiliation": "SIGGRAPH 2021 Immersive Pavilion Chair"},
    {"name": "June Kim", "affiliation": "SIGGRAPH 2021 International Resources Chair"},
    {"name": "Michael Reed", "affiliation": "SIGGRAPH 2021 Labs Chair"},
    {"name": "David Spoelstra", "affiliation": "SIGGRAPH 2021 Platform Technology Liaison"},
    {"name": "Melina Skouras", "affiliation": "SIGGRAPH 2021 Posters Chair"},
    {"name": "John Kalaigian", "affiliation": "SIGGRAPH 2021 Production Sessions Chair"},
    {"name": "Chris Evans", "affiliation": "SIGGRAPH 2021 Real-Time Live! Chair"},
    {"name": "Andres Burbano", "affiliation": "SIGGRAPH 2021 Retrospective Chair"},
    {"name": "Ian Failes", "affiliation": "SIGGRAPH 2021 Special Projects Chair"},
    {"name": "Alex Bryant", "affiliation": "SIGGRAPH 2021 Student Volunteers Chair"},
    {"name": "Sylvain Paris", "affiliation": "SIGGRAPH 2021 Technical Papers Chair"},
    {"name": "Larry Bafia", "affiliation": "SIGGRAPH 2021 VR Theater Director"},
    {"name": "Muunuu Nandigjav", "affiliation": None},
]

siggraph_2020_data = [
    {"name": "Kristy Pron", "affiliation": "Walt Disney Imagineering (SIGGRAPH 2020 Conference Chair)"},
    {"name": "MK Haley", "affiliation": "Walt Disney Imagineering (ACM SIGGRAPH Frontiers Chair)"},
    {"name": "Christine Holmes", "affiliation": "Blue Sky Studios (Adaptability Focus Area Co-Chair)"},
    {"name": "Natalie Rountree", "affiliation": "Not specified (Adaptability Focus Area Co-Chair)"},
    {"name": "Nik Apostolides", "affiliation": "Johns Hopkins University (Art Gallery Chair)"},
    {"name": "Andres Burbano", "affiliation": "Universidad de los Andes (Art Papers Chair)"},
    {"name": "Corinne Price", "affiliation": "ICF (Attendee Experience Manager)"},
    {"name": "Susan Reiser", "affiliation": "UNC Asheville & Vassar College (Courses Chair)"},
    {"name": "Larry Bafia", "affiliation": "Centre for Digital Media (Creative Development Director)"},
    {"name": "Munkhtsetseg Nandigjav", "affiliation": "Savannah College of Art and Design (Electronic Theater Director)"},
    {"name": "Andrew Duchowski", "affiliation": "Clemson University (Education Liaison)"},
    {"name": "Dani Belko", "affiliation": "Facebook (Emerging Technologies Chair)"},
    {"name": "Carlos Gonzalez-Ochoa", "affiliation": "Not specified (Games Focus Area Chair)"},
    {"name": "Ginger Alford", "affiliation": "SMU Lyle School of Engineering (General Submissions Chair)"},
    {"name": "David Spoelstra", "affiliation": "MediaMachine LLC (GraphicsNet Chair)"},
    {"name": "Chris Redmann", "affiliation": "Unity Technologies (Immersive Pavilion Chair)"},
    {"name": "June Kim", "affiliation": "University of New South Wales (International Resources Chair)"},
    {"name": "Ana Cecilia Balliache Liendo", "affiliation": "Schell Games (Posters Chair)"},
    {"name": "Derrick Nau", "affiliation": "DreamWorks Animation (Production Sessions Chair)"},
    {"name": "Marc Olano", "affiliation": "University of Maryland, Baltimore County (Real-Time Live! Chair)"},
    {"name": "Thierry Frey", "affiliation": "Reel FX Animation Studios (SIGGRAPH Executive Experience Co-Chair)"},
    {"name": "Joanne Green", "affiliation": "University of Pittsburgh (SIGGRAPH Executive Experience Co-Chair)"},
    {"name": "Erik Brunvand", "affiliation": "University of Utah (SIGGRAPH Labs Co-Chair)"},
    {"name": "Forrest Lucas", "affiliation": "Two Bit Circus (SIGGRAPH Labs Co-Chair)"},
    {"name": "Sarah Rust", "affiliation": "Rooster Teeth (Student Volunteers Chair)"},
    {"name": "Szymon Rusinkiewicz", "affiliation": "Princeton University (Technical Papers Chair)"},
    {"name": "Monica Cappiello", "affiliation": "Cogswell Polytechnical College (VR Theater Director)"},
    {"name": "Pol Jeremias-Vila", "affiliation": "Pixar Animation Studios (SIGGRAPH 2021 Conference Chair)"},
]

siggraph_2019_data = [
    {"name": "Mikki Rose", "affiliation": "Blue Sky Studios (SIGGRAPH 2019 Conference Chair)"},
    {"name": "Natalie Rountree", "affiliation": "Not specified (Adaptive Technology Co-Chair)"},
    {"name": "Dylan Moore", "affiliation": "Not specified (Adaptive Technology Co-Chair)"},
    {"name": "Brittany Ransom", "affiliation": "California State University Long Beach (Art Gallery Chair)"},
    {"name": "Everardo Reyes", "affiliation": "Université Paris 8 (Art Papers Editor)"},
    {"name": "Joshua Grow", "affiliation": "Zorroa (Attendee Experience Manager)"},
    {"name": "Mark Elendt", "affiliation": "SideFX Software (Birds of a Feather Coordinator)"},
    {"name": "Adele Newton", "affiliation": "Executive Director, CS-Can (Business Symposium Chair)"},
    {"name": "Emily Hsu", "affiliation": "Blizzard Entertainment (Computer Animation Festival Director)"},
    {"name": "Michael Reed", "affiliation": "Blue Sky Studios (Courses Chair)"},
    {"name": "Munkhtsetseg Nandigjav", "affiliation": "Savannah College of Art and Design (Creative Development Director)"},
    {"name": "Andrew Duchowski", "affiliation": "Clemson University (Education Liaison)"},
    {"name": "Courtney Starrett", "affiliation": "Seton Hall University (Emerging Technologies Chair)"},
    {"name": "Christine Holmes", "affiliation": "Blue Sky Studios (Experience Hall Manager)"},
    {"name": "Christopher Evans", "affiliation": "Epic Games (Games Co-Chair)"},
    {"name": "Laurent Delayen", "affiliation": "Epic Games (Games Co-Chair)"},
    {"name": "Ginger Alford", "affiliation": "Trinity Valley School & Southern Methodist University (General Submissions Chair)"},
    {"name": "Carlos Cardenas", "affiliation": "Qualcomm Inc. (GraphicsNet Chair)"},
    {"name": "June Kim", "affiliation": "University of New South Wales (International Resources Chair)"},
    {"name": "Jim Kilmer", "affiliation": "The OPAL Group (Pathfinders Coordinator)"},
    {"name": "AJ Christensen", "affiliation": "National Center for Supercomputing Applications (NCSA) (Posters Coordinator)"},
    {"name": "Derrick Nau", "affiliation": "DreamWorks Animation (Production Sessions Chair)"},
    {"name": "Gracie Arenas Stritmatter", "affiliation": "BioWare/EA (Real-Time Live! Chair)"},
    {"name": "MK Haley", "affiliation": "Walt Disney Imagineering (SIGGRAPH Frontiers Talks Chair)"},
    {"name": "Corinne Price", "affiliation": "ICF (Student Volunteer Chair)"},
    {"name": "Chrissy Cain", "affiliation": "Santa Cruz Bicycles (Studio Chair)"},
    {"name": "Olga Sorkine-Hornung", "affiliation": "ETH Zurich (Technical Papers Chair)"},
    {"name": "Maxwell Planck", "affiliation": "Adventure Lab (VR Theater Director)"},
    {"name": "Victoria Rege", "affiliation": "Graphcore (Immersive Pavilion Chair)"},
    {"name": "Kristy Pron", "affiliation": "Walt Disney Imagineering (SIGGRAPH 2020 Conference Chair)"},
]

i3dg_2023 = [
    {"name": "Erik Sintorn", "affiliation": "Chalmers University of Technology, Sweden"},
    {"name": "Bart Wroński", "affiliation": "NVIDIA Corporation"},
    {"name": "Michael Doggett", "affiliation": "Lund University, Sweden"},
    {"name": "Angelo Pesce", "affiliation": "Roblox"},
    {"name": "Markus Billeter", "affiliation": "School of Computing, University of Leeds"},
    {"name": "Mauricio Vives", "affiliation": "Autodesk, Inc."},
    {"name": "Xiaoxi Liu", "affiliation": "Unity Technologies"},
{"name": "Christoph Peters", "affiliation": "University of Bonn"},
    {"name": "Tiow Seng Tan", "affiliation": "National University of Singapore"},
    {"name": "Yusuke Tokuyoshi", "affiliation": "AMD Japan Ltd."},
    {"name": "Shiguang Liu", "affiliation": "Tianjin University"},
    {"name": "Corey Toler-Franklin", "affiliation": "University of Florida"},
    {"name": "Nicolas Savva", "affiliation": "Autodesk, Inc."},
    {"name": "Markus Billeter", "affiliation": "University of Leeds"},
    {"name": "Michal Iwanicki", "affiliation": "Activision"},
    {"name": "Jon Hasselgren", "affiliation": "NVIDIA"},
    {"name": "Elena Garces", "affiliation": "Universidad"},
    {"name": "Konstantin Shkurko", "affiliation": "University of Utah"},
    {"name": "Colin Barré-Brisebois", "affiliation": "SEED, Electronic Arts"},
    {"name": "Javier Meseguer de Paz", "affiliation": "Next Limit Technologies"},
    {"name": "Markus Billeter", "affiliation": "University of Leeds"},
    {"name": "Yann Savoye", "affiliation": "Liverpool John Moores University"},
    {"name": "Jiri Bittner", "affiliation": "Czech Technical University in Prague"},
    {"name": "Bart Wronski", "affiliation": "NVIDIA"},
    {"name": "John Hable", "affiliation": "Unity Technologies"},
    {"name": "Eric Guérin", "affiliation": "LIRIS"},
    {"name": "Ludovic Hoyet", "affiliation": "INRIA Rennes - Centre Bretagne Atlantique"},
    {"name": "Ulf Assarsson", "affiliation": "Chalmers University of Technology"},
    {"name": "Erik Sintorn", "affiliation": "Chalmers University of Technology"},
    {"name": "Chris Oat", "affiliation": "Rockstar Games"},
    {"name": "Soufiane Khiat", "affiliation": "Unity Technologies"},
    {"name": "Dr. Mansi Sharma", "affiliation": "Indian Institute of Technology, Delhi"},
    {"name": "Petrik Clarberg", "affiliation": "NVIDIA"},
    {"name": "Wallace Lages", "affiliation": "Northeastern University"},
    {"name": "Romain Pacanowski", "affiliation": "INRIA"},
    {"name": "Christiaan Gribble", "affiliation": "Advanced Micro Devices, Inc."}

]

i3dg_2022 = [
    {"name": "Michael Doggett", "affiliation": "Lund University, Sweden"},
    {"name": "Angelo Pesce", "affiliation": "Roblox"},
    {"name": "Ulf Assarsson", "affiliation": "Chalmers University of Technology, Goteborg, Sweden"},
    {"name": "Ari Silvennoinen", "affiliation": "Activision Publishing, Inc."},
    {"name": "Petrik Clarberg", "affiliation": "NVIDIA Corporation"},
    {"name": "Christoph Peters", "affiliation": "Intel"},
    {"name": "Mauricio Vives", "affiliation": "Autodesk, Inc."},
{"name": "Marc Comino Trinidad", "affiliation": "Universidad Rey Juan Carlos"},
    {"name": "Ann Mcnamara", "affiliation": "Texas A&M University"},
    {"name": "Kun Zhou", "affiliation": "Zhejiang University"},
    {"name": "José A. Iglesias Guitián", "affiliation": "University of A Coruña (UDC), CITIC - Centre for ICT Research"},
    {"name": "Christiaan Gribble", "affiliation": "SURVICE Engineering Company"},
    {"name": "Aline Normoyle", "affiliation": "Bryn Mawr College"},
    {"name": "Markus Billeter", "affiliation": "University of Leeds"},
    {"name": "Elena Garces", "affiliation": "Universidad"},
    {"name": "Kevin Myers", "affiliation": "Activision"},
    {"name": "Adrien Gruson", "affiliation": "etsmtl.ca"},
    {"name": "Dr. Mansi Sharma", "affiliation": "Indian Institute of Technology, Delhi"},
    {"name": "Yury Uralsky", "affiliation": "NVIDIA"},
    {"name": "Tan Tiow Seng", "affiliation": "National University of Singapore"},
    {"name": "Nicolas Savva", "affiliation": "Autodesk, Inc."},
    {"name": "Corey Toler-Franklin", "affiliation": "University of Florida"},
    {"name": "Eric Guérin", "affiliation": "LIRIS"},
    {"name": "Romain Pacanowski", "affiliation": "CNRS"},
    {"name": "Marco Salvi", "affiliation": "NVIDIA"},
    {"name": "Qi Sun", "affiliation": "New York University"},
    {"name": "Benjamin Watson", "affiliation": "North Carolina State University"},
    {"name": "Konstantin Shkurko", "affiliation": "University of Utah"},
    {"name": "Jiri Bittner", "affiliation": "Czech Technical University in Prague"},
    {"name": "Erik Sintorn", "affiliation": "Chalmers University of Technology"},
    {"name": "Chris Oat", "affiliation": "Rockstar Games"},
    {"name": "Sumanta Pattanaik", "affiliation": "UCF"},
    {"name": "Michal Iwanicki", "affiliation": "Activision"},
    {"name": "Adrien Dubouchet", "affiliation": "Activision"},
    {"name": "Shuang Zhao", "affiliation": "University of California, Irvine"},
    {"name": "Sebastien Hillaire", "affiliation": "Epic Games"},
    {"name": "Theresa Foley", "affiliation": "NVIDIA Corporation"},
    {"name": "Helge Rhodin", "affiliation": "EPFL Lausanne, Switzerland"},
    {"name": "Ludovic Hoyet", "affiliation": "INRIA Rennes - Centre Bretagne Atlantique"},
    {"name": "Leonardo Scandolo", "affiliation": "IMDEA Software"},
    {"name": "Yusuke Tokuyoshi", "affiliation": "AMD Japan Ltd."},
    {"name": "Jonathan Dupuy", "affiliation": "Unity Technologies"},
    {"name": "Yann Savoye", "affiliation": "Liverpool John Moores University"}

]

i3dg_2021 = [
    {"name": "Ulf Assarsson", "affiliation": "Chalmers University of Technology, Goteborg, Sweden"},
    {"name": "Ari Silvennoinen", "affiliation": "Activision Publishing, Inc."},
    {"name": "Dan Casas", "affiliation": "Universidad Rey Juan Carlos, Madrid"},
    {"name": "Eric Haines", "affiliation": "NVIDIA"},
    {"name": "Zdravko Velinov", "affiliation": "Creative Assembly Sofia"},
    {"name": "Mauricio Vives", "affiliation": "Autodesk, Inc."},
{"name": "Laurent Belcour", "affiliation": "Unity Technologies"},
    {"name": "Jiri Bittner", "affiliation": "Czech Technical University in Prague"},
    {"name": "Petrik Clarberg", "affiliation": "NVIDIA"},
    {"name": "Marc Comino", "affiliation": "Universitat Politècnica de Catalunya"},
    {"name": "Jonathan Dupuy", "affiliation": "Unity Technologies"},
    {"name": "Tim Foley", "affiliation": "NVIDIA"},
    {"name": "Mihai Francu", "affiliation": "University of Copenhagen"},
    {"name": "Elena Garces", "affiliation": "King Juan Carlos University"},
    {"name": "Christiaan Gribble", "affiliation": "SURVICE Engineering Company"},
    {"name": "Adrien Gruson", "affiliation": "McGill University"},
    {"name": "Sebastien Hillaire", "affiliation": "Epic Games"},
    {"name": "Naty Hoffman", "affiliation": "Lucasfilm"},
    {"name": "Daniel Holden", "affiliation": "Ubisoft La Forge"},
    {"name": "Ludovic Hoyet", "affiliation": "INRIA Rennes - Centre Bretagne Atlantique"},
    {"name": "Jose A. Iglesias Guitian", "affiliation": "University of A Coruña (UDC)"},
    {"name": "Michal Iwanicki", "affiliation": "Activision"},
    {"name": "Soufiane Khiat", "affiliation": "Unity Technologies"},
    {"name": "Wallace Lages", "affiliation": "Virginia Tech"},
    {"name": "Miles Macklin", "affiliation": "NVIDIA / University of Copenhagen"},
    {"name": "Ann Mcnamara", "affiliation": "Texas A&M University"},
    {"name": "Aline Normoyle", "affiliation": "Swarthmore College"},
    {"name": "Chris Oat", "affiliation": "Rockstar Games"},
    {"name": "Romain Pacanowski", "affiliation": "CNRS"},
    {"name": "Sumanta Pattanaik", "affiliation": "UCF"},
    {"name": "Jesús Pérez", "affiliation": "URJC"},
    {"name": "Helge Rhodin", "affiliation": "EPFL Lausanne, Switzerland"},
    {"name": "Marco Salvi", "affiliation": "NVIDIA"},
    {"name": "Yann Savoye", "affiliation": "Liverpool John Moore University / LJMU"},
    {"name": "Nicolas Savva", "affiliation": "Autodesk, Inc."},
    {"name": "Erik Sintorn", "affiliation": "Chalmers University of Technology"},
    {"name": "Qi Sun", "affiliation": "Adobe Research"},
    {"name": "Corey Toler-Franklin", "affiliation": "University of Florida"},
    {"name": "Yury Uralsky", "affiliation": "NVIDIA"},
    {"name": "Michael Vance", "affiliation": "Activision"},
    {"name": "Marco Volino", "affiliation": "University of Surrey"},
    {"name": "Benjamin Watson", "affiliation": "North Carolina State University"},
    {"name": "Shuang Zhao", "affiliation": "University of California, Irvine"},
    {"name": "Kun Zhou", "affiliation": "Zhejiang University"}
]

i3dg_2020 = [
    {"name": "Dan Casas", "affiliation": "Universidad Rey Juan Carlos, Madrid"},
    {"name": "Eric Haines", "affiliation": "NVIDIA"},
    {"name": "Sheldon Andrews", "affiliation": "École de technologie supérieure"},
    {"name": "Natalya Tatarchuk", "affiliation": "Unity Technologies"},
    {"name": "Zdravko Velinov", "affiliation": "Disney Research LA"},
{"name": "Ulf Assarsson", "affiliation": "Chalmers University of Technology"},
    {"name": "Laurent Belcour", "affiliation": "Unity Technologies"},
    {"name": "Ari Rapkin Blenkhorn", "affiliation": "Johns Hopkins University Applied Physics Lab"},
    {"name": "Ronan Boulic", "affiliation": "Ecole Polytechnique Federale de Lausanne"},
    {"name": "Derek Bradley", "affiliation": "Disney Research"},
    {"name": "Petrik Clarberg", "affiliation": "NVIDIA"},
    {"name": "Matthew Cong", "affiliation": "Industrial Light and Magic"},
    {"name": "Jeremy Cowles", "affiliation": "Unity Technologies"},
    {"name": "Jonathan Dupuy", "affiliation": "Unity Technologies"},
    {"name": "Elmar Eisemann", "affiliation": "Delft University of Technology"},
    {"name": "Tim Foley", "affiliation": "NVIDIA"},
    {"name": "Mihai Francu", "affiliation": "University of Copenhagen"},
    {"name": "Abhinav Golas", "affiliation": "Samsung Research America"},
    {"name": "Adrien Gruson", "affiliation": "McGill University"},
    {"name": "Eric Guérin", "affiliation": "INSA de Lyon"},
    {"name": "Toshiya Hachisuka", "affiliation": "The University of Tokyo"},
    {"name": "Eric Heitz", "affiliation": "Unity Technologies"},
    {"name": "Sebastien Hillaire", "affiliation": "Epic Games"},
    {"name": "Naty Hoffman", "affiliation": "Lucasfilm"},
    {"name": "Daniel Holden", "affiliation": "Ubisoft La Forge"},
    {"name": "Jose A. Iglesias Guitian", "affiliation": "University of A Coruña (UDC)"},
    {"name": "Michal Iwanicki", "affiliation": "Activision"},
    {"name": "Anton Kaplanyan", "affiliation": "Facebook"},
    {"name": "Sofian Khiat", "affiliation": "Unity Technologies"},
    {"name": "Miles Macklin", "affiliation": "NVIDIA / University of Copenhagen"},
    {"name": "Steve McAuley", "affiliation": "Ubisoft Montreal"},
    {"name": "Michael McGuffin", "affiliation": "ETS Montreal"},
    {"name": "Morgan McGuire", "affiliation": "NVIDIA"},
    {"name": "Aline Normoyle", "affiliation": "Swarthmore College"},
    {"name": "Carol O'Sullivan", "affiliation": "Trinity College Dublin"},
    {"name": "Chris Oat", "affiliation": "Rockstar Games"},
    {"name": "Anjul Patney", "affiliation": "NVIDIA"},
    {"name": "Sumanta Pattanaik", "affiliation": "UCF"},
    {"name": "Nuria Pelechano", "affiliation": "Universitat Politecnica de Catalunya"},
    {"name": "Angelo Pesce", "affiliation": "Activision"},
    {"name": "Jesús Pérez", "affiliation": "URJC"},
    {"name": "Marco Salvi", "affiliation": "NVIDIA"},
    {"name": "Tamar Shinar", "affiliation": "University of California Riverside"},
    {"name": "Erik Sintorn", "affiliation": "Chalmers University of Technology"},
    {"name": "Michael Stengel", "affiliation": "NVIDIA"},
    {"name": "Qi Sun", "affiliation": "NVIDIA"},
    {"name": "Andrea Tagliasacchi", "affiliation": "Google Brain"},
    {"name": "Steve Tonneau", "affiliation": "University of Edinburgh"},
    {"name": "Yury Uralsky", "affiliation": "NVIDIA"},
    {"name": "Michael Vance", "affiliation": "Activision"},
    {"name": "Kangxue Yin", "affiliation": "Simon Fraser University"},
    {"name": "Sung-Eui Yoon", "affiliation": "KAIST"},
    {"name": "Cem Yuksel", "affiliation": "University of Utah"},
    {"name": "Gabriel Zachmann", "affiliation": "University of Bremen"},
    {"name": "Shuang Zhao", "affiliation": "University of California Irvine"}
]

i3dg_2019 = [
    {"name": "Sheldon Andrews", "affiliation": "École de technologie supérieure"},
    {"name": "Natalya Tatarchuk", "affiliation": "Unity Technologies"},
    {"name": "Morgan McGuire", "affiliation": "NVIDIA"},
    {"name": "Derek Nowrouzezahrai", "affiliation": "McGill University"},
    {"name": "Dan Casas", "affiliation": "Universidad Rey Juan Carlos, Madrid"},
    {"name": "Ulf Assarsson", "affiliation": "Chalmers University of Technology"},
    {"name": "Norman Badler", "affiliation": "University of Pennsylvania"},
    {"name": "Laurent Belcour", "affiliation": "Unity Research"},
    {"name": "Ari Rapkin Blenkhorn", "affiliation": "Leidos"},
    {"name": "Tamy Boubekeur", "affiliation": "Telecom ParisTech"},
    {"name": "Dan Calian", "affiliation": "University College London"},
    {"name": "Petrik Clarberg", "affiliation": "NVIDIA"},
    {"name": "Michael Doggett", "affiliation": "Lund University"},
    {"name": "Jonathan Dupuy", "affiliation": "Unity Research"},
    {"name": "Elmar Eisemann", "affiliation": "Delft University of Technology"},
    {"name": "Tim Foley", "affiliation": "NVIDIA"},
    {"name": "Eric Haines", "affiliation": "NVIDIA"},
    {"name": "Eric Heitz", "affiliation": "Unity Technologies"},
    {"name": "Anton Kaplanyan", "affiliation": "Oculus Research"},
    {"name": "John Keyser", "affiliation": "Texas A & M University"},
    {"name": "Paul Lalonde", "affiliation": "Google"},
    {"name": "Douglas Lanman", "affiliation": ""},
    {"name": "David McAllister", "affiliation": ""},
    {"name": "Bochang Moon", "affiliation": "Gwangju Institute of Science and Technology"},
    {"name": "Matthias Niessner", "affiliation": "Technical University of Munich"},
    {"name": "Aline Normoyle", "affiliation": "University of Pennsylvania"},
    {"name": "Romain Pacanowski", "affiliation": "CNRS"},
    {"name": "Anjul Patney", "affiliation": "NVIDIA"},
    {"name": "Sumanta Pattanaik", "affiliation": "University of Central Florida"},
    {"name": "Nuria Pelechano", "affiliation": "Universitat Politècnica de Catalunya"},
    {"name": "Tobias Ritschel", "affiliation": "MPI Informatik"},
    {"name": "Marco Salvi", "affiliation": "NVIDIA"},
    {"name": "Pedro Sander", "affiliation": "The Hong Kong University of Science and Technology"},
    {"name": "Ari Shapiro", "affiliation": "University of Southern California"},
    {"name": "Tamar Shinar", "affiliation": "University of California Riverside"},
    {"name": "Erik Sintorn", "affiliation": "Chalmers University of Technology"},
    {"name": "Michael Stengel", "affiliation": "NVIDIA"},
    {"name": "Kartic Subr", "affiliation": "University of Edinburgh"},
    {"name": "Qi Sun", "affiliation": "Adobe Research"},
    {"name": "Ingo Wald", "affiliation": "NVIDIA"},
    {"name": "Huamin Wang", "affiliation": "The Ohio State University"},
    {"name": "Sung-Eui Yoon", "affiliation": "Korea Advanced Institute of Science and Technology"},
    {"name": "Cem Yuksel", "affiliation": "University of Utah"},
    {"name": "Shuang Zhao", "affiliation": "University of California Irvine"},
    {"name": "Kun Zhou", "affiliation": "Zhejiang University"}
]


new_2023 = [
    {"name": "Alla Sheff er", "affiliation": "Unknown"},
    {"name": "Michael Wimmer", "affiliation": "Unknown"},
    {"name": "Maneesh Agrawala", "affiliation": "Unknown"},
    {"name": "Kavita Bala", "affiliation": "Unknown"},
    {"name": "Bernd Bickel", "affiliation": "Unknown"},
    {"name": "Tao Ju", "affiliation": "Unknown"},
    {"name": "Jaakko Lehtinen", "affiliation": "Unknown"},
    {"name": "Ming Lin", "affiliation": "Unknown"},
    {"name": "Xin Tong", "affiliation": "Unknown"},
    {"name": "Michiel van de Panne", "affiliation": "Unknown"},
    {"name": "Chris Wojtan", "affiliation": "Unknown"},
    {"name": "Kun Zhou", "affiliation": "Unknown"},
    {"name": "Denis Zorin", "affiliation": "Unknown"},
    {"name": "Miika Aittala", "affiliation": "Unknown"},
    {"name": "Hadar Averbuch-Elor", "affiliation": "Unknown"},
    {"name": "Moritz Baecher", "affiliation": "Unknown"},
    {"name": "Christopher Batty", "affiliation": "Unknown"},
    {"name": "Mirela Ben-Chen", "affiliation": "Unknown"},
    {"name": "Bedrich Benes", "affiliation": "Unknown"},
    {"name": "Amit H. Bermano", "affiliation": "Unknown"},
    {"name": "Florence Bertails-Descoubes", "affiliation": "Unknown"},
    {"name": "Mikhail Bessmeltsev", "affiliation": "Unknown"},
    {"name": "David Bommes", "affiliation": "Unknown"},
    {"name": "Tamy Boubekeur", "affiliation": "Unknown"},
    {"name": "Adrien Bousseau", "affiliation": "Unknown"},
    {"name": "Derek Bradley", "affiliation": "Unknown"},
    {"name": "Marcel Campen", "affiliation": "Unknown"},
    {"name": "Nathan Carr", "affiliation": "Unknown"},
    {"name": "Duygu Ceylan", "affiliation": "Unknown"},
    {"name": "Siddhartha Chaudhuri", "affiliation": "Unknown"},
    {"name": "Jiawen Chen", "affiliation": "Unknown"},
    {"name": "Fanny Chevalier", "affiliation": "Unknown"},
    {"name": "Piotr Didyk", "affiliation": "Unknown"},
    {"name": "Julie Digne", "affiliation": "Unknown"},
    {"name": "Elmar Eisemann", "affiliation": "Unknown"},
    {"name": "Ohad Fried", "affiliation": "Unknown"},
    {"name": "Chi Wing Fu", "affiliation": "Unknown"},
    {"name": "Lin Gao", "affiliation": "Unknown"},
    {"name": "Eitan Grinspun", "affiliation": "Unknown"},
    {"name": "Yulia Gryaditskaya", "affiliation": "Unknown"},
    {"name": "Diego Gutierrez", "affiliation": "Unknown"},
    {"name": "Rana Hanocka", "affiliation": "Unknown"},
    {"name": "Peter Hedman", "affiliation": "Unknown"},
    {"name": "Felix Heide", "affiliation": "Unknown"},
    {"name": "Jessica Hodgins", "affiliation": "Unknown"},
    {"name": "Ruizhen Hu", "affiliation": "Unknown"},
    {"name": "Jia-Bin Huang", "affiliation": "Unknown"},
    {"name": "Jin Huang", "affiliation": "Unknown"},
    {"name": "Takeo Igarashi", "affiliation": "Unknown"},
    {"name": "Wenzel Jakob", "affiliation": "Unknown"},
    {"name": "Anton Kaplanyan", "affiliation": "Unknown"},
    {"name": "Danny Kaufman", "affiliation": "Unknown"},
    {"name": "Vladimir Kim", "affiliation": "Unknown"},
    {"name": "Taku Komura", "affiliation": "Unknown"},
    {"name": "Mina Konakovic-Lukovic", "affiliation": "Unknown"},
    {"name": "Sylvain Lefebvre", "affiliation": "Unknown"},
    {"name": "Anat Levin", "affiliation": "Unknown"},
    {"name": "Wilmot Li", "affiliation": "Unknown"},
    {"name": "Ming Lin", "affiliation": "Unknown"},
    {"name": "Lingjie Liu", "affiliation": "Unknown"},
    {"name": "Marco Livesu", "affiliation": "Unknown"},
    {"name": "Rafal K. Mantiuk", "affiliation": "Unknown"},
    {"name": "Belen Masia", "affiliation": "Unknown"},
    {"name": "James McCann", "affiliation": "Unknown"},
    {"name": "Dominik Michels", "affiliation": "Unknown"},
    {"name": "Rahul Narain", "affiliation": "Unknown"},
    {"name": "Michael Neff", "affiliation": "Unknown"},
    {"name": "Carol O'Sullivan", "affiliation": "Unknown"},
    {"name": "Nico Pietroni", "affiliation": "Unknown"},
    {"name": "Yael Pritch", "affiliation": "Unknown"},
    {"name": "Jing Ren", "affiliation": "Unknown"},
    {"name": "Tobias Ritschel", "affiliation": "Unknown"},
    {"name": "Holly Rushmeier", "affiliation": "Unknown"},
    {"name": "Manolis Savva", "affiliation": "Unknown"},
    {"name": "Adriana Schulz", "affiliation": "Unknown"},
    {"name": "Ariel Shamir", "affiliation": "Unknown"},
    {"name": "Tianjia Shao", "affiliation": "Unknown"},
    {"name": "Tamar Shinar", "affiliation": "Unknown"},
    {"name": "Melina Skouras", "affiliation": "Unknown"},
    {"name": "Philipp Slusallek", "affiliation": "Unknown"},
    {"name": "Markus Steinberger", "affiliation": "Unknown"},
    {"name": "Hao Su", "affiliation": "Unknown"},
    {"name": "Shinjiro Sueda", "affiliation": "Unknown"},
    {"name": "Andrea Tagliasacchi", "affiliation": "Unknown"},
    {"name": "Bernhard Th omaszewski", "affiliation": "Unknown"},
    {"name": "Beibei Wang", "affiliation": "Unknown"},
    {"name": "Rui Wang", "affiliation": "Unknown"},
    {"name": "Bin Wang", "affiliation": "Unknown"},
    {"name": "Huamin Wang", "affiliation": "Unknown"},
    {"name": "Wenping Wang", "affiliation": "Unknown"},
    {"name": "Li-Yi Wei", "affiliation": "Unknown"},
    {"name": "Gordon Wetzstein", "affiliation": "Unknown"},
    {"name": "Alexander Wilkie", "affiliation": "Unknown"},
    {"name": "Feng Xu", "affiliation": "Unknown"},
    {"name": "Ling-Qi Yan", "affiliation": "Unknown"},
    {"name": "Yuting Ye", "affiliation": "Unknown"},
    {"name": "Lap-Fai Yu", "affiliation": "Unknown"},
    {"name": "Shuang Zhao", "affiliation": "Unknown"},
    {"name": "Yi Zhou", "affiliation": "Unknown"},
    {"name": "Bo Zhu", "affiliation": "Unknown"},
    {"name": "Denis Zorin", "affiliation": "Unknown"},
    {"name": "Andrew Adams", "affiliation": "Unknown"},
    {"name": "Marco Attene", "affiliation": "Unknown"},
    {"name": "Robert Bridson", "affiliation": "Unknown"},
    {"name": "Angel Chang", "affiliation": "Unknown"},
    {"name": "Stelian Coros", "affiliation": "Unknown"},
    {"name": "Eugene d'Eon", "affiliation": "Unknown"},
    {"name": "Iliyan Georgiev", "affiliation": "Unknown"},
    {"name": "Michael Gharbi", "affiliation": "Unknown"},
    {"name": "Toshiya Hachisuka", "affiliation": "Unknown"},
    {"name": "Bernhard Kerbl", "affiliation": "Unknown"},
    {"name": "Sung-Hee Lee", "affiliation": "Unknown"},
    {"name": "Céline Loscos", "affiliation": "Unknown"},
    {"name": "Wojciech Matusik", "affiliation": "Unknown"},
    {"name": "Matthew O'Toole", "affiliation": "Unknown"},
    {"name": "Michael Rubinstein", "affiliation": "Unknown"},
    {"name": "Eli Shechtman", "affiliation": "Unknown"},
    {"name": "Peter-Pike Sloan", "affiliation": "Unknown"},
    {"name": "Marc Stamminger", "affiliation": "Unknown"},
    {"name": "Kartic Subr", "affiliation": "Unknown"},
    {"name": "Daniel Sykora", "affiliation": "Unknown"},
    {"name": "Matthias Teschner", "affiliation": "Unknown"},
    {"name": "Christian Th eobalt", "affiliation": "Unknown"},
    {"name": "Nils Th uerey", "affiliation": "Unknown"},
    {"name": "Amir Vaxman", "affiliation": "Unknown"},
    {"name": "Nicholas Vining", "affiliation": "Unknown"},
    {"name": "Michael Wand", "affiliation": "Unknown"},
    {"name": "Tim Weyrich", "affiliation": "Unknown"},
    {"name": "Emily Whiting", "affiliation": "Unknown"},
    {"name": "Changxi Zheng", "affiliation": "Unknown"}
]

new_2022 = [
    {"name": "Niloy J. Mitra", "affiliation": "Unknown"},
    {"name": "Miika Aittala", "affiliation": "NVIDIA"},
    {"name": "Bedrich Benes", "affiliation": "Purdue University"},
    {"name": "Amit H. Bermano", "affiliation": "Tel Aviv University"},
    {"name": "Mikhail Bessmeltsev", "affiliation": "University of Montreal"},
    {"name": "Nicolas Bonneel", "affiliation": "CNRS, University of Lyon"},
    {"name": "Marcel Campen", "affiliation": "Osnabrück University"},
    {"name": "Jiawen Chen", "affiliation": "Adobe Inc."},
    {"name": "Sunghee Choi", "affiliation": "Korea Advanced Institute of Science and Technology (KAIST)"},
    {"name": "Daniel Cohen-Or", "affiliation": "Tel Aviv University"},
    {"name": "Angela Dai", "affiliation": "Technical University of Munich"},
    {"name": "Fernando de Goes", "affiliation": "Pixar"},
    {"name": "Tali Dekel", "affiliation": "Google Inc., Weizmann Institute"},
    {"name": "Julie Digne", "affiliation": "CNRS, LIRIS"},
    {"name": "George Drettakis", "affiliation": "INRIA, Université Côte d’Azur"},
    {"name": "Sanja Fidler", "affiliation": "University of Toronto, NVIDIA"},
    {"name": "Matthew Fisher", "affiliation": "Adobe Research"},
    {"name": "Ohad Fried", "affiliation": "Th e Interdisciplinary Center Herzliya"},
    {"name": "Chi Wing Fu", "affiliation": "Chinese University of Hong Kong"},
    {"name": "Hongbo Fu", "affiliation": "City University of Hong Kong; CS Dept, Tsinghua University"},
    {"name": "Th omas Funkhouser", "affiliation": "Princeton University, Google Research"},
    {"name": "Yotam Gingold", "affiliation": "George Mason University"},
    {"name": "Ioannis Gkioulekas", "affiliation": "Carnegie Mellon University"},
    {"name": "Yulia Gryaditskaya", "affiliation": "CVSSP, University of Surrey"},
    {"name": "Sehoon Ha", "affiliation": "Georgia Institute of Technology, Google Inc."},
    {"name": "Rana Hanocka", "affiliation": "University of Chicago"},
    {"name": "Mingming He", "affiliation": "USC Institute for Creative Technologies (ICT)"},
    {"name": "Peter Hedman", "affiliation": "Google Inc."},
    {"name": "Felix Heide", "affiliation": "Princeton University, Algolux"},
    {"name": "Philipp Herholz", "affiliation": "ETH"},
    {"name": "Nicolas Holzschuch", "affiliation": "INRIA"},
    {"name": "Hui Huang", "affiliation": "Shenzhen University"},
    {"name": "Jia-Bin Huang", "affiliation": "Meta; University of Maryland, College Park"},
    {"name": "Matthias Hullin", "affiliation": "University of Bonn"},
    {"name": "Takeo Igarashi", "affiliation": "University of Tokyo, Preferred Networks"},
    {"name": "Angjoo Kanazawa", "affiliation": "UC Berkeley"},
    {"name": "Danny Kaufman", "affiliation": "Adobe"},
    {"name": "Min H. Kim", "affiliation": "Korea Advanced Institute of Science and Technology (KAIST)"},
    {"name": "Taku Komura", "affiliation": "University of Hong Kong, University of Edinburgh"},
    {"name": "Mina Konakovic-Lukovic", "affiliation": "MIT"},
    {"name": "Johannes Kopf", "affiliation": "Facebook, Oculus"},
    {"name": "Kyros Kutulakos", "affiliation": "University of Toronto"},
    {"name": "Jehee Lee", "affiliation": "Seoul National University, Movement Research Lab."},
    {"name": "Sung-Hee Lee", "affiliation": "Korea Advanced Institute of Science and Technology (KAIST)"},
    {"name": "David Levin", "affiliation": "University of Toronto, NVIDIA"},
    {"name": "Tzu-Mao Li", "affiliation": "University of California, San Diego"},
    {"name": "Ming Lin", "affiliation": "University of Maryland, University of North Carolina"},
    {"name": "Lingjie Liu", "affiliation": "Max-Planck-Institut für Informatik"},
    {"name": "Rafal K. Mantiuk", "affiliation": "University of Cambridge; Meta Platforms, Inc."},
    {"name": "Rachel McDonnell", "affiliation": "Trinity College Dublin"},
    {"name": "Pooran Memari", "affiliation": "CNRS, Ecole Polytechnique"},
    {"name": "Dominik Michels", "affiliation": "KAUST"},
    {"name": "Rahul Narain", "affiliation": "Indian Institute of Technology Delhi"},
    {"name": "Maks Ovsjanikov", "affiliation": "École Polytechnique"},
    {"name": "Nancy Pollard", "affiliation": "Carnegie Mellon University"},
    {"name": "Gerard Pons-Moll", "affiliation": "University of Tübingen"},
    {"name": "Jonathan Ragan-Kelley", "affiliation": "MIT CSAIL, UC Berkeley"},
    {"name": "Daniel Ritchie", "affiliation": "Brown University"},
    {"name": "Tobias Ritschel", "affiliation": "University College London (UCL)"},
    {"name": "Adriana Schulz", "affiliation": "University of Washington"},
    {"name": "Ana Serrano", "affiliation": "Universidad de Zaragoza - I3A"},
    {"name": "Tianjia Shao", "affiliation": "State Key Lab of CAD and CG, Zhejiang University"},
    {"name": "Alla Sheff er", "affiliation": "University of British Columbia, Amazon"},
    {"name": "Hao Su", "affiliation": "UCSD"},
    {"name": "Andrea Tagliasacchi", "affiliation": "Google Canada, University of Toronto"},
    {"name": "Siyu Tang", "affiliation": "ETH Zürich"},
    {"name": "Nils Th uerey", "affiliation": "Technical University of Munich"},
    {"name": "Xin Tong", "affiliation": "Microsoft"},
    {"name": "Wenping Wang", "affiliation": "Texas A&M University, University of Hong Kong"},
    {"name": "Huamin Wang", "affiliation": "Style3D Research, Th e Ohio State University"},
    {"name": "Alexander Wilkie", "affiliation": "Charles University, Prague"},
    {"name": "Feng Xu", "affiliation": "Tsinghua University"},
    {"name": "Ling-Qi Yan", "affiliation": "UC Santa Barbara"},
    {"name": "Yuting Ye", "affiliation": "Reality Labs Research, Meta"},
    {"name": "Sai-Kit Yeung", "affiliation": "Hong Kong University of Science and Technology"},
    {"name": "Lap-Fai Yu", "affiliation": "George Mason University"},
    {"name": "Hao (Richard) Zhang", "affiliation": "Simon Fraser University, Amazon"},
    {"name": "Shuang Zhao", "affiliation": "University of California Irvine"},
    {"name": "Bo Zhu", "affiliation": "Dartmouth College"},
    {"name": "Hugues Hoppe", "affiliation": "Unknown"},
    {"name": "Carol O’Sullivan", "affiliation": "Unknown"},
    {"name": "Holly Rushmeier", "affiliation": "Unknown"},
    {"name": "Chris Wojtan", "affiliation": "Unknown"},
    {"name": "Steve Marschner", "affiliation": "Unknown"},
    {"name": "Sylvain Paris", "affiliation": "Unknown"},
    {"name": "Alla Sheff er", "affiliation": "Unknown"},
    {"name": "Jaakko Lehtinen", "affiliation": "Unknown"},
    {"name": "Michael Wimmer", "affiliation": "Unknown"},
    {"name": "Wolfgang Heidrich", "affiliation": "Unknown"},
    {"name": "Aaron Hertzmann", "affiliation": "Unknown"}
]

new_2019 = [
    {"name": "Tomasz Bednarz", "affiliation": "CSIRO Data61, UNSW Art & Design, Australia"},
    {"name": "Sarah Kenderdine", "affiliation": "ArtLab Laboratory for Experimental Museology (Em+), Switzerland"},
    {"name": "June Kim", "affiliation": "The University of New South Wales, Australia"},
    {"name": "Michael Hsin-Yao Liang", "affiliation": "Silkroad Visual Technologies Co., LTD, Taiwan"},
    {"name": "Pol Jeremias-Vila", "affiliation": "Pixar Animation Studios, USA"},
    {"name": "Jinny H.J. Choo", "affiliation": "Korea National University of Arts, South Korea"},
    {"name": "Sai-Kit Yeung", "affiliation": "The Hong Kong University of Science and Technology, Hong Kong"},
    {"name": "John Doolan", "affiliation": "Virtual Immersive, Australia"},
    {"name": "Joe Cincotta", "affiliation": "Thinking.Studio, Australia"},
    {"name": "Alyn Rockwood", "affiliation": "Boulder Graphics, USA"},
    {"name": "Brian Wyvill", "affiliation": "University of Victoria, Canada"},
    {"name": "Matt Adcock", "affiliation": "CSIRO Data61, Australia"},
    {"name": "Yuta Sugiura", "affiliation": "Keio University, Japan"},
    {"name": "Mark Elendt", "affiliation": "SideFX, Canada"},
    {"name": "Stephen N. Spencer", "affiliation": "University of Washington, USA"},
    {"name": "Mike Seymour", "affiliation": "Sydney University, Australia"},
    {"name": "Xin Tong", "affiliation": "Microsoft Research, China"},
    {"name": "Belen Masia", "affiliation": "Universidad de Zaragoza, Spain"},
    {"name": "C. Karen Liu", "affiliation": "Stanford University, USA"},
    {"name": "Mark Billinghurst", "affiliation": "University of Auckland, New Zealand, University of South Australia, Australia"},
    {"name": "Arindam Dey", "affiliation": "University of Queensland, Australia"},
    {"name": "Bruce H. Thomas", "affiliation": "University of South Australia, Australia"},
    {"name": "Norbert Drage", "affiliation": "Curtin University, Australia"},
    {"name": "Daniel Filonik", "affiliation": "EPICentre, UNSW Art & Design, Australia"},
    {"name": "Ian Failes", "affiliation": "Vfxblog, Australia"},
    {"name": "Craig James", "affiliation": "CSIRO, Australia"},
    {"name": "John McGhee", "affiliation": "University of New South Wales, Art & Design, Australia"},
    {"name": "Luc Betbeder-Matibet", "affiliation": "University of New South Wales, Sydney, Australia"},
    {"name": "Rick Xu", "affiliation": "Shenzhen ACM SIGGRAPH Chapter, China"},
    {"name": "Ayumi Kimura", "affiliation": "Research Manager at OLM Digital, Inc., Japan / Program Manager and Collaboration Coordinator at CMIC, Victoria University of Wellington, New Zealand"},
    {"name": "Diana Arellano", "affiliation": "Mackevision, Germany"},
    {"name": "Jessica Hodgins", "affiliation": "Carnegie Mellon University, USA"},
    {"name": "Surapong Lertsithichai", "affiliation": "Mahidol University, Thailand"},
    {"name": "Mashhuda Glencross", "affiliation": "The University of Queensland, Australia"},
    {"name": "David Spoelstra", "affiliation": "MediaMachine LLC, USA"},
    {"name": "Prakash Ramajillu", "affiliation": "Koelnmesse Pte Ltd, Singapore"},
    {"name": "Ken Anjyo", "affiliation": "Executive Advisor at OLM Digital, Inc. / Director at CMIC, Victoria University of Wellington"},
    {"name": "Jinny H.J. Choo", "affiliation": "Korea National University of Arts, South Korea"},
    {"name": "Shuzo John Shiota", "affiliation": "Polygon Pictures Inc., Japan"}
]



from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def disambiguate_authors(chairs_list, previous_list):
    disambiguated_list = []
    used_names = set()

    for chair in chairs_list:
        best_match = None
        max_similarity = 0

        for prev_chair in previous_list:
            similarity = similar(chair['name'], prev_chair['name'])
            # print(chair['name'])
            if similarity > max_similarity and chair['affiliation'] == prev_chair['affiliation']:
                max_similarity = similarity
                best_match = prev_chair

        if best_match is not None and best_match['name'] not in used_names:
            disambiguated_list.append(best_match)
            used_names.add(best_match['name'])
        else:
            disambiguated_list.append(chair)

    return disambiguated_list

# Combine all the committee chairs lists
all_chairs = new_2022+new_2023+new_2019
# Disambiguate and remove duplicates
unique_chairs = disambiguate_authors(all_chairs, all_chairs)

print(unique_chairs)

import csv

# Specify the filename for the CSV file
csv_filename = 'Graphics_PC_new.csv'

# Define the field names for the CSV header
field_names = ['name', 'affiliation']

# Write the data to the CSV file
with open(csv_filename, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=field_names)

    # Write the header
    writer.writeheader()

    # Write the committee_chairs data
    writer.writerows(unique_chairs)

print(f"The data has been written to {csv_filename}")




