OSDI_2023=[
    {"name": "Roxana Geambasu", "affiliation": "Columbia University"},
    {"name": "Ed Nightingale", "affiliation": "Apple"},
    {"name": "Atul Adya", "affiliation": "Databricks"},
    {"name": "Rachit Agarwal", "affiliation": "Cornell University"},
    {"name": "Nitin Agrawal", "affiliation": "Google"},
    {"name": "Ramnatthan Alagappan", "affiliation": "University of Illinois at Urbana–Champaign"},
    {"name": "Jeremy Andrus", "affiliation": "Apple"},
    {"name": "Sebastian Angel", "affiliation": "University of Pennsylvania"},
    {"name": "Mahesh Balakrishnan", "affiliation": "Confluent"},
    {"name": "Adam Belay", "affiliation": "MIT CSAIL"},
    {"name": "Emery Berger", "affiliation": "University of Massachusetts Amherst"},
    {"name": "Edouard Bugnion", "affiliation": "EPFL"},
    {"name": "George Candea", "affiliation": "EPFL"},
    {"name": "Kang Chen", "affiliation": "Tsinghua University"},
    {"name": "Vijay Chidambaram", "affiliation": "The University of Texas at Austin and VMware Research"},
    {"name": "Mosharaf Chowdhury", "affiliation": "University of Michigan"},
    {"name": "Byung-Gon Chun", "affiliation": "Seoul National University and FriendliAI"},
    {"name": "Asaf Cidon", "affiliation": "Columbia University"},
    {"name": "Manuel Costa", "affiliation": "Microsoft Research"},
    {"name": "Landon Cox", "affiliation": "Microsoft Research"},
    {"name": "Natacha Crooks", "affiliation": "University of California, Berkeley"},
    {"name": "Jon Crowcroft", "affiliation": "University of Cambridge"},
    {"name": "Heming Cui", "affiliation": "University of Hong Kong"},
    {"name": "Dilma Da Silva", "affiliation": "Texas A&M University"},
    {"name": "Murat Demirbas", "affiliation": "Amazon Web Services"},
    {"name": "Ittay Eyal", "affiliation": "Technion—Israel Institute of Technology"},
    {"name": "Jason Flinn", "affiliation": "Meta"},
    {"name": "Bryan Ford", "affiliation": "EPFL"},
    {"name": "Aishwarya Ganesan", "affiliation": "University of Illinois at Urbana-Champaign and VMware Research"},
    {"name": "Phillip Gibbons", "affiliation": "Carnegie Mellon University"},
    {"name": "Yossi Gilad", "affiliation": "Hebrew University of Jerusalem"},
    {"name": "Joseph Gonzalez", "affiliation": "University of California, Berkeley"},
    {"name": "Andreas Haeberlen", "affiliation": "University of Pennsylvania and Roblox"},
    {"name": "Steven Hand", "affiliation": "Google"},
    {"name": "Tim Harris", "affiliation": "Microsoft"},
    {"name": "Wenjun Hu", "affiliation": "Yale University"},
    {"name": "Ryan Huang", "affiliation": "Johns Hopkins University"},
    {"name": "Rüdiger Kapitza", "affiliation": "Friedrich-Alexander-Universität Erlangen-Nürnberg"},
    {"name": "Brad Karp", "affiliation": "University College London"},
    {"name": "Baris Kasikci", "affiliation": "University of Michigan"},
    {"name": "Eddie Kohler", "affiliation": "Harvard University"},
    {"name": "Mathias Lécuyer", "affiliation": "University of British Columbia"},
    {"name": "Philip Levis", "affiliation": "Google and Stanford University"},
    {"name": "Amit Levy", "affiliation": "Princeton University"},
    {"name": "Jinyang Li", "affiliation": "New York University"},
    {"name": "Hyeontaek Lim", "affiliation": "Google"},
    {"name": "Wyatt Lloyd", "affiliation": "Princeton University"},
    {"name": "Jay Lorch", "affiliation": "Microsoft Research"},
    {"name": "Shan Lu", "affiliation": "University of Chicago"},
    {"name": "Martin Maas", "affiliation": "Google"},
    {"name": "Jonathan Mace", "affiliation": "Max Planck Institute for Software Systems (MPI-SWS)"},
    {"name": "Ratul Mahajan", "affiliation": "University of Washington and Intentionet"},
    {"name": "Z. Morley Mao", "affiliation": "University of Michigan and Google"},
    {"name": "James Mickens", "affiliation": "Harvard University"},
    {"name": "Thomas Moscibroda", "affiliation": "Microsoft"},
    {"name": "Deepak Narayanan", "affiliation": "Microsoft Research"},
    {"name": "Ravi Netravali", "affiliation": "Princeton University"},
    {"name": "Jason Nieh", "affiliation": "Columbia University"},
    {"name": "Cristina Nita-Rotaru", "affiliation": "Northeastern University"},
    {"name": "Shadi Noghabi", "affiliation": "Microsoft Research"},
    {"name": "Aurojit Panda", "affiliation": "New York University"},
    {"name": "KyoungSoo Park", "affiliation": "Korea Advanced Institute of Science and Technology (KAIST)"},
    {"name": "Bryan Parno", "affiliation": "Carnegie Mellon University"},
    {"name": "Daniel Peek", "affiliation": "Meta"},
    {"name": "Peter Pietzuch", "affiliation": "Imperial College London"},
    {"name": "Dan Ports", "affiliation": "Microsoft Research"},
    {"name": "Costin Raiciu", "affiliation": "University Politehnica of Bucharest"},
    {"name": "David Richardson", "affiliation": "Apple"},
    {"name": "Luis Rodrigues", "affiliation": "INESC-ID and Instituto Superior Técnico, University of Lisbon"},
    {"name": "Christopher Rossbach", "affiliation": "The University of Texas at Austin and Katana Graph"},
    {"name": "Malte Schwarzkopf", "affiliation": "Brown University"},
    {"name": "Marco Serafini", "affiliation": "University of Massachusetts Amherst"},
    {"name": "Marc Shapiro", "affiliation": "Sorbonne-Université–LIP6 and Inria"},
    {"name": "Ji-Yong Shin", "affiliation": "Northeastern University"}
]

OSDI_2022 = [
    {"name": "Marcos K. Aguilera", "affiliation": "VMware Research"},
    {"name": "Hakim Weatherspoon", "affiliation": "Cornell University and Exotanium, Inc."},
    {"name": "Atul Adya", "affiliation": "Databricks"},
    {"name": "Nitin Agrawal", "affiliation": "ThoughtSpot"},
    {"name": "Deniz Altinbüken", "affiliation": "Google"},
    {"name": "Behnaz Arzani", "affiliation": "Microsoft Research"},
    {"name": "Mahesh Balakrishnan", "affiliation": "Facebook"},
    {"name": "Oana Balmau", "affiliation": "McGill University"},
    {"name": "Andrew Baumann", "affiliation": "Microsoft Research"},
    {"name": "Adam Belay", "affiliation": "MIT CSAIL"},
    {"name": "Ranjita Bhagwan", "affiliation": "Microsoft Research"},
    {"name": "Annette Bieniusa", "affiliation": "Technische Universität Kaiserslautern"},
    {"name": "Ken Birman", "affiliation": "Cornell University"},
    {"name": "Rodrigo Bruno", "affiliation": "INESC-ID and Instituto Superior Técnico, University of Lisbon"},
    {"name": "Irina Calciu", "affiliation": "Graft"},
    {"name": "George Candea", "affiliation": "EPFL"},
    {"name": "Marco Canini", "affiliation": "KAUST"},
    {"name": "Miguel Castro", "affiliation": "Microsoft"},
    {"name": "Rong Chen", "affiliation": "Shanghai Jiao Tong University"},
    {"name": "Byung-Gon Chun", "affiliation": "Seoul National University and FriendliAI"},
    {"name": "Asaf Cidon", "affiliation": "Columbia University"},
    {"name": "Landon Cox", "affiliation": "Microsoft Research"},
    {"name": "Natacha Crooks", "affiliation": "University of California, Berkeley"},
    {"name": "Murat Demirbas", "affiliation": "Amazon Web Services"},
    {"name": "Yufei Ding", "affiliation": "University of California, Santa Barbara"},
    {"name": "Roxana Geambasu", "affiliation": "Columbia University"},
    {"name": "Ashvin Goel", "affiliation": "University of Toronto"},
    {"name": "Haryadi S. Gunawi", "affiliation": "University of Chicago"},
    {"name": "Indranil Gupta", "affiliation": "University of Illinois at Urbana–Champaign"},
    {"name": "Andreas Haeberlen", "affiliation": "University of Pennsylvania"},
    {"name": "Wenjun Hu", "affiliation": "Yale University"},
    {"name": "Rüdiger Kapitza", "affiliation": "Technische Universität Braunschweig"},
    {"name": "Manos Kapritsos", "affiliation": "University of Michigan"},
    {"name": "Baris Kasikci", "affiliation": "University of Michigan"},
    {"name": "Ana Klimovic", "affiliation": "ETH Zurich"},
    {"name": "Eddie Kohler", "affiliation": "Harvard University"},
    {"name": "Kevin Kornegay", "affiliation": "Morgan State University"},
    {"name": "Dejan Kostić", "affiliation": "KTH Royal Institute of Technology"},
    {"name": "Philip Levis", "affiliation": "Stanford University"},
    {"name": "Jialin Li", "affiliation": "National University of Singapore"},
    {"name": "Jonathan Mace", "affiliation": "Max Planck Institute for Software Systems (MPI-SWS)"},
    {"name": "Ratul Mahajan", "affiliation": "University of Washington and Intentionet"},
    {"name": "Petros Maniatis", "affiliation": "Google Research"},
    {"name": "Z. Morley Mao", "affiliation": "University of Michigan"},
    {"name": "Kathryn S McKinley", "affiliation": "Google"},
    {"name": "Neha Narula", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Ravi Netravali", "affiliation": "Princeton University"},
    {"name": "Jason Nieh", "affiliation": "Columbia University"},
    {"name": "Cristina Nita-Rotaru", "affiliation": "Northeastern University"},
    {"name": "Shadi Noghabi", "affiliation": "Microsoft Research"},
    {"name": "Sam H. Noh", "affiliation": "UNIST (Ulsan National Institute of Science and Technology)"},
    {"name": "Aurojit Panda", "affiliation": "NYU"},
    {"name": "Amar Phanishayee", "affiliation": "Microsoft Research"},
    {"name": "Peter Pietzuch", "affiliation": "Imperial College London"},
    {"name": "Luis Rodrigues", "affiliation": "INESC-ID and Instituto Superior Técnico, University of Lisbon"},
    {"name": "Christopher Rossbach", "affiliation": "The University of Texas at Austin and Katana Graph"},
    {"name": "Malte Schwarzkopf", "affiliation": "Brown University"},
    {"name": "Marco Serafini", "affiliation": "University of Massachusetts Amherst"},
    {"name": "Marc Shapiro", "affiliation": "Inria and UPMC-LIP6"},
    {"name": "Ji-Yong Shin", "affiliation": "Northeastern University"},
    {"name": "Liuba Shrira", "affiliation": "Brandeis University"},
    {"name": "Vishal Shrivastav", "affiliation": "Purdue University"},
    {"name": "Alex C. Snoeren", "affiliation": "University of California, San Diego"},
    {"name": "Robert Soulé", "affiliation": "Yale University"},
    {"name": "Phillip Stanley-Marbell", "affiliation": "University of Cambridge"},
    {"name": "Swami Sundararaman", "affiliation": "Pyxeda AI"},
    {"name": "Adriana Szekeres", "affiliation": "VMware Research"},
    {"name": "Amy Tai", "affiliation": "VMware Research"},
    {"name": "Doug Terry", "affiliation": "Amazon Web Services"},
    {"name": "Dan Tsafrir", "affiliation": "Technion—Israel Institute of Technology and VMware Research"},
    {"name": "Ymir Vigfusson", "affiliation": "Emory University"},
    {"name": "Rashmi Vinayak", "affiliation": "Carnegie Mellon University"},
    {"name": "Hakim Weatherspoon", "affiliation": "Cornell University and Exotanium, Inc."},
    {"name": "Bernard Wong", "affiliation": "University of Waterloo"},
    {"name": "Tim Wood", "affiliation": "George Washington University"},
    {"name": "Gala Yadgar", "affiliation": "Technion—Israel Institute of Technology"},
    {"name": "Ding Yuan", "affiliation": "University of Toronto"},
    {"name": "Gerd Zellweger", "affiliation": "VMware Research"},
    {"name": "Yiying Zhang", "affiliation": "University of California, San Diego"},
{"name": "Andrea Arpaci-Dusseau", "affiliation": "University of Wisconsin—Madison"},
    {"name": "Angela Demke Brown", "affiliation": "University of Toronto"},
    {"name": "Jason Flinn", "affiliation": "Facebook"},
    {"name": "Casey Henderson", "affiliation": "USENIX Association"},
    {"name": "Jon Howell", "affiliation": "VMware Research"},
    {"name": "Kimberly Keeton", "affiliation": ""},
    {"name": "Hank Levy", "affiliation": "University of Washington"},
    {"name": "Jay Lorch", "affiliation": "Microsoft Research"},
    {"name": "Shan Lu", "affiliation": "University of Chicago"},
    {"name": "James Mickens", "affiliation": "Harvard University"},
    {"name": "Timothy Roscoe", "affiliation": "ETH Zurich"},
    {"name": "Margo Seltzer", "affiliation": "University of British Columbia"},
    {"name": "Geoff Voelker", "affiliation": "University of California, San Diego"},
{"name": "Natacha Crooks", "affiliation": "University of California, Berkeley"},
    {"name": "Adriana Szekeres", "affiliation": "VMware Research"}

]

OSDI_2021 = [
    {"name": "Angela Demke Brown", "affiliation": "University of Toronto"},
    {"name": "Jay Lorch", "affiliation": "Microsoft Research"},
    {"name": "Atul Adya", "affiliation": "Google"},
    {"name": "Deniz Altinbüken", "affiliation": "Google"},
    {"name": "Nadav Amit", "affiliation": "VMware Research"},
    {"name": "Thomas Anderson", "affiliation": "University of Washington"},
    {"name": "Sebastian Angel", "affiliation": "University of Pennsylvania"},
    {"name": "Behnaz Arzani", "affiliation": "Microsoft Research"},
    {"name": "Mahesh Balakrishnan", "affiliation": "Facebook"},
    {"name": "Sujata Banerjee", "affiliation": "VMware Research"},
    {"name": "Sorav Bansal", "affiliation": "Indian Institute of Technology Delhi"},
    {"name": "Andrew Baumann", "affiliation": "Microsoft Research"},
    {"name": "Adam Belay", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Theophilus A. Benson", "affiliation": "Brown University"},
    {"name": "Pramod Bhatotia", "affiliation": "Technische Universität Munich"},
    {"name": "James Bornholt", "affiliation": "The University of Texas at Austin"},
    {"name": "Edouard Bugnion", "affiliation": "EPFL"},
    {"name": "George Candea", "affiliation": "EPFL"},
    {"name": "Kang Chen", "affiliation": "Tsinghua University"},
    {"name": "Rong Chen", "affiliation": "Shanghai Jiao Tong University"},
    {"name": "Mosharaf Chowdhury", "affiliation": "University of Michigan"},
    {"name": "Moshe Gabel", "affiliation": "University of Toronto"},
    {"name": "Ada Gavrilovska", "affiliation": "Georgia Institute of Technology"},
    {"name": "Manya Ghobadi", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Garth A. Gibson", "affiliation": "Vector Institute, Carnegie Mellon University, and University of Toronto"},
    {"name": "Ashvin Goel", "affiliation": "University of Toronto"},
    {"name": "Joseph Gonzalez", "affiliation": "University of California, Berkeley"},
    {"name": "Ronghui Gu", "affiliation": "Columbia University"},
    {"name": "Haryadi Gunawi", "affiliation": "University of Chicago"},
    {"name": "Chuanxiong Guo", "affiliation": "ByteDance"},
    {"name": "Chris Hawblitzel", "affiliation": "Microsoft Research"},
    {"name": "Jon Howell", "affiliation": "VMware Research"},
    {"name": "Yu Hua", "affiliation": "Huazhong University of Science and Technology"},
    {"name": "Ryan Huang", "affiliation": "Johns Hopkins University"},
    {"name": "Michael Isard", "affiliation": "Google Research"},
    {"name": "Joe Izraelevitz", "affiliation": "University of Colorado, Boulder"},
    {"name": "Manos Kapritsos", "affiliation": "University of Michigan"},
    {"name": "Baris Kasikci", "affiliation": "University of Michigan"},
    {"name": "Sam King", "affiliation": "University of California, Davis"},
    {"name": "Orran Krieger", "affiliation": "Boston University"},
    {"name": "Arvind Krishnamurthy", "affiliation": "University of Washington"},
    {"name": "Amit Levy", "affiliation": "Princeton University"},
    {"name": "Jialin Li", "affiliation": "National University of Singapore"},
    {"name": "Wyatt Lloyd", "affiliation": "Princeton University"},
    {"name": "Shan Lu", "affiliation": "University of Chicago"},
    {"name": "Harsha V. Madhyastha", "affiliation": "University of Michigan"},
    {"name": "Petros Maniatis", "affiliation": "Google"},
    {"name": "Z. Morley Mao", "affiliation": "University of Michigan"},
    {"name": "Changwoo Min", "affiliation": "Virginia Tech"},
    {"name": "Radhika Mittal", "affiliation": "University of Illinois at Urbana–Champaign"},
    {"name": "Dushyanth Narayanan", "affiliation": "Microsoft Research"},
    {"name": "Ravi Netravali", "affiliation": "University of California, Los Angeles"},
    {"name": "Kay Ousterhout", "affiliation": "Lightstep"},
    {"name": "Aurojit Panda", "affiliation": "New York University"},
    {"name": "Gennady Pekhimenko", "affiliation": "University of Toronto and Vector Institute"},
    {"name": "Amar Phanishayee", "affiliation": "Microsoft Research"},
    {"name": "Peter Pietzuch", "affiliation": "Imperial College London"},
    {"name": "Don Porter", "affiliation": "The University of North Carolina at Chapel Hill"},
    {"name": "Oriana Riva", "affiliation": "Microsoft Research"},
    {"name": "Malte Schwarzkopf", "affiliation": "Brown University"},
    {"name": "Vyas Sekar", "affiliation": "Carnegie Mellon University"},
    {"name": "Michael Stumm", "affiliation": "University of Toronto"},
    {"name": "Lalith Suresh", "affiliation": "VMware Research"},
    {"name": "Doug Terry", "affiliation": "Amazon"},
    {"name": "Alexey Tumanov", "affiliation": "Georgia Institute of Technology"},
    {"name": "Amin Vahdat", "affiliation": "Google"},
    {"name": "Shivaram Venkataraman", "affiliation": "University of Wisconsin—Madison"},
    {"name": "Rashmi Vinayak", "affiliation": "Carnegie Mellon University"},
    {"name": "Marko Vukolić", "affiliation": "IBM Research - Zurich"},
    {"name": "Andrew Warfield", "affiliation": "Amazon"},
    {"name": "Gala Yadgar", "affiliation": "Technion—Israel Institute of Technology"},
    {"name": "Junfeng Yang", "affiliation": "Columbia University"},
    {"name": "Ding Yuan", "affiliation": "University of Toronto"},
    {"name": "Irene Zhang", "affiliation": "Microsoft Research"},
    {"name": "Yiying Zhang", "affiliation": "University of California, San Diego"},
    {"name": "Wenting Zheng", "affiliation": "University of California, Berkeley, and Carnegie Mellon University"},
    {"name": "Yuanyuan Zhou", "affiliation": "University of California, San Diego"},
    {"name": "Sangeetha Abdu Jyothi", "affiliation": "University of California, Irvine, and VMware Research"},
    {"name": "Deniz Altinbüken", "affiliation": "Google"},
    {"name": "Dilma Da Silva", "affiliation": "Texas A&M University"},
    {"name": "Aurojit Panda", "affiliation": "New York University"},
    {"name": "Baris Kasikci", "affiliation": "University of Michigan"},
    {"name": "Amy Ousterhout", "affiliation": "University of California, Berkeley"},
    {"name": "Malte Schwarzkopf", "affiliation": "Brown University"},
    {"name": "Reto Achermann", "affiliation": "University of British Columbia"},
    {"name": "Zsolt István", "affiliation": "IT University of Copenhagen"},
    {"name": "Adriana Szekeres", "affiliation": "VMware Research"},
    {"name": "Vasily Tarasov", "affiliation": "IBM Research - Almaden"},
    {"name": "Andrea Arpaci-Dusseau", "affiliation": "University of Wisconsin—Madison"},
    {"name": "Jason Flinn", "affiliation": "Facebook"},
    {"name": "Casey Henderson", "affiliation": "USENIX Association"},
    {"name": "Jon Howell", "affiliation": "VMware Research"},
    {"name": "Kimberly Keeton", "affiliation": ""},
    {"name": "Hank Levy", "affiliation": "University of Washington"},
    {"name": "Shan Lu", "affiliation": "University of Chicago"},
    {"name": "James Mickens", "affiliation": "Harvard University"},
    {"name": "Brian Noble", "affiliation": "University of Michigan"},
    {"name": "Timothy Roscoe", "affiliation": "ETH Zurich"},
    {"name": "Margo Seltzer", "affiliation": "University of British Columbia"},
    {"name": "Geoff Voelker", "affiliation": "University of California, San Diego"}
]

OSDI_2020 = [
    {"name": "Jon Howell", "affiliation": "VMware Research"},
    {"name": "Shan Lu", "affiliation": "University of Chicago"},
    {"name": "Rachit Agarwal", "affiliation": "Cornell University"},
    {"name": "Lorenzo Alvisi", "affiliation": "Cornell University"},
    {"name": "Tom Anderson", "affiliation": "University of Washington"},
    {"name": "Sebastian Angel", "affiliation": "University of Pennsylvania"},
    {"name": "Andrea Arpaci-Dusseau", "affiliation": "University of Wisconsin—Madison"},
    {"name": "Andrew Baumann", "affiliation": "Microsoft Research"},
    {"name": "Irina Calciu", "affiliation": "VMware Research"},
    {"name": "George Candea", "affiliation": "EPFL"},
    {"name": "Rong Chen", "affiliation": "Shanghai Jiao Tong University"},
    {"name": "Wenguang Chen", "affiliation": "Tsinghua University"},
    {"name": "Vijay Chidambaram", "affiliation": "The University of Texas at Austin and VMware Research"},
    {"name": "Byung-Gon Chun", "affiliation": "Seoul National University"},
    {"name": "Allen Clement", "affiliation": ""},
    {"name": "Natacha Crooks", "affiliation": "University of California, Berkeley"},
    {"name": "Dilma Da Silva", "affiliation": "Texas A&M University"},
    {"name": "Alexandra Fedorova", "affiliation": "University of British Columbia"},
    {"name": "Jason Flinn", "affiliation": "Facebook"},
    {"name": "Roxana Geambasu", "affiliation": "Columbia University"},
    {"name": "Yossi Gilad", "affiliation": "The Hebrew University of Jerusalem"},
    {"name": "Haryadi Gunawi", "affiliation": "University of Chicago"},
    {"name": "Andreas Haeberlen", "affiliation": "University of Pennsylvania"},
    {"name": "Tim Harris", "affiliation": "Amazon"},
    {"name": "Chris Hawblitzel", "affiliation": "Microsoft Research"},
    {"name": "Gernot Heiser", "affiliation": "University of New South Wales and CSIRO’s Data61"},
    {"name": "Y. Charlie Hu", "affiliation": "Purdue University"},
    {"name": "Ryan Huang", "affiliation": "Johns Hopkins University"},
    {"name": "Rebecca Isaacs", "affiliation": "Twitter"},
    {"name": "Frans Kaashoek", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Manos Kapritsos", "affiliation": "University of Michigan"},
    {"name": "Baris Kasikci", "affiliation": "University of Michigan"},
    {"name": "Kimberly Keeton", "affiliation": ""},
    {"name": "Anne-Marie Kermarrec", "affiliation": "EPFL"},
    {"name": "Ana Klimovic", "affiliation": "Google Research and ETH Zurich"},
    {"name": "Jinyang Li", "affiliation": "New York University"},
    {"name": "Wyatt Lloyd", "affiliation": "Princeton University"},
    {"name": "Jay Lorch", "affiliation": "Microsoft Research"},
    {"name": "Xiaosong Ma", "affiliation": "Quatar Computing Research Institute"},
    {"name": "Kathryn S. McKinley", "affiliation": "Google"},
    {"name": "James Mickens", "affiliation": "Harvard University"},
    {"name": "Robert Morris", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Derek Murray", "affiliation": "Google"},
    {"name": "Madan Musuvathi", "affiliation": "Microsoft Research"},
    {"name": "Bryan Parno", "affiliation": "Carnegie Mellon University"},
    {"name": "Simon Peter", "affiliation": "The University of Texas at Austin"},
    {"name": "Don Porter", "affiliation": "The University of North Carolina at Chapel Hill"},
    {"name": "Dan Ports", "affiliation": "Microsoft Research"},
    {"name": "Costin Raiciu", "affiliation": "University Politehnica of Bucharest"},
    {"name": "Malte Schwarzkopf", "affiliation": "Brown University"},
    {"name": "Ryan Stutsman", "affiliation": "University of Utah"},
    {"name": "Michael Swift", "affiliation": "University of Wisconsin—Madison"},
    {"name": "Kaushik Veeraraghavan", "affiliation": "Facebook"},
    {"name": "Rashmi Vinayak", "affiliation": "Carnegie Mellon University"},
    {"name": "Xi Wang", "affiliation": "University of Washington"},
    {"name": "Yang Wang", "affiliation": "The Ohio State University"},
    {"name": "John Wilkes", "affiliation": "Google"},
    {"name": "Emmett Witchel", "affiliation": "The University of Texas at Austin"},
    {"name": "Harry Xu", "affiliation": "University of California, Los Angeles"},
    {"name": "Tianyin Xu", "affiliation": "University of Illinois at Urbana–Champaign"},
    {"name": "Junfeng Yang", "affiliation": "Columbia University"},
    {"name": "Ding Yuan", "affiliation": "University of Toronto"},
    {"name": "Nickolai Zeldovich", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Irene Zhang", "affiliation": "Microsoft Research"},
    {"name": "Yiying Zhang", "affiliation": "University of California, San Diego"},
    {"name": "Lidong Zhou", "affiliation": "Microsoft Research"},
    {"name": "Yuanyuan Zhou", "affiliation": "University of California, San Diego"},
    {"name": "Andrea Arpaci-Dusseau", "affiliation": "University of Wisconsin—Madison"},
    {"name": "Jason Flinn", "affiliation": "Facebook"},
    {"name": "Casey Henderson", "affiliation": "USENIX Association"},
    {"name": "Kimberly Keeton", "affiliation": ""},
    {"name": "Hank Levy", "affiliation": "University of Washington"},
    {"name": "Shan Lu", "affiliation": "University of Chicago"},
    {"name": "James Mickens", "affiliation": "Harvard University"},
    {"name": "Brian Noble", "affiliation": "University of Michigan"},
    {"name": "Timothy Roscoe", "affiliation": "ETH Zurich"},
    {"name": "Margo Seltzer", "affiliation": "University of British Columbia"},
    {"name": "Geoff Voelker", "affiliation": "University of California, San Diego"}
]

OSDI_2019 = [
    {"name": "Andrea Arpaci-Dusseau", "affiliation": "University of Wisconsin—Madison"},
    {"name": "Geoff Voelker", "affiliation": "University of California, San Diego"},
    {"name": "Rachit Agarwal", "affiliation": "Cornell University"},
    {"name": "Marcos K. Aguilera", "affiliation": "VMware Research"},
    {"name": "Mahesh Balakrishnan", "affiliation": "Yale University/Facebook"},
    {"name": "Ranjita Bhagwan", "affiliation": "Microsoft Research India"},
    {"name": "Edouard Bugnion", "affiliation": "École Polytechnique Fédérale de Lausanne (EPFL)"},
    {"name": "Miguel Castro", "affiliation": "Microsoft Research Cambridge"},
    {"name": "Kang Chen", "affiliation": "Tsinghua University"},
    {"name": "Vijay Chidambaram", "affiliation": "The University of Texas at Austin"},
    {"name": "Landon Cox", "affiliation": "Duke University"},
    {"name": "Angela Demke Brown", "affiliation": "University of Toronto"},
    {"name": "Sandhya Dwarkadas", "affiliation": "University of Rochester"},
    {"name": "Sasha Fedorova", "affiliation": "University of British Columbia"},
    {"name": "Roxana Geambasu", "affiliation": "Columbia University"},
    {"name": "Cristiano Giuffrida", "affiliation": "Vrije Universiteit Amsterdam"},
    {"name": "Haryadi Gunawi", "affiliation": "University of Chicago"},
    {"name": "Andreas Haeberlen", "affiliation": "University of Pennsylvania"},
    {"name": "Jon Howell", "affiliation": "VMware Research"},
    {"name": "Rebecca Isaacs", "affiliation": "Twitter"},
    {"name": "Michael Isard", "affiliation": "Google"},
    {"name": "Frans Kaashoek", "affiliation": "Massachusetts Institute of Technology"},
    {"name": "Manos Kapritsos", "affiliation": "University of Michigan"},
    {"name": "Taesoo Kim", "affiliation": "Georgia Institute of Technology"},
    {"name": "Sam King", "affiliation": "University of California, Davis"},
    {"name": "Christoforos Kozyrakis", "affiliation": "Stanford University"},
    {"name": "Jinyang Li", "affiliation": "New York University"},
    {"name": "Wyatt Lloyd", "affiliation": "Princeton University"},
    {"name": "Jay Lorch", "affiliation": "Microsoft Research"},
    {"name": "Richard Mortier", "affiliation": "University of Cambridge"},
    {"name": "Gilles Muller", "affiliation": "Inria"},
    {"name": "KyoungSoo Park", "affiliation": "Korea Advanced Institute of Science and Technology (KAIST)"},
    {"name": "Raluca Popa", "affiliation": "University of California, Berkeley"},
    {"name": "Don Porter", "affiliation": "The University of North Carolina at Chapel Hill"},
    {"name": "Justine Sherry", "affiliation": "Carnegie Mellon University"},
    {"name": "Liuba Shrira", "affiliation": "Brandeis University"},
    {"name": "Ryan Stutsman", "affiliation": "University of Utah"},
    {"name": "Steve Swanson", "affiliation": "University of California, San Diego"},
    {"name": "Michael Swift", "affiliation": "University of Wisconsin—Madison"},
    {"name": "Dan Tsafrir", "affiliation": "VMware Research and Technion—Israel Institute of Technology"},
    {"name": "Rashmi Vinayak", "affiliation": "Carnegie Mellon University"},
    {"name": "Xi Wang", "affiliation": "University of Washington"},
    {"name": "Andrew Warfield", "affiliation": "Amazon"},
    {"name": "Roger Wattenhofer", "affiliation": "ETH Zurich"},
    {"name": "Hakim Weatherspoon", "affiliation": "Cornell University"},
    {"name": "Ming Wu", "affiliation": "Microsoft Research"},
    {"name": "Yubin Xia", "affiliation": "Shanghai Jiao Tong University"},
    {"name": "Ding Yuan", "affiliation": "University of Toronto"},
    {"name": "Matei Zaharia", "affiliation": "Stanford University"},
    {"name": "Irene Zhang", "affiliation": "Microsoft Research"},
    {"name": "Yiying Zhang", "affiliation": "Purdue University"},
    {"name": "Vijay Chidambaram", "affiliation": "The University of Texas at Austin"},
    {"name": "Yiying Zhang", "affiliation": "Purdue University"},
    {"name": "Brad Chen", "affiliation": "Google"},
    {"name": "Jason Flinn", "affiliation": "University of Michigan"},
    {"name": "Casey Henderson", "affiliation": "USENIX Association"},
    {"name": "Kimberly Keeton", "affiliation": "Hewlett Packard Labs"},
    {"name": "Hank Levy", "affiliation": "University of Washington"},
    {"name": "James Mickens", "affiliation": "Harvard University"},
    {"name": "Brian Noble", "affiliation": "University of Michigan"},
    {"name": "Timothy Roscoe", "affiliation": "ETH Zurich"},
    {"name": "Margo Seltzer", "affiliation": "University of British Columbia"},
    {"name": "Amin Vahdat", "affiliation": "Google and University of California, San Diego"}
]

SOSP_2023 = [
    {"name": "Peter Druschel", "affiliation": "Max Planck Institute for Software Systems (MPI-SWS)"},
    {"name": "Antoine Kaufmann", "affiliation": "Max Planck Institute for Software Systems (MPI-SWS)"},
    {"name": "Jonathan Mace", "affiliation": "Max Planck Institute for Software Systems (MPI-SWS) and Microsoft Research"},
    {"name": "Jason Flinn", "affiliation": "Meta"},
    {"name": "Margo Seltzer", "affiliation": "University of British Columbia"},
    {"name": "Meng", "affiliation": "The University of Texas at Arlington"},
    {"name": "Nitin Agrawal", "affiliation": "Google"},
    {"name": "Marcos K. Aguilera", "affiliation": "VMware Research"},
    {"name": "Mohammad Alizadeh", "affiliation": "MIT"},
    {"name": "Mahesh Balakrishnan", "affiliation": "Confluent"},
    {"name": "Adam Belay", "affiliation": "MIT CSAIL"},
    {"name": "Edouard Bugnion", "affiliation": "EPFL"},
    {"name": "Haibo Chen", "affiliation": "Shanghai Jiao Tong University"},
    {"name": "Rong Chen", "affiliation": "Shanghai Jiao Tong University"},
    {"name": "Angela Demke Brown", "affiliation": "University of Toronto"},
    {"name": "Haryadi S. Gunawi", "affiliation": "University of Chicago"},
    {"name": "Gernot Heiser", "affiliation": "UNSW Sydney"},
    {"name": "Ryan Huang", "affiliation": "University of Michigan"},
    {"name": "Rebecca Isaacs", "affiliation": "Amazon Web Services"},
    {"name": "Manos Kapritsos", "affiliation": "University of Michigan"},
    {"name": "Baris Kasikci", "affiliation": "University of Michigan and Google"},
    {"name": "Kimberly Keeton", "affiliation": "Google"},
    {"name": "Christos Kozyrakis", "affiliation": "Stanford University"},
    {"name": "Dongyoon Lee", "affiliation": "Stony Brook University"},
    {"name": "Brian Levine", "affiliation": "University of Massachusetts Amherst"},
    {"name": "Shan Lu", "affiliation": "Microsoft Research and University of Chicago"},
    {"name": "Jonathan Mace", "affiliation": "Max Planck Institute for Software Systems (MPI-SWS) and Microsoft Research"},
    {"name": "Peter Macko", "affiliation": "MongoDB"},
    {"name": "Kostas Magoutis", "affiliation": "University of Crete and FORTH-ICS"},
    {"name": "Jeff Mogul", "affiliation": "Google"},
    {"name": "Kiran-Kumar Muniswamy-Reddy", "affiliation": "Amazon"},
    {"name": "Jason Nieh", "affiliation": "Columbia University"},
    {"name": "Sam H. Noh", "affiliation": "Virginia Tech"},
    {"name": "Aurojit Panda", "affiliation": "New York University"},
    {"name": "Thomas Pasquier", "affiliation": "University of British Columbia"},
    {"name": "Marta Pati˜no", "affiliation": "Universidad Polit´ecnica de Madrid, Spain"},
    {"name": "Simon Peter", "affiliation": "University of Washington"},
    {"name": "Peter Pietzuch", "affiliation": "Imperial College London"},
    {"name": "Raluca Ada Popa", "affiliation": "UC Berkeley"},
    {"name": "Andrew Quinn", "affiliation": "University of California, Santa Cruz"},
    {"name": "Timothy Roscoe", "affiliation": "ETH Zurich"},
    {"name": "Stefan Savage", "affiliation": "University of California, San Diego"},
    {"name": "Margo Seltzer", "affiliation": "University of British Columbia"},
    {"name": "Liuba Shrira", "affiliation": "Brandeis University"},
    {"name": "Dimitrios Skarlatos", "affiliation": "Carnegie Mellon University"},
    {"name": "Akshitha Sriraman", "affiliation": "Carnegie Mellon University and Google"},
    {"name": "Ryan Stutsman", "affiliation": "University of Utah"},
    {"name": "Doug Terry", "affiliation": "Amazon Web Services"},
    {"name": "Keval Vora", "affiliation": "Simon Fraser University"},
    {"name": "Hongyi Wang", "affiliation": "CMU"},
    {"name": "Lanjun Wang", "affiliation": "Tianjin University"},
    {"name": "Xi Wang", "affiliation": "University of Washington"},
    {"name": "Emmett Witchel", "affiliation": "UT Austin and Katana Graph"},
    {"name": "Gala Yadgar", "affiliation": "Technion - Israel Institute of Technology"},
    {"name": "Junfeng Yang", "affiliation": "Columbia University"},
    {"name": "Eiko Yoneki", "affiliation": "University of Cambridge"},
    {"name": "Haifeng Yu", "affiliation": "National University of Singapore"},
    {"name": "Ding Yuan", "affiliation": "University of Toronto and YScope"},
    {"name": "Ce Zhang", "affiliation": "ETH Zurich"},
    {"name": "Yiying Zhang", "affiliation": "University of California, San Diego"},
    {"name": "Lin Zhong", "affiliation": "Yale University"},
    {"name": "Lidong Zhou", "affiliation": "Microsoft Research"},
    {"name": "Yuanyuan Zhou", "affiliation": "University of California, San Diego"}
]

SOSP_2022 = [
    {"name": "Vijay Chidambaram", "affiliation": "The University of Texas at Austin and VMware Research"},
    {"name": "Anthony D. Joseph", "affiliation": "University of California, Berkeley"},
    {"name": "Jialin Li", "affiliation": "National University of Singapore (NUS)"},
    {"name": "Tianyin Xu", "affiliation": "University of Illinois at Urbana-Champaign"},
    {"name": "Robbert van Renesse", "affiliation": "Cornell University"},
    {"name": "Nickolai Zeldovich", "affiliation": "MIT"},
    {"name": "Sebastian Angel", "affiliation": "University of Pennsylvania"},
    {"name": "Oana Balmau", "affiliation": "McGill University"},
    {"name": "Adam Belay", "affiliation": "MIT"},
    {"name": "Frank Bellosa", "affiliation": "Karlsruhe Institute of Technology"},
    {"name": "Emery Berger", "affiliation": "UMass Amherst"},
    {"name": "Ranjita Bhagwan", "affiliation": "Microsoft Research India"},
    {"name": "Edouard Bugnion", "affiliation": "EPFL"},
    {"name": "Haibo Chen", "affiliation": "Shanghai Jiao Tong University"},
    {"name": "Kang Chen", "affiliation": "Tsinghua University"},
    {"name": "Byung-Gon Chun", "affiliation": "Seoul National University"},
    {"name": "Natacha Crooks", "affiliation": "UC Berkeley"},
    {"name": "Jon Crowcroft", "affiliation": "University of Cambridge"},
    {"name": "Ittay Eyal", "affiliation": "Technion"},
    {"name": "Sasha Fedorova", "affiliation": "University of British Columbia"},
    {"name": "Anja Feldmann", "affiliation": "Max Planck Institute for Informatics (MPI-INF)"},
    {"name": "Jason Flinn", "affiliation": "Facebook"},
    {"name": "Roxana Geambasu", "affiliation": "Columbia University"},
    {"name": "Manya Ghobadi", "affiliation": "MIT"},
    {"name": "Philip Gibbons", "affiliation": "Carnegie Mellon University"},
    {"name": "Andreas Haeberlen", "affiliation": "University of Pennsylvania"},
    {"name": "Hermann Haertig", "affiliation": "TU Dresden"},
    {"name": "Steve Hand", "affiliation": "Google"},
    {"name": "Chris Hawblitzel", "affiliation": "Microsoft Research Redmond"},
    {"name": "Gernot Heiser", "affiliation": "UNSW / NICTA"},
    {"name": "Wenjun Hu", "affiliation": "Yale"},
    {"name": "Manos Kapritsos", "affiliation": "University of Michigan"},
    {"name": "Brad Karp", "affiliation": "University College London"},
    {"name": "Taesoo Kim", "affiliation": "Georgia Institute of Technology"},
    {"name": "Ana Klimovic", "affiliation": "ETH Zurich"},
    {"name": "Dejan Kostic", "affiliation": "KTH Royal Institute of Technology"},
    {"name": "Ramakrishna Kotla", "affiliation": "Amazon Web Services"},
    {"name": "Julia Lawall", "affiliation": "Inria/LIP6"},
    {"name": "Amit Levy", "affiliation": "Princeton University"},
    {"name": "Cheng Li", "affiliation": "USTC, China"},
    {"name": "Jinyang Li", "affiliation": "New York University"},
    {"name": "Jonathan Mace", "affiliation": "Max Planck Institute for Software Systems (MPI-SWS)"},
    {"name": "Sarah Meiklejohn", "affiliation": "University College London"},
    {"name": "James Mickens", "affiliation": "Harvard University"},
    {"name": "Jeff Mogul", "affiliation": "Google"},
    {"name": "Gilles Muller", "affiliation": "INRIA"},
    {"name": "Dushyanth Narayanan", "affiliation": "Microsoft Research Cambridge"},
    {"name": "KyoungSoo Park", "affiliation": "KAIST"},
    {"name": "Fernando Pedone", "affiliation": "University of Lugano"},
    {"name": "Simon Peter", "affiliation": "UT Austin"},
    {"name": "Peter Pietzuch", "affiliation": "Imperial College London"},
    {"name": "Raluca Popa", "affiliation": "UC Berkeley"},
    {"name": "Don Porter", "affiliation": "Univ. of North Carolina-Chapel Hill"},
    {"name": "Rodrigo Rodrigues", "affiliation": "Instituto Superior Técnico (IST - ULisboa), INESC-ID"},
    {"name": "Chris Rossbach", "affiliation": "UT Austin and VMware Research"},
    {"name": "Malte Schwarzkopf", "affiliation": "Brown University"},
    {"name": "Mark Silberstein", "affiliation": "Technion-Israel Institute of Technology"},
    {"name": "Ryan Stutsman", "affiliation": "University of Utah"},
    {"name": "Steve Swanson", "affiliation": "UC San Diego"},
    {"name": "Amin Vahdat", "affiliation": "Google, UCSD"},
    {"name": "Xi Wang", "affiliation": "University of Washington"},
    {"name": "Bernard Wong", "affiliation": "University of Waterloo"},
    {"name": "Junfeng Yang", "affiliation": "Columbia University"},
    {"name": "Minlan Yu", "affiliation": "Harvard University"},
    {"name": "Ding Yuan", "affiliation": "University of Toronto"},
    {"name": "Matei Zaharia", "affiliation": "Stanford University"},
    {"name": "Irene Zhang", "affiliation": "Microsoft Research Redmond"},
    {"name": "Yiying Zhang", "affiliation": "UC San Diego"},
    {"name": "Lidong Zhou", "affiliation": "Microsoft Research Asia"},
    {"name": "Noa Zilberman", "affiliation": "Oxford University"}
]

SOSP_2019 = [
    {"name": "Tim Brecht", "affiliation": "University of Waterloo"},
    {"name": "Carey Williamson", "affiliation": "University of Calgary"},
    {"name": "Remzi H. Arpaci-Dusseau", "affiliation": "University of Wisconsin"},
    {"name": "Yuanyuan Zhou", "affiliation": "University of California San Diego"},
    {"name": "Atul Adya", "affiliation": "Google"},
    {"name": "Nitin Agrawal", "affiliation": "ThoughtSpot"},
    {"name": "Samer Al-Kiswany", "affiliation": "Waterloo"},
    {"name": "Lorenzo Alvisi", "affiliation": "Cornell"},
    {"name": "David Andersen", "affiliation": "CMU"},
    {"name": "Sujata Banerjee", "affiliation": "VMware"},
    {"name": "Edouard Bugnion", "affiliation": "EPFL"},
    {"name": "Haibo Chen", "affiliation": "SJTU, China"},
    {"name": "Peter Chen", "affiliation": "Michigan"},
    {"name": "Yu Chen", "affiliation": "Tsinghua, China"},
    {"name": "Vijay Chidambaram", "affiliation": "Texas"},
    {"name": "Adam Chlipala", "affiliation": "MIT"},
    {"name": "Angela Demke Brown", "affiliation": "Toronto"},
    {"name": "Sasha Federova", "affiliation": "UBC"},
    {"name": "Joey Gonzalez", "affiliation": "UC Berkeley"},
    {"name": "Haryadi Gunawi", "affiliation": "Chicago"},
    {"name": "Gernot Heiser", "affiliation": "UNSW, Australia"},
    {"name": "Ryan Huang", "affiliation": "John Hopkins University"},
    {"name": "Rebecca Isaacs", "affiliation": "Twitter"},
    {"name": "Michael Kaminsky", "affiliation": "BrdgAI/CMU"},
    {"name": "Brad Karp", "affiliation": "University College London"},
    {"name": "Baris Kasikci", "affiliation": "Michigan"},
    {"name": "Taesoo Kim", "affiliation": "Georgia Tech"},
    {"name": "Eddie Kohler", "affiliation": "Harvard"},
    {"name": "Sanjeev Kumar", "affiliation": "Uber"},
    {"name": "Jinyang Li", "affiliation": "NYU"},
    {"name": "Carlos Maltzahn", "affiliation": "UCSC"},
    {"name": "James Mickens", "affiliation": "Harvard"},
    {"name": "Robert Morris", "affiliation": "MIT"},
    {"name": "Gilles Muller", "affiliation": "INRIA, France"},
    {"name": "Sam Noh", "affiliation": "UNIST, Korea"},
    {"name": "KyoungSoo Park", "affiliation": "KAIST, Korea"},
    {"name": "Raluca Popa", "affiliation": "Berkeley"},
    {"name": "Don Porter", "affiliation": "UNC"},
    {"name": "Dan Ports", "affiliation": "Microsoft Research"},
    {"name": "Tom Ristenpart", "affiliation": "Cornell"},
    {"name": "Chris Rossbach", "affiliation": "Texas"},
    {"name": "Leonid Ryzhyk", "affiliation": "VMware"},
    {"name": "Kai Shen", "affiliation": "Google"},
    {"name": "Justine Sherry", "affiliation": "CMU"},
    {"name": "Mark Silberstein", "affiliation": "Technion"},
    {"name": "Muthian Sivathanu", "affiliation": "Microsoft, India"},
    {"name": "Keith Smith", "affiliation": "NetApp"},
    {"name": "Deian Stefan", "affiliation": "UCSD"},
    {"name": "Ion Stoica", "affiliation": "UC Berkeley"},
    {"name": "Ryan Stutsman", "affiliation": "Utah"},
    {"name": "Shivaram Venkataraman", "affiliation": "Wisconsin"},
    {"name": "Emmett Witchel", "affiliation": "Texas"},
    {"name": "Tianyin Xu", "affiliation": "UIUC"},
    {"name": "Junfeng Yang", "affiliation": "Columbia"},
    {"name": "Irene Zhang", "affiliation": "Microsoft"},
    {"name": "Yiying Zhang", "affiliation": "Purdue"},
    {"name": "Lidong Zhou", "affiliation": "Microsoft Research Asia"}
]




from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def disambiguate_authors(chairs_list, previous_list):
    disambiguated_list = []
    used_names = set()

    for chair in chairs_list:
        best_match = None
        max_similarity = 0

        for prev_chair in previous_list:
            similarity = similar(chair['name'], prev_chair['name'])
            if similarity > max_similarity and chair['affiliation'] == prev_chair['affiliation']:
                max_similarity = similarity
                best_match = prev_chair

        if best_match is not None and best_match['name'] not in used_names:
            disambiguated_list.append(best_match)
            used_names.add(best_match['name'])
        else:
            disambiguated_list.append(chair)

    return disambiguated_list

# Combine all the committee chairs lists
all_chairs = OSDI_2023+ OSDI_2022+OSDI_2021+OSDI_2020+OSDI_2019+SOSP_2023+SOSP_2022+SOSP_2019

# Disambiguate and remove duplicates
unique_chairs = disambiguate_authors(all_chairs, all_chairs)

print(unique_chairs)

import csv

# Specify the filename for the CSV file
csv_filename = 'OS_PC.csv'

# Define the field names for the CSV header
field_names = ['name', 'affiliation']

# Write the data to the CSV file
with open(csv_filename, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=field_names)

    # Write the header
    writer.writeheader()

    # Write the committee_chairs data
    writer.writerows(unique_chairs)

print(f"The data has been written to {csv_filename}")


