committees = [
    {"name": "Hsin-Hsi Chen", "affiliation": "National Taiwan University"},
    {"name": "Wei-Jou (Edward) Duh", "affiliation": "National Taiwan University"},
    {"name": "Hen-Hsen Huang", "affiliation": "Academia Sinica"},
    {"name": "Makoto P. Kato", "affiliation": "University of Tsukuba"},
    {"name": "Josiane Mothe", "affiliation": "Université de Toulouse"},
    {"name": "Barbara Poblete", "affiliation": "University of Chile and Amazon Visiting Academic"},
    {"name": "Xiangnan He", "affiliation": "University of Science and Technology of China"},
    {"name": "Julian Urbano", "affiliation": "Delft University of Technology"},
    {"name": "Grace Hui Yang", "affiliation": "Georgetown University"},
    {"name": "Yaregal Assabie", "affiliation": "Addis Ababa University"},
    {"name": "Ellen M. Voorhees", "affiliation": "National Institute of Standards and Technology"},
    {"name": "Ricardo Baeza-Yates", "affiliation": "Northeastern University"},
    {"name": "Chua Tat Seng", "affiliation": "National University of Singapore"},
    {"name": "Jiafeng Guo", "affiliation": "University of Chinese Academy of Sciences"},
    {"name": "Gabriella Pasi", "affiliation": "University of Milano-Bicocca"},
    {"name": "Radu Ionescu", "affiliation": "University of Bucharest"},
    {"name": "Paul Thomas", "affiliation": "Microsoft Corporation"},
    {"name": "Altigran Soares da Silva", "affiliation": "Universidade Federal do Amazonas"},
    {"name": "Ruihua Song", "affiliation": "Renmin University of China"},
    {"name": "Debasis Ganguly", "affiliation": "University of Glasgow"},
    {"name": "Sole Pera", "affiliation": "Delft University of Technology"},
    {"name": "Liana Ermakova", "affiliation": "Université de Bretagne Occidentale"},
    {"name": "Maura R. Grossman", "affiliation": "University of Waterloo"},
    {"name": "Tracy Holloway King", "affiliation": "Adobe Inc."},
    {"name": "Zhao-Yan Ming", "affiliation": "Hangzhou City University"},
    {"name": "Emine Yilmaz", "affiliation": "UCL & Amazon"},
    {"name": "Kuan-Yu Chen", "affiliation": "National Taiwan University of Science and Technology"},
    {"name": "Pu-Jen Cheng", "affiliation": "National Taiwan University"},
    {"name": "Yung-Chun Chang", "affiliation": "Taipei Medical University"},
    {"name": "Maria Gäde", "affiliation": "Humboldt-Universität zu Berlin"},
    {"name": "Dan Li", "affiliation": "Elesvier"},
    {"name": "Ming-Feng Tsai", "affiliation": "National Chengchi University"},
    {"name": "Lun-Wei Ku", "affiliation": "Academia Sinica"},
    {"name": "Hussein Suleman", "affiliation": "University of Cape Town"},
    {"name": "Suzan Verberne", "affiliation": "University Leiden"},
    {"name": "Mark Sanderson", "affiliation": "RMIT University"},
    {"name": "Bracha Shapira", "affiliation": "Ben Gurion University of the Negev"},
    {"name": "Cheng-Te Li", "affiliation": "National Cheng Kung University"},
    {"name": "Lung-Hao Lee", "affiliation": "National Central University"},
    {"name": "Chung Chi Chen", "affiliation": "National Institute of Advanced Industrial Science and Technology, Japan"},
    {"name": "An-Zi Yen", "affiliation": "National Yang Ming Chiao Tung University"}
]

committees_1 = [
    {"name": "Fernando Diaz", "affiliation": "Google"},
    {"name": "Chirag Shah", "affiliation": "University of Washington"},
    {"name": "Torsten Suel", "affiliation": "New York University"},
    {"name": "Pablo Castells", "affiliation": "Universidad Autónoma de Madrid"},
    {"name": "Rosie Jones", "affiliation": "Spotify"},
    {"name": "Tetsuya Sakai", "affiliation": "Waseda University"},
    {"name": "Hui Fang", "affiliation": "University of Delaware"},
    {"name": "Claudia Hauff", "affiliation": "Technische Universiteit Delft"},
    {"name": "Ruihua Song", "affiliation": "Renmin University of China"},
    {"name": "Fernando Diaz", "affiliation": "Google"},
    {"name": "Chirag Shah", "affiliation": "University of Washington"},
    {"name": "Yiqun Liu", "affiliation": "Tsinghua University"},
    {"name": "Ian Soboroff", "affiliation": "National Institute of Standards and Technology"},
    {"name": "Miguel Martínez", "affiliation": "Signal AI"},
    {"name": "Milad Shokouhi", "affiliation": "Microsoft"},
    {"name": "Sengor Altingovde", "affiliation": "Middle East Technical University"},
    {"name": "Rodrygo Santos", "affiliation": "Universidade Federal de Minas Gerais"},
    {"name": "Hiroaki Ohshima", "affiliation": "University of Hyogo"},
    {"name": "Barbara Poblete", "affiliation": "University of Chile"},
    {"name": "Abdigani Dirye", "affiliation": "Unknown"},  # No affiliation provided
    {"name": "Jiafeng Guo", "affiliation": "Chinese Academy of Sciences"},
    {"name": "Hema Raghavan", "affiliation": "LinkedIn"},
    {"name": "Rishabh Mehrotra", "affiliation": "Spotify"},
    {"name": "Karthik Subbian", "affiliation": "Amazon"},
    {"name": "Alejandro Bellogín", "affiliation": "Universidad Autónoma de Madrid"},
    {"name": "Masaharu Yoshioka", "affiliation": "Hokkaido University"},
    {"name": "Jiqun Liu", "affiliation": "University of Oklahoma"},
    {"name": "Bhaskar Mitra", "affiliation": "Microsoft"},
    {"name": "Jian-Yun Nie", "affiliation": "Université de Montréal"},
    {"name": "Barbara Poblete", "affiliation": "University of Chile"},
    {"name": "Hussein Suleman", "affiliation": "University of Cape Town"},
    {"name": "Suzan Verberne", "affiliation": "Universiteit Leiden"},
    {"name": "Bhaskar Mitra", "affiliation": "Microsoft"},
    {"name": "Charlie Clarke", "affiliation": "University of Waterloo"},
    {"name": "Zhaochun Ren", "affiliation": "Shandong University"},
    {"name": "Alistair Moffat", "affiliation": "The University of Melbourne"},
    {"name": "Emine Yilmaz", "affiliation": "University College London, Amazon"},
    {"name": "Johanne Trippas", "affiliation": "The University of Melbourne"},
    {"name": "Matthew Mitsui", "affiliation": "VidIQ"}
]


program_committee = [
    {"name": "Panagiotis Adamopoulos", "affiliation": "Emory University – USA"},
    {"name": "Qingyao Ai", "affiliation": "University of Massachusetts Amherst – USA"},
    {"name": "Wei Ai", "affiliation": "University of Michigan – USA"},
    {"name": "Mohammad Akbari", "affiliation": "University College London – Singapore"},
    {"name": "Ahmet Aker", "affiliation": "University of Duisburg-Essen – Germany"},
    {"name": "Elif Aktolga", "affiliation": "Apple – USA"},
    {"name": "M-Dyaa Albakour", "affiliation": "Signal Media – UK"},
    {"name": "Ismail Sengor Altingovde", "affiliation": "Middle East Technical University – Turkey"},
    {"name": "Giuseppe Amato", "affiliation": "ISTI-CNR – Italy"},
    {"name": "Hadi Amiri", "affiliation": "Harvard University – USA"},
    {"name": "Avishek Anand", "affiliation": "L3S Research Center – Germany"},
    {"name": "Avi Arampatzis", "affiliation": "Democritus University of Thrace – Greece"},
    {"name": "Ioannis Arapakis", "affiliation": "Telefonica Research – Spain"},
    {"name": "Jaime Arguello", "affiliation": "The University of North Carolina at Chapel Hill – USA"},
    {"name": "Azin Ashkan", "affiliation": "Google – USA"},
    {"name": "Mossaab Bagdouri", "affiliation": "Walmart Labs – USA"},
    {"name": "Xiao Bai", "affiliation": "Yahoo Research – USA"},
    {"name": "Jie Bao", "affiliation": "JD Finance – China"},
    {"name": "Zhifeng Bao", "affiliation": "RMIT University – Australia"},
    {"name": "Alberto Barrón-Cedeño", "affiliation": "Università di Bologna – Italy"},
    {"name": "Srikanta Bedathur", "affiliation": "IIT Delhi – India"},
    {"name": "Klaus Berberich", "affiliation": "Saarbruecken University of Applied Sciences – Germany"},
    {"name": "Jiang Bian", "affiliation": "Microsoft – China"},
    {"name": "Asia J. Biega", "affiliation": "Microsoft Research Montréal – Germany"},
    {"name": "Bodo Billerbeck", "affiliation": "Microsoft – Australia"},
    {"name": "Lidong Bing", "affiliation": "Alibaba – China"},
    {"name": "Ilaria Bordino", "affiliation": "UniCredit R&D – Italy"},
    {"name": "Martin Braschler", "affiliation": "ZHAW – Switzerland"},
    {"name": "Sebastian Bruch", "affiliation": "Google – USA"},
    {"name": "George Buchanan", "affiliation": "The University of Melbourne – Australia"},
    {"name": "Fidel Cacheda", "affiliation": "Universidade da Coruña – Spain"},
    {"name": "Fei Cai", "affiliation": "National University of Defense Technology – China"},
    {"name": "Berkant Barla Cambazoglu", "affiliation": "RMIT University – Australia"},
    {"name": "Fazli Can", "affiliation": "Bilkent University – Turkey"},
    {"name": "Iván Cantador", "affiliation": "Universidad Autónoma de Madrid – Spain"},
    {"name": "Marc Cartright", "affiliation": "Google – USA"},
    {"name": "Pablo Castells", "affiliation": "Universidad Autónoma de Madrid – Spain"},
    {"name": "Kevin Chang", "affiliation": "University of Illinois at Urbana-Champaign – USA"},
    {"name": "Hsin-Hsi Chen", "affiliation": "National Taiwan University – Taiwan"},
    {"name": "Ruey-Cheng Chen", "affiliation": "SEEK – Australia"},
    {"name": "Zhumin Chen", "affiliation": "Shandong university – China"},
    {"name": "Max Chevalier", "affiliation": "Université de Toulouse, CNRS – France"},
    {"name": "Adrian-Gabriel Chifu", "affiliation": "Université Aix-Marseille-Toulon, CNRS, LIS – France"},
    {"name": "Evangelia Christakopoulou", "affiliation": "University of Minnesota – USA"},
    {"name": "Gordon Cormack", "affiliation": "University of Waterloo – Canada"},
    {"name": "Matt Crane", "affiliation": "Facebook – USA"},
    {"name": "Paolo Cremonesi", "affiliation": "Politecnico di Milano – Italy"},
    {"name": "Tonya Custis", "affiliation": "Thomson Reuters – USA"},
    {"name": "Zhuyun Dai", "affiliation": "Carnegie Mellon University – USA"},
    {"name": "Jeffrey Dalton", "affiliation": "University of Glasgow – UK"},
    {"name": "Luis M. de Campos", "affiliation": "University of Granada – Spain"},
    {"name": "Gianluca Demartini", "affiliation": "The University of Queensland – Australia"},
    {"name": "Elena Demidova", "affiliation": "L3S Research Center – Germany"},
    {"name": "Hongbo Deng", "affiliation": "Alibaba – USA"},
    {"name": "Laura Dietz", "affiliation": "University of New Hampshire – USA"},
    {"name": "B. Taner Dincer", "affiliation": "University of Mugla – Turkey"},
    {"name": "Zhuoye Ding", "affiliation": "JD.com – China"},
    {"name": "Doug Downey", "affiliation": "Northwestern University – USA"},
    {"name": "Carsten Eickhoff", "affiliation": "Brown University – USA"},
    {"name": "Tamer Elsayed", "affiliation": "Qatar University – Qatar"},
    {"name": "Liana Ermakova", "affiliation": "HCTI Université de Bretagne Occidentale – Russia"},
    {"name": "Yi Fang", "affiliation": "Santa Clara University – USA"},
    {"name": "Fuli Feng", "affiliation": "National University of Singapore – Singapore"},
    {"name": "Juan M. Fernández-Luna", "affiliation": "University of Granada – Spain"},
    {"name": "Nicola Ferro", "affiliation": "University of Padova – Italy"},
    {"name": "Besnik Fetahu", "affiliation": "L3S Research Center – Germany"},
    {"name": "Simone Filice", "affiliation": "Amazon – USA"},
    {"name": "Marcus Fontoura", "affiliation": "Microsoft – USA"},
    {"name": "Adam Fourney", "affiliation": "Microsoft – USA"},
    {"name": "Edward Fox", "affiliation": "Virginia Tech – USA"},
    {"name": "Patrick Gallinari", "affiliation": "Sorbonne Université – France"},
    {"name": "Iftah Gamzu", "affiliation": "Amazon – USA"},
    {"name": "Debasis Ganguly", "affiliation": "IBM Ireland Research Lab – Ireland"},
    {"name": "Wei Gao", "affiliation": "Victoria University of Wellington – New Zealand"},
    {"name": "Dario Garigliotti", "affiliation": "University of Stavanger – Norway"},
    {"name": "Shlomo Geva", "affiliation": "Queensland University of Technology – Australia"},
    {"name": "Debanjan Ghosh", "affiliation": "Massachusetts Institute of Technology – USA"},
    {"name": "Anastasia Giachanou", "affiliation": "Universitat Politècnica de València – Spain"},
    {"name": "Goran Glavaš", "affiliation": "University of Mannheim – Germany"},
    {"name": "Lorraine Goeuriot", "affiliation": "Université Grenoble Alpes, CNRS – France"},
    {"name": "Marcos Goncalves", "affiliation": "Federal University of Minas Gerais – Brazil"},
    {"name": "David Graus", "affiliation": "FD Mediagroep – The Netherlands"},
    {"name": "Krishna Gummadi", "affiliation": "MPI-SWS – Germany"},
    {"name": "Guibing Guo", "affiliation": "Northeastern University – China"},
    {"name": "Parth Gupta", "affiliation": "Amazon – Spain"},
    {"name": "Cathal Gurrin", "affiliation": "Dublin City University – Ireland"},
    {"name": "Kishaloy Halder", "affiliation": "National University of Singapore – Singapore"},
    {"name": "Martin Halvey", "affiliation": "University of Strathclyde – UK"},
    {"name": "Shuguang Han", "affiliation": "Google – USA"},
    {"name": "Allan Hanbury", "affiliation": "Vienna University of Technology – Austria"},
    {"name": "Morgan Harvey", "affiliation": "Northumbria University – UK"},
    {"name": "Ben He", "affiliation": "University of Chinese Academy of Sciences – China"},
    {"name": "Daqing He", "affiliation": "University of Pittsburgh – USA"},
    {"name": "Qi He", "affiliation": "LinkedIn – USA"},
    {"name": "Xiangnan He", "affiliation": "University of Science and Technology of China – China"},
    {"name": "Chathra Hendahewa", "affiliation": "TD Bank Group – USA"},
    {"name": "Tuan-Anh Hoang", "affiliation": "L3S Research Center, Leibniz University of Hanover – Germany"},
    {"name": "Orland Hoeber", "affiliation": "University of Regina – Canada"},
    {"name": "Liangjie Hong", "affiliation": "Etsy Inc. – USA"},
    {"name": "Richang Hong", "affiliation": "Hefei University of Technology – China"},
    {"name": "Frank Hopfgartner", "affiliation": "The University of Sheffield – UK"},
    {"name": "Hsun-Ping Hsieh", "affiliation": "National Cheng Kung University – Taiwan"},
    {"name": "Chao Huang", "affiliation": "University of Notre Dame – USA"},
    {"name": "Jimmy Huang", "affiliation": "York University – Canada"},
    {"name": "Zi Huang", "affiliation": "The University of Queensland – Australia"},
    {"name": "Juan F. Huete", "affiliation": "University of Granada – Spain"},
    {"name": "Kai Hui", "affiliation": "Amazon – Germany"},
    {"name": "Muhammad Imran", "affiliation": "Qatar Computing Research Institute – Qatar"},
    {"name": "Amir Ingber", "affiliation": "Amazon Research – Israel"},
    {"name": "Radu Tudor Ionescu", "affiliation": "University of Bucharest – Romania"},
    {"name": "Shoaib Jameel", "affiliation": "Kent University – UK"},
    {"name": "Peng Jiang", "affiliation": "Kwai Inc. – China"},
    {"name": "Jiepu Jiang", "affiliation": "Virginia Tech – USA"},
    {"name": "Xin Jiang", "affiliation": "Huawei Noah's Ark Lab – Hong Kong"},
    {"name": "Xiaolong Jin", "affiliation": "Chinese Academy of Sciences – China"},
    {"name": "Gareth Jones", "affiliation": "Dublin City University – Ireland"},
    {"name": "Roy Ka-Wei Lee", "affiliation": "Singapore Management University – Singapore"},
    {"name": "Nattiya Kanhabua", "affiliation": "NTENT – Spain"},
    {"name": "Maryam Karimzadehgan", "affiliation": "Google – USA"},
    {"name": "Markus Kattenbeck", "affiliation": "Vienna Technical University – Germany"},
    {"name": "Liadh Kelly", "affiliation": "Maynooth University – Ireland"},
    {"name": "Evgeny Kharitonov", "affiliation": "Facebook AI – Russia"},
    {"name": "Jaewon Kim", "affiliation": "RMIT University – Australia"},
    {"name": "Sunyoung Kim", "affiliation": "Rutgers University – USA"},
    {"name": "Yubin Kim", "affiliation": "UPMC Enterprises – USA"},
    {"name": "Julia Kiseleva", "affiliation": "Microsoft Research AI – USA"},
    {"name": "Deguang Kong", "affiliation": "Yahoo Research – USA"},
    {"name": "Weize Kong", "affiliation": "Google – USA"},
    {"name": "Bevan Koopman", "affiliation": "CSIRO – Australia"},
    {"name": "Alexander Kotov", "affiliation": "Wayne State University – USA"},
    {"name": "Elad Kravi", "affiliation": "Amazon Research – Israel"},
    {"name": "Udo Kruschwitz", "affiliation": "University of Essex – UK"},
    {"name": "Abhimanyu Lad", "affiliation": "LinkedIn, Corp. – USA"},
    {"name": "Yanyan Lan", "affiliation": "ICT – China"},
    {"name": "Ni Lao", "affiliation": "SayMosaic – USA"},
    {"name": "Gal Lavee", "affiliation": "Microsoft – Israel"}
]

program_committee_1 = [
    {"name": "Chia-Jung Lee", "affiliation": "Microsoft – USA"},
    {"name": "Wenqiang Lei", "affiliation": "National University of Singapore – Singapore"},
    {"name": "Jochen L. Leidner", "affiliation": "Refinitiv Labs and University of Sheffield – UK"},
    {"name": "Luis A. Leiva", "affiliation": "Sciling, SL – Spain"},
    {"name": "Ran Levy", "affiliation": "Amazon – USA"},
    {"name": "Cheng Li", "affiliation": "Google – USA"},
    {"name": "Chenliang Li", "affiliation": "Wuhan University – China"},
    {"name": "Liangda Li", "affiliation": "Yahoo Lab! – USA"},
    {"name": "Piji Li", "affiliation": "Tencent – China"},
    {"name": "Yong Li", "affiliation": "Tsinghua University – China"},
    {"name": "Defu Lian", "affiliation": "University of Science and Technology of China – China"},
    {"name": "Shangsong Liang", "affiliation": "Sun Yat-sen University – UK"},
    {"name": "Lizi Liao", "affiliation": "National University of Singapore – Singapore"},
    {"name": "Alexander Libov", "affiliation": "Amazon – Israel"},
    {"name": "Chang Liu", "affiliation": "Peking University – China"},
    {"name": "Huan Liu", "affiliation": "Arizona State University – USA"},
    {"name": "Jie Liu", "affiliation": "Nankai University – China"},
    {"name": "Jingjing Liu", "affiliation": "M.D. Anderson Cancer Center – USA"},
    {"name": "Kang Liu", "affiliation": "Chinese Academy of Sciences – China"},
    {"name": "Wei Liu", "affiliation": "Tencent AI Lab – China"},
    {"name": "Xiaodong Liu", "affiliation": "Microsoft – USA"},
    {"name": "Xiaozhong Liu", "affiliation": "Indiana University Bloomington – USA"},
    {"name": "Xuanzhe Liu", "affiliation": "Peking University – China"},
    {"name": "Zhiyuan Liu", "affiliation": "Tsinghua University – China"},
    {"name": "Andreas Lommatzsch", "affiliation": "TU Berlin – Germany"},
    {"name": "David Losada", "affiliation": "University of Santiago de Compostela – Spain"},
    {"name": "Wei Lu", "affiliation": "Singapore University of Technology and Design – Singapore"},
    {"name": "Xiaolu Lu", "affiliation": "RMIT University – Australia"},
    {"name": "Claudio Lucchese", "affiliation": "Ca' Foscari University of Venice – Italy"},
    {"name": "Cheng Luo", "affiliation": "Tsinghua University – China"},
    {"name": "Ping Luo", "affiliation": "Chinese Academy of Sciences – China"},
    {"name": "Mihai Lupu", "affiliation": "Research Studios Austria – Austria"},
    {"name": "Qin Lv", "affiliation": "University of Colorado Boulder – USA"},
    {"name": "Yuanhua Lv", "affiliation": "Microsoft – USA"},
    {"name": "Weizhi Ma", "affiliation": "Tsinghua University – China"},
    {"name": "Andrew Macfarlane", "affiliation": "City, University of London – UK"},
    {"name": "Joel Mackenzie", "affiliation": "RMIT University – Australia"},
    {"name": "Joao Magalhaes", "affiliation": "Universidade NOVA de Lisboa – Portugal"},
    {"name": "Maria Maistro", "affiliation": "University of Padua – Italy"},
    {"name": "Jiaxin Mao", "affiliation": "Tsinghua University – China"},
    {"name": "Xian-Ling Mao", "affiliation": "Beijing Institute of Technology – China"},
    {"name": "Flavio Martins", "affiliation": "Universidade NOVA de Lisboa – Portugal"},
    {"name": "Yosi Mass", "affiliation": "IBM Haifa Research Lab – Israel"},
    {"name": "Julian Mcauley", "affiliation": "University of California San Diego – USA"},
    {"name": "Richard Mccreadie", "affiliation": "University of Glasgow – UK"},
    {"name": "Rishabh Mehrotra", "affiliation": "Spotify Research – UK"},
    {"name": "Florian Meier", "affiliation": "Aalborg University Copenhagen – Germany"},
    {"name": "Edgar Meij", "affiliation": "Bloomberg L.P. – UK"},
    {"name": "Bhaskar Mitra", "affiliation": "Microsoft – UK"},
    {"name": "Matthew Mitsui", "affiliation": "Rutgers University – USA"},
    {"name": "Stefano Mizzaro", "affiliation": "University of Udine – Italy"},
    {"name": "Mohand Boughanem", "affiliation": "Université de Toulouse, CNRS – France"},
    {"name": "Mitra Mohtarami", "affiliation": "MIT Computer Science and Artificial Intelligence Lab – USA"},
    {"name": "Felipe Moraes", "affiliation": "Delft University of Technology – The Netherlands"},
    {"name": "Alejandro Moreo Fernández", "affiliation": "Istituto di Scienza e Tecnologie dell'Informazione A. Faedo – Italy"},
    {"name": "Yashar Moshfeghi", "affiliation": "University of Strathclyde – UK"},
    {"name": "Henning Müller", "affiliation": "HES-SO – Switzerland"},
    {"name": "Seung-Hoon Na", "affiliation": "Chonbuk National University – South Korea"},
    {"name": "Preslav Nakov", "affiliation": "Qatar Computing Research Institute, HBKU – Qatar"},
    {"name": "Franco Maria Nardini", "affiliation": "ISTI-CNR – Italy"},
    {"name": "Liqiang Nie", "affiliation": "Shandong University – China"},
    {"name": "Alexandros Ntoulas", "affiliation": "LinkedIn – USA"},
    {"name": "Neil O'Hare", "affiliation": "Yahoo Research – USA"},
    {"name": "Alexandra Olteanu", "affiliation": "Microsoft – USA"},
    {"name": "Harrie Oosterhuis", "affiliation": "University of Amsterdam – The Netherlands"},
    {"name": "Eliyahu Osherovich", "affiliation": "Amazon.com – Israel"},
    {"name": "Vito Claudio Ostuni", "affiliation": "Pandora – USA"},
    {"name": "Jiaul Paik", "affiliation": "IIT Kharagpur – India"},
    {"name": "Liang Pang", "affiliation": "Institute of Computer Technology, Chinese Academy of Sciences – China"},
    {"name": "Haris Papageorgiou", "affiliation": "Institute for Language and Speech Processing – Greece"},
    {"name": "Alexandra Papoutsaki", "affiliation": "Pomona College – USA"},
    {"name": "Javier Parapar", "affiliation": "IRLab, Computer Science Dept., University of A Coruña – Spain"},
    {"name": "Dae Hoon Park", "affiliation": "Yahoo Research – USA"},
    {"name": "Gabriella Pasi", "affiliation": "University of Milano-Bicocca – Italy"},
    {"name": "Jan Pedersen", "affiliation": "Uber Technologies – USA"},
    {"name": "Jian Pei", "affiliation": "Simon Fraser University – Canada"},
    {"name": "Baolin Peng", "affiliation": "The Chinese University of Hong Kong – Hong Kong"},
    {"name": "Giulio Ermanno Pibiri", "affiliation": "University of Pisa – Italy"},
    {"name": "Vassilis Plachouras", "affiliation": "Facebook – UK"},
    {"name": "Martin Potthast", "affiliation": "Leipzig University – Germany"},
    {"name": "Zhen Qin", "affiliation": "Google – USA"},
    {"name": "Fiana Raiber", "affiliation": "Yahoo Research – Israel"},
    {"name": "Maya Ramanath", "affiliation": "IIT Delhi – India"},
    {"name": "Jinfeng Rao", "affiliation": "University of Maryland – USA"},
    {"name": "Edie Rasmussen", "affiliation": "The University of British Columbia – Canada"},
    {"name": "Pengjie Ren", "affiliation": "University of Amsterdam – The Netherlands"},
    {"name": "Xiang Ren", "affiliation": "University of Southern California – USA"},
    {"name": "Yongli Ren", "affiliation": "RMIT University – Australia"},
    {"name": "Zhaochun Ren", "affiliation": "JD.com – China"},
    {"name": "Chiara Renso", "affiliation": "ISTI-CNR, Pisa, Italy – Italy"},
    {"name": "Haggai Roitman", "affiliation": "IBM Research Haifa – Israel"},
    {"name": "Tuukka Ruotsalo", "affiliation": "University of Helsinki – Finland"},
    {"name": "Rishiraj Saha Roy", "affiliation": "Max Planck Institute for Informatics – Germany"},
    {"name": "Alan Said", "affiliation": "University of Gothenburg – Sweden"},
    {"name": "Eric Sanjuan", "affiliation": "Laboratoire Informatique d'Avignon- Université d'Avignon – France"},
    {"name": "Rodrygo Santos", "affiliation": "Universidade Federal de Minas Gerais – Brazil"},
    {"name": "Denis Savenkov", "affiliation": "Facebook – USA"},
    {"name": "Ralf Schenkel", "affiliation": "Trier University – Germany"},
    {"name": "Huawei Shen", "affiliation": "Chinese Academy of Sciences – China"},
    {"name": "Mário J. Silva", "affiliation": "Instituto Superior Técnico, Universidade de Lisboa, INESC-ID – Portugal"},
    {"name": "Gianmaria Silvello", "affiliation": "University of Padova – Italy"},
    {"name": "Jakob Grue Simonsen", "affiliation": "University of Copenhagen – Denmark"},
    {"name": "Moumita Sinha", "affiliation": "Adobe Inc. – India"},
    {"name": "Laurianne Sitbon", "affiliation": "Queensland University of Technology – Australia"},
    {"name": "Catherine Smith", "affiliation": "Kent State University – USA"},
    {"name": "Luca Soldaini", "affiliation": "Amazon – USA"},
    {"name": "Dawei Song", "affiliation": "The Open University – UK"},
    {"name": "Xuemeng Song", "affiliation": "Shandong University – Singapore"},
    {"name": "Yang Song", "affiliation": "Google – USA"},
    {"name": "Damiano Spina", "affiliation": "RMIT University – Australia"},
    {"name": "Efstathios Stamatatos", "affiliation": "University of the Aegean – Greece"},
    {"name": "Torsten Suel", "affiliation": "New York University – USA"},
    {"name": "Kazunari Sugiyama", "affiliation": "National University of Singapore – Singapore"},
    {"name": "Aixin Sun", "affiliation": "Nanyang Technological University – Singapore"},
    {"name": "Fei Sun", "affiliation": "Alibaba Group – China"},
    {"name": "Jiliang Tang", "affiliation": "Michigan State University – USA"},
    {"name": "Jinhui Tang", "affiliation": "Nanjing University of Science and Technology – China"},
    {"name": "Jintao Tang", "affiliation": "National University of Defense Technology – China"},
    {"name": "Thrivikrama Taula", "affiliation": "Apple Inc – USA"},
    {"name": "Gabriele Tolomei", "affiliation": "University of Padua – Italy"},
    {"name": "Nicola Tonellotto", "affiliation": "ISTI-CNR – Italy"},
    {"name": "Salvatore Trani", "affiliation": "ISTI-CNR – Italy"},
    {"name": "Christoph Trattner", "affiliation": "University of Bergen – Norway"},
    {"name": "Manos Tsagkias", "affiliation": "904Labs – The Netherlands"},
    {"name": "Md Zia Ullah", "affiliation": "Université de Toulouse – France"},
    {"name": "Kazutoshi Umemoto", "affiliation": "The University of Tokyo – Japan"},
    {"name": "Julián Urbano", "affiliation": "Delft University of Technology – The Netherlands"},
    {"name": "Christophe Van Gysel", "affiliation": "Apple Inc. – The Netherlands"},
    {"name": "Olivier Van Laere", "affiliation": "Apple Inc. – USA"},
    {"name": "Theodoros Vasiloudis", "affiliation": "SICS Swedish ICT – Sweden"},
    {"name": "Rossano Venturini", "affiliation": "Dipartimento di Informatica, Università di Pisa – Italy"}
]

committee_data_2 = [
    {"name": "Suzan Verberne", "affiliation": "LIACS, Leiden University – The Netherlands"},
    {"name": "Vishwa Vinay", "affiliation": "Adobe Research Bangalore – India"},
    {"name": "Henning Wachsmuth", "affiliation": "Paderborn University – Germany"},
    {"name": "Bin Wang", "affiliation": "Xiaomi AI Labs – China"},
    {"name": "Chuan-Ju Wang", "affiliation": "Academia Sinica – Taiwan"},
    {"name": "Hongning Wang", "affiliation": "University of Virginia – USA"},
    {"name": "Lidan Wang", "affiliation": "University of Maryland – USA"},
    {"name": "Meng Wang", "affiliation": "Hefei University of Technology – China"},
    {"name": "Quan Wang", "affiliation": "Institute of Information Engineering, Chinese Academy of Sciences – China"},
    {"name": "Shuaiqiang Wang", "affiliation": "JD.com – China"},
    {"name": "Xiang Wang", "affiliation": "National University of Singapore – Singapore"},
    {"name": "Yue Wang", "affiliation": "University of Michigan – USA"},
    {"name": "Yulu Wang", "affiliation": "Google – USA"},
    {"name": "Ziqi Wang", "affiliation": "Facebook – UK"},
    {"name": "Wouter Weerkamp", "affiliation": "904Labs – The Netherlands"},
    {"name": "Ran Wolff", "affiliation": "Yahoo Research – USA"},
    {"name": "Liang Wu", "affiliation": "Airbnb, Inc. – USA"},
    {"name": "Wei Wu", "affiliation": "Microsoft – China"},
    {"name": "Chenyan Xiong", "affiliation": "Carnegie Mellon University; Microsoft – USA"},
    {"name": "Takehiro Yamamoto", "affiliation": "University of Hyogo – Japan"},
    {"name": "Liu Yang", "affiliation": "University of Massachusetts Amherst – USA"},
    {"name": "Peilin Yang", "affiliation": "Twitter – USA"},
    {"name": "Ting Yao", "affiliation": "JD AI Research – China"},
    {"name": "Hongzhi Yin", "affiliation": "The University of Queensland – Australia"},
    {"name": "Fan Yixing", "affiliation": "Chinese Academy of Sciences – China"},
    {"name": "Zhengtao Yu", "affiliation": "Kunming University of Science and Technology – China"},
    {"name": "Xiaojun Yuan", "affiliation": "University at Albany – USA"},
    {"name": "Hamed Zamani", "affiliation": "University of Massachusetts Amherst – USA"},
    {"name": "Aston Zhang", "affiliation": "Amazon AI – USA"},
    {"name": "Baichuan Zhang", "affiliation": "Facebook – USA"},
    {"name": "Fan Zhang", "affiliation": "Tsinghua University – China"},
    {"name": "Hanwang Zhang", "affiliation": "Nanyang Technological University – USA"},
    {"name": "Mingyang Zhang", "affiliation": "Google – USA"},
    {"name": "Peng Zhang", "affiliation": "Tianjin University – China"},
    {"name": "Qi Zhang", "affiliation": "Fudan University – China"},
    {"name": "Rongting Zhang", "affiliation": "Amazon – USA"},
    {"name": "Shuo Zhang", "affiliation": "University of Stavanger – Norway"},
    {"name": "Weinan Zhang", "affiliation": "Harbin Institute of Technology – China"},
    {"name": "Ying Zhang", "affiliation": "Nankai University – China"},
    {"name": "Zhiwei Zhang", "affiliation": "Facebook Inc – USA"},
    {"name": "Bo Zhao", "affiliation": "Pinterest – USA"},
    {"name": "Jiashu Zhao", "affiliation": "JD.com – China"},
    {"name": "Le Zhao", "affiliation": "Houzz Inc – USA"},
    {"name": "Shiwan Zhao", "affiliation": "IBM Research – China"},
    {"name": "Wayne Xin Zhao", "affiliation": "Renmin University of China – China"},
    {"name": "Yong Zheng", "affiliation": "Illinois Institute of Technology – USA"},
    {"name": "Xiaofei Zhu", "affiliation": "Chongqing University of Technology – China"},
    {"name": "Yadong Zhu", "affiliation": "Mobvista – China"},
    {"name": "Imed Zitouni", "affiliation": "Microsoft – USA"},
    {"name": "Guido Zuccon", "affiliation": "The University of Queensland – Australia"}
]


committee_data_3 = [
    {"name": "Eytan Adar", "affiliation": "University of Michigan – USA"},
    {"name": "Eugene Agichtein", "affiliation": "Emory University and Amazon – USA"},
    {"name": "Amr Ahmed", "affiliation": "Google – USA"},
    {"name": "Omar Alonso", "affiliation": "Microsoft – USA"},
    {"name": "Javed Aslam", "affiliation": "Northeastern University – USA"},
    {"name": "Leif Azzopardi", "affiliation": "University of Strathclyde – UK"},
    {"name": "Ricardo Baeza-Yates", "affiliation": "NTENT, Northeastern University, Universitat Pompeu Fabra, Universidad de Chile – USA/Spain/Chile"},
    {"name": "Krisztian Balog", "affiliation": "University of Stavanger – Norway"},
    {"name": "Nicholas Belkin", "affiliation": "Rutgers University – USA"},
    {"name": "Michael Bendersky", "affiliation": "Google – USA"},
    {"name": "Paul Bennett", "affiliation": "Microsoft – USA"},
    {"name": "Jamie Callan", "affiliation": "Carnegie Mellon University – USA"},
    {"name": "Robert Capra", "affiliation": "The University of North Carolina at Chapel Hill – USA"},
    {"name": "David Carmel", "affiliation": "Amazon – Israel"},
    {"name": "Ben Carterette", "affiliation": "University of Delaware – USA"},
    {"name": "Carlos Castillo", "affiliation": "Universitat Pompeu Fabra – Spain"},
    {"name": "James Caverlee", "affiliation": "Texas A&M University – USA"},
    {"name": "Yi Chang", "affiliation": "Jilin University – USA"},
    {"name": "Tat-Seng Chua", "affiliation": "National University of Singapore – Singapore"},
    {"name": "Charles Clarke", "affiliation": "University of Waterloo – Canada"},
    {"name": "Nick Craswell", "affiliation": "Microsoft – USA"},
    {"name": "Bruce Croft", "affiliation": "University of Massachusetts Amherst – USA"},
    {"name": "J. Shane Culpepper", "affiliation": "RMIT University – Australia"},
    {"name": "Brian Davison", "affiliation": "Lehigh University – USA"},
    {"name": "Maarten de Rijke", "affiliation": "University of Amsterdam – The Netherlands"},
    {"name": "Arjen de Vries", "affiliation": "Radboud University – The Netherlands"},
    {"name": "Fernando Diaz", "affiliation": "Spotify – USA"},
    {"name": "Debora Donato", "affiliation": "Mix Tech – USA"},
    {"name": "David Elsweiler", "affiliation": "University of Regensburg – Germany"},
    {"name": "Hui Fang", "affiliation": "University of Delaware – USA"},
    {"name": "Norbert Fuhr", "affiliation": "University of Duisburg-Essen – Germany"},
    {"name": "Evgeniy Gabrilovich", "affiliation": "Google – USA"},
    {"name": "Julio Gonzalo", "affiliation": "UNED – Spain"},
    {"name": "Jiafeng Guo", "affiliation": "Chinese Academy of Sciences – China"},
    {"name": "Ido Guy", "affiliation": "eBay Research – Israel"},
    {"name": "Claudia Hauff", "affiliation": "TU DELFT – The Netherlands"},
    {"name": "Jiyin He", "affiliation": "Signal – UK"},
    {"name": "Djoerd Hiemstra", "affiliation": "Radboud University – The Netherlands"},
    {"name": "Jeff Huang", "affiliation": "Brown University – USA"},
    {"name": "Hideo Joho", "affiliation": "University of Tsukuba – Japan"},
    {"name": "Vanja Josifovski", "affiliation": "Pinterest – USA"},
    {"name": "Jaap Kamps", "affiliation": "University of Amsterdam – The Netherlands"},
    {"name": "Min-Yen Kan", "affiliation": "National University of Singapore – Singapore"},
    {"name": "Noriko Kando", "affiliation": "National Institute of Informatics – Japan"},
    {"name": "Jussi Karlgren", "affiliation": "Gavagai and KTH Royal Institute of Technology – Sweden"},
    {"name": "Makoto P. Kato", "affiliation": "Kyoto University – Japan"},
    {"name": "Diane Kelly", "affiliation": "University of Tennessee – USA"},
    {"name": "Yehuda Koren", "affiliation": "Google – Israel"},
    {"name": "Wessel Kraaij", "affiliation": "Leiden University – The Netherlands"},
    {"name": "Oren Kurland", "affiliation": "Technion, Israel Institute of Technology – Israel"},
    {"name": "Wai Lam", "affiliation": "The Chinese University of Hong Kong – China"},
    {"name": "Matthew Lease", "affiliation": "The University of Texas at Austin – USA"},
    {"name": "Liane Lewin-Eytan", "affiliation": "Amazon Research – Israel"},
    {"name": "Hang Li", "affiliation": "Bytedance AI Lab – China"},
    {"name": "Ee-Peng Lim", "affiliation": "Singapore Management University – Singapore"},
    {"name": "Jimmy Lin", "affiliation": "University of Waterloo – Canada"},
    {"name": "Christina Lioma", "affiliation": "University of Copenhagen – Denmark"},
    {"name": "Tie-Yan Liu", "affiliation": "Microsoft – China"},
    {"name": "Yiqun Liu", "affiliation": "Tsinghua University – China"},
    {"name": "R. Manmatha", "affiliation": "Amazon – USA"},
    {"name": "Qiaozhu Mei", "affiliation": "University of Michigan – USA"},
    {"name": "Tao Mei", "affiliation": "AI Research of JD.com – China"},
    {"name": "Donald Metzler", "affiliation": "Google – USA"},
    {"name": "Alistair Moffat", "affiliation": "The University of Melbourne – Australia"},
    {"name": "Alessandro Moschitti", "affiliation": "Amazon – USA"},
    {"name": "Josiane Mothe", "affiliation": "Université de Toulouse, CNRS – France"},
    {"name": "Isabelle Moulinier", "affiliation": "Capital One – USA"},
    {"name": "Vanessa Murdock", "affiliation": "Amazon – USA"},
    {"name": "Wolfgang Nejdl", "affiliation": "L3S and University of Hannover – Germany"},
    {"name": "Douglas W. Oard", "affiliation": "University of Maryland – USA"},
    {"name": "Raffaele Perego", "affiliation": "ISTI-CNR – Italy"},
    {"name": "Benjamin Piwowarski", "affiliation": "CNRS - Sorbonne Université – France"},
    {"name": "Barbara Poblete", "affiliation": "University of Chile – Chile"},
    {"name": "Kira Radinsky", "affiliation": "eBay – Israel"},
    {"name": "Filip Radlinski", "affiliation": "Google – UK"},
    {"name": "Berthier Ribeiro-Neto", "affiliation": "Google Engineering & CS Department, UFMG – Brazil"},
    {"name": "Paolo Rosso", "affiliation": "Universitat Politecnica de Valencia – Spain"},
    {"name": "Ian Ruthven", "affiliation": "University of Strathclyde – UK"},
    {"name": "Tetsuya Sakai", "affiliation": "Waseda University – Japan"},
    {"name": "Mark Sanderson", "affiliation": "RMIT University – Australia"},
    {"name": "Fabrizio Sebastiani", "affiliation": "Italian National Council of Research – Italy"},
    {"name": "Chirag Shah", "affiliation": "Rutgers University – USA"},
    {"name": "Milad Shokouhi", "affiliation": "Microsoft – UK"},
    {"name": "Fabrizio Silvestri", "affiliation": "Facebook – UK"},
    {"name": "Mark Smucker", "affiliation": "University of Waterloo – Canada"},
    {"name": "Ian Soboroff", "affiliation": "NIST – USA"},
    {"name": "Aya Soffer", "affiliation": "IBM Research – Israel"},
    {"name": "Ruihua Song", "affiliation": "Microsoft – China"},
    {"name": "Neel Sundaresan", "affiliation": "Microsoft – USA"},
    {"name": "Paul Thomas", "affiliation": "Microsoft – Australia"},
    {"name": "Andrew Trotman", "affiliation": "University of Otago – New Zealand"},
    {"name": "Xuanhui Wang", "affiliation": "Google – USA"},
    {"name": "Gerhard Weikum", "affiliation": "Max Planck Institute for Informatics – Germany"},
    {"name": "Ji-Rong Wen", "affiliation": "Renmin University of China – China"},
    {"name": "Ryen White", "affiliation": "Microsoft – USA"},
    {"name": "Jun Xu", "affiliation": "Renmin University of China – China"},
    {"name": "Grace Hui Yang", "affiliation": "Georgetown University – USA"},
    {"name": "Dawei Yin", "affiliation": "JD.com – USA"},
    {"name": "Elad Yom-Tov", "affiliation": "Microsoft – Israel"},
    {"name": "Justin Zobel", "affiliation": "The University of Melbourne – Australia"}
]

all_chairs_data = [
    {"name": "Yoelle Maarek", "affiliation": "Amazon Research"},
    {"name": "Jian-Yun Nie", "affiliation": "University of Montreal"},
    {"name": "Falk Scholer", "affiliation": "RMIT University"},
    {"name": "Zhicheng Dou", "affiliation": "Renmin University of China"},
    {"name": "Mounia Lalmas", "affiliation": "Spotify"},
    {"name": "Marc Najork", "affiliation": "Google"}
]


from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def disambiguate_authors(chairs_list, previous_list):
    disambiguated_list = []
    used_names = set()

    for chair in chairs_list:
        best_match = None
        max_similarity = 0

        for prev_chair in previous_list:
            similarity = similar(chair['name'], prev_chair['name'])
            if similarity > max_similarity and chair['affiliation'] == prev_chair['affiliation']:
                max_similarity = similarity
                best_match = prev_chair

        if best_match is not None and best_match['name'] not in used_names:
            disambiguated_list.append(best_match)
            used_names.add(best_match['name'])
        else:
            disambiguated_list.append(chair)

    return disambiguated_list

# Combine all the committee chairs lists
all_chairs = committees + committees_1 + program_committee + program_committee_1 + committee_data_2 + committee_data_3 + all_chairs_data

# Disambiguate and remove duplicates
unique_chairs = disambiguate_authors(all_chairs, all_chairs)

print(unique_chairs)

import csv

# Specify the filename for the CSV file
csv_filename = 'SIGIR_PC.csv'

# Define the field names for the CSV header
field_names = ['name', 'affiliation']

# Write the data to the CSV file
with open(csv_filename, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=field_names)

    # Write the header
    writer.writeheader()

    # Write the committee_chairs data
    writer.writerows(unique_chairs)

print(f"The data has been written to {csv_filename}")