committee_chairs_2023 = [
    {'name': 'Tor Aamodt', 'affiliations': 'University of British Columbia'},
    {'name': 'José Luis Abellán', 'affiliations': 'Universidad Católica de Murcia, Spain'},
    {'name': 'Alaa Alameldeen', 'affiliations': 'Simon Fraser University'},
    {'name': 'Nael Abu-Ghazaleh', 'affiliations': 'University of California Riverside'},
    {'name': 'Jung Ho Ahn', 'affiliations': 'SNU'},
    {'name': 'Shoaib Akram', 'affiliations': 'Australian National University'},
    {'name': 'Ismail Akturk', 'affiliations': 'Ozyegin University'},
    {'name': 'Erik Altman', 'affiliations': 'IBM Research'},
    {'name': 'Juan Luis Aragon', 'affiliations': 'Universidad de Murcia'},
    {'name': 'Bahar Asgari', 'affiliations': 'University of Maryland'},
    {'name': 'Rajeev Balasubramonian', 'affiliations': 'University of Utah'},
    {'name': 'Trinayan Baruah', 'affiliations': 'AMD'},
    {'name': 'Scott Beamer', 'affiliations': 'UC Santa Cruz'},
    {'name': 'Nathan Beckmann', 'affiliations': 'CMU'},
    {'name': 'Evgeny Bolotin', 'affiliations': 'NVIDIA'},
    {'name': 'Ramon Canal', 'affiliations': 'UPC'},
    {'name': 'Jose Cano', 'affiliations': 'University of Glascow'},
    {'name': 'Trevor E. Carlson', 'affiliations': 'National University of Singapore'},
    {'name': 'John Carter', 'affiliations': 'IBM Research'},
    {'name': 'Yiran Chen', 'affiliations': 'Duke University'},
    {'name': 'Yufei Ding', 'affiliations': 'UCSB'},
    {'name': 'Srinivas Devadas', 'affiliations': 'Massachusetts Institute of Technology'},
    {'name': 'Ronald Dreslinski', 'affiliations': 'University of Michigan'},
    {'name': 'Lieven Eeckhout', 'affiliations': 'Ghent University'},
    {'name': 'Zhenman Fang', 'affiliations': 'Simon Fraser University'},
    {'name': 'Bjoern Franke', 'affiliations': 'University of Edinburgh'},
    {'name': 'Dimitris Gizopoulos', 'affiliations': 'University of Athens'},
    {'name': 'Maya Gokhale', 'affiliations': 'LLNL'},
    {'name': 'Antonio Gonzalez', 'affiliations': 'Polytechnic University of Catalonia'},
    {'name': 'Dibakar Gope', 'affiliations': 'ARM'},
    {'name': 'Xiaochen Guo', 'affiliations': 'Lehigh University'},
    {'name': 'Nikos Hardavellas', 'affiliations': 'Northwestern University'},
    {'name': 'Mark Hempstead', 'affiliations': 'Tufts University'},
    {'name': 'Kei Hiraki', 'affiliations': 'Preferred Networks'},
    {'name': 'James C. Hoe', 'affiliations': 'Carnegie Mellon University'},
    {'name': 'Nima Honarmand', 'affiliations': 'SUNY Stony Brook'},
    {'name': 'Jian Huang', 'affiliations': 'University of Illinois at Urbana-Champaign'},
    {'name': 'Michael Huang', 'affiliations': 'University of Rochester'},
    {'name': 'Yipeng Huang', 'affiliations': 'Rutgers University'},
    {'name': 'Clayton Hughes', 'affiliations': 'Sandia National Laboratories'},
    {'name': 'Jaehyuk Huh', 'affiliations': 'KAIST'},
    {'name': 'Koji Inoue', 'affiliations': 'Kyushu University'},
    {'name': 'Engin Ipek', 'affiliations': 'Qualcomm'},
    {'name': 'Ravishankar Iyer', 'affiliations': 'Intel'},
    {'name': 'Paolo Rech', 'affiliations': 'University of Trento'},
    {'name': 'Vijay Janapa Reddi', 'affiliations': 'Harvard/UT Austin/Google'},
    {'name': 'Byunghyun Jang', 'affiliations': 'U Mississippi'},
    {'name': 'Hyeran Jeon', 'affiliations': 'University of California, Merced'},
    {'name': 'Daniel Jiménez', 'affiliations': 'Texas A&M University'},
    {'name': 'Adwait Jog', 'affiliations': 'William & Mary'},
    {'name': 'Russ Joseph', 'affiliations': 'Northwestern University'},
    {'name': 'Krishnan Kailas', 'affiliations': 'IBM Research'},
    {'name': 'Sudarsun Kannan', 'affiliations': 'Rutgers'},
    {'name': 'Omer Khan', 'affiliations': 'University of Connecticut'},
    {'name': 'John Kim', 'affiliations': 'KAIST'},
    {'name': 'Rakesh Kumar', 'affiliations': 'Norwegian University of Science and Technology (NTNU)'},
    {'name': 'Benjamin Lee', 'affiliations': 'Duke'},
    {'name': 'Xue Lin', 'affiliations': 'Northeastern University'},
    {'name': 'Gabriel Loh', 'affiliations': 'AMD Research'},
    {'name': 'Jason Lowe-Power', 'affiliations': 'University of California, Davis'},
    {'name': 'Divya Mahajan', 'affiliations': 'Microsoft'},
    {'name': 'José Martínez', 'affiliations': 'Cornell University'},
    {'name': 'Gokhan Memik', 'affiliations': 'Northwestern University'},
    {'name': 'Pierre Michaud', 'affiliations': 'Inria'},
    {'name': 'Prakash Murali', 'affiliations': 'Microsoft'},
    {'name': 'Hoda Naghibijouybari', 'affiliations': 'Binghamton University'},
    {'name': 'Fanny Nina Paravecino', 'affiliations': 'Microsoft'},
    {'name': 'Tirthak Patel', 'affiliations': 'Rice University'},
    {'name': 'Gilles Pokam', 'affiliations': 'Intel'},
    {'name': 'Dmitry Ponomarev', 'affiliations': 'SUNY Binghamton'},
    {'name': 'Jose Renau', 'affiliations': 'UC Santa-Cruz'},
    {'name': 'Minsoo Rhu', 'affiliations': 'KAIST'},
    {'name': 'Timothy G. Rogers', 'affiliations': 'Purdue University'},
    {'name': 'Alberto Ros', 'affiliations': 'University of Murcia'},
    {'name': 'Eric Rotenberg', 'affiliations': 'North Carolina State University'},
    {'name': 'Julio Sahuquillo', 'affiliations': 'Universitat Politecnica off Valencia'},
    {'name': 'Smruti R. Sarangi', 'affiliations': 'IIT Delhi'},
    {'name': 'Yanos Sazeides', 'affiliations': 'University of Cyprus'},
    {'name': 'Resit Sendag', 'affiliations': 'University of Rhode Island'},
    {'name': 'Xipeng Shen', 'affiliations': 'North Carolina State University'},
    {'name': 'Cristina Silvano', 'affiliations': 'Politecnico di Milano'},
    {'name': 'Ravi Soundararajan', 'affiliations': 'VMware'},
    {'name': 'Per Stenström', 'affiliations': 'Chalmers University of Technology'},
    {'name': 'Sreenivas Subramoney', 'affiliations': 'Intel Labs'},
    {'name': 'Yifan Sun', 'affiliations': 'William & Mary'},
    {'name': 'Jakub Szefer', 'affiliations': 'Yale University'},
    {'name': 'Radu Teodorescu', 'affiliations': 'Ohio State'},
    {'name': 'Devesh Tiwari', 'affiliations': 'Northeastern University'},
    {'name': 'Josep Torrellas', 'affiliations': 'University of Illinois Urbana-Champaign'},
    {'name': 'Pedro Trancoso', 'affiliations': 'Chalmers University of Technology'},
    {'name': 'Hung-Wei Tseng', 'affiliations': 'University of California, Riverside'},
    {'name': 'James Tuck', 'affiliations': 'North Carolina State University'},
    {'name': 'Osman Unsal', 'affiliations': 'BSC'},
    {'name': 'Guru Venkataramani', 'affiliations': 'George Washington University'},
    {'name': 'Rujia Wang', 'affiliations': 'Illinois Institute of Technology'},
    {'name': 'Daniel Wong', 'affiliations': 'University of California, Riverside'},
    {'name': 'Lisa Wu Wills', 'affiliations': 'Duke University'},
    {'name': 'Yuan Xie', 'affiliations': 'Univ. of California Santa Barbara'},
    {'name': 'Xiaolin Xu', 'affiliations': 'Northeastern University'},
    {'name': 'Ayse Yilmazer', 'affiliations': 'Istanbul Technical University'},
    {'name': 'Lixin Zhang', 'affiliations': 'CAS – Chinese Academy of Sciences'},
    {'name': 'Huiyang Zhou', 'affiliations': 'NC State University'}
]

committee_chairs_2022 = [
    {'name': 'Stefanos Kaxiras', 'affiliations': 'Uppsala University'},
    {'name': 'Tor Aamodt', 'affiliations': 'University of British Columbia'},
    {'name': 'Alaa Alameldeen', 'affiliations': 'Simon Fraser University'},
    {'name': 'Omer Anjum', 'affiliations': 'UIUC'},
    {'name': 'Juan Luis Aragón', 'affiliations': 'University of Murcia'},
    {'name': 'Todd Austin', 'affiliations': 'University of Michigan'},
    {'name': 'Arkaprava Basu', 'affiliations': 'Indian Institute of Science'},
    {'name': 'Nathan Beckmann', 'affiliations': 'CMU'},
    {'name': 'Koen Bertels', 'affiliations': 'QbeeX.com'},
    {'name': 'Trey Cain', 'affiliations': 'NVIDIA'},
    {'name': 'John Carter', 'affiliations': 'IBM'},
    {'name': 'Yiran Chen', 'affiliations': 'Duke University'},
    {'name': 'Derek Chiou', 'affiliations': 'Microsoft / The University of Texas at Austin'},
    {'name': 'Esha Choukse', 'affiliations': 'Microsoft Research'},
    {'name': 'Marcelo Cintra', 'affiliations': 'Center of Advanced European Studies and Research'},
    {'name': 'Caroline Collange', 'affiliations': 'Inria, Univ Rennes, CNRS, IRISA'},
    {'name': 'Guilherme Cox', 'affiliations': 'NVIDIA'},
    {'name': 'Alexandros Daglis', 'affiliations': 'Georgia Tech'},
    {'name': 'Zidong Du', 'affiliations': 'Institute of Computing Technology, Chinese Academy of Sciences'},
    {'name': 'Sandhya Dwarkadas', 'affiliations': 'University of Rochester'},
    {'name': 'Wendy Elsasser', 'affiliations': 'Arm Research'},
    {'name': 'Christopher Fletcher', 'affiliations': 'University of Illinois–Urbana Champaign'},
    {'name': 'Saugata Ghose', 'affiliations': 'University of Illinois Urbana-Champaign'},
    {'name': 'Boris Grot', 'affiliations': 'University of Edinburgh'},
    {'name': 'Mark Hempstead', 'affiliations': 'Tufts University'},
    {'name': 'Andrew D. Hilton', 'affiliations': 'Duke University'},
    {'name': 'James C. Hoe', 'affiliations': 'Carnegie Mellon University'},
    {'name': 'H. Peter Hofstee', 'affiliations': 'IBM Systems'},
    {'name': 'Nima Honarmand', 'affiliations': 'Independent Consultant'},
    {'name': 'Yang Hu', 'affiliations': 'UT Dallas'},
    {'name': 'Yipeng Huang', 'affiliations': 'Rutgers University'},
    {'name': 'Koji Inoue', 'affiliations': 'Kyushu University'},
    {'name': 'Engin Ipek', 'affiliations': 'Qualcomm'},
    {'name': 'Magnus Jahre', 'affiliations': 'Norwegian University of Science and Technology'},
    {'name': 'Akanksha Jain', 'affiliations': 'Google'},
    {'name': 'Xun Jian', 'affiliations': 'Virginia Tech'},
    {'name': 'Daniel Jiménez', 'affiliations': 'Texas A&M University'},
    {'name': 'Timothy Jones', 'affiliations': 'University of Cambridge'},
    {'name': 'Ulya Karpuzcu', 'affiliations': 'University Minnesota'},
    {'name': 'Jangwoo Kim', 'affiliations': 'Seoul National University'},
    {'name': 'Young Geun Kim', 'affiliations': 'Soongsil University'},
    {'name': 'Tushar Krishna', 'affiliations': 'Georgia Tech'},
    {'name': 'Rakesh Kumar', 'affiliations': 'Norwegian University of Science and Technology'},
    {'name': 'Benjamin C. Lee', 'affiliations': 'University of Pennsylvania'},
    {'name': 'Ruby Lee', 'affiliations': 'Princeton'},
    {'name': 'Gabriel Loh', 'affiliations': 'AMD Research'},
    {'name': 'Divya Mahajan', 'affiliations': 'Microsoft'},
    {'name': 'Diana Marculescu', 'affiliations': 'The University of Texas at Austin'},
    {'name': 'Jason Mars', 'affiliations': 'University of Michigan'},
    {'name': 'Avi Mendelson', 'affiliations': 'Technion'},
    {'name': 'Pierre Michaud', 'affiliations': 'Inria'},
    {'name': 'Shubu Mukherjee', 'affiliations': 'Cavium'},
    {'name': 'Abdullah Muzahid', 'affiliations': 'Texas A&M University'},
    {'name': 'Soner Onder', 'affiliations': 'Michigan Technological University'},
    {'name': 'Dionisios Pnevmatikatos', 'affiliations': 'National Technical University of Athens & FORTH'},
    {'name': 'Gilles A Pokam', 'affiliations': 'Intel'},
    {'name': 'Sai Manoj Pudukotai Dinakarrao', 'affiliations': 'George Mason University'},
    {'name': 'Xuehai Qian', 'affiliations': 'University of Southern California'},
    {'name': 'Priyanka Raina', 'affiliations': 'Stanford University'},
    {'name': 'Steve Reinhardt', 'affiliations': 'Microsoft'},
    {'name': 'Eric Rotenberg', 'affiliations': 'North Carolina State University'},
    {'name': 'Karu Sankaralingam', 'affiliations': 'University of Wisconsin'},
    {'name': 'Kelly Shaw', 'affiliations': 'Williams College'},
    {'name': 'John Paul Shen', 'affiliations': 'Carnegie Mellon University'},
    {'name': 'Matthew D. Sinclair', 'affiliations': 'University of Wisconsin-Madison / AMD Research'},
    {'name': 'Anand Sivasubramaniam', 'affiliations': 'Penn State University'},
    {'name': 'Kevin Skadron', 'affiliations': 'University of Virginia'},
    {'name': 'Dimitrios Skarlatos', 'affiliations': 'CMU'},
    {'name': 'Ioannis Sourdis', 'affiliations': 'Chalmers University of Technology'},
    {'name': 'Sreenivas Subramoney', 'affiliations': 'Intel Labs'},
    {'name': 'Edward Suh', 'affiliations': 'Cornell University / Facebook'},
    {'name': 'Zehra Sura', 'affiliations': 'Bloomberg'},
    {'name': 'Samantika Sury', 'affiliations': 'Intel'},
    {'name': 'Jakub Szefer', 'affiliations': 'Yale University'},
    {'name': 'Michael Taylor', 'affiliations': 'U. Washington'},
    {'name': 'Elvira Teran', 'affiliations': 'Texas A&M International University'},
    {'name': 'Devesh Tiwari', 'affiliations': 'Northeastern University'},
    {'name': 'James Tuck', 'affiliations': 'North Carolina State University'},
    {'name': 'Dean Tullsen', 'affiliations': 'University of California, San Diego'},
    {'name': 'Osman Unsal', 'affiliations': 'BSC'},
    {'name': 'Radha Venkatagiri', 'affiliations': 'Oregon State University'},
    {'name': 'Swagath Venkataramani', 'affiliations': 'IBM Corporation'},
    {'name': 'Gu-Yeon Wei', 'affiliations': 'Harvard'},
    {'name': 'Daniel Wong', 'affiliations': 'University of California, Riverside'},
    {'name': 'Lisa Wu Wills', 'affiliations': 'Duke University'},
    {'name': 'Mengjia Yan', 'affiliations': 'MIT'},
    {'name': 'Chia-Lin Yang', 'affiliations': 'National Taiwan University'},
    {'name': 'Jun Yang', 'affiliations': 'University of Pittsburgh'},
    {'name': 'Donald Yeung', 'affiliations': 'University of Maryland'},
    {'name': 'Hongil Yoon', 'affiliations': 'Google'},
    {'name': 'Clifford Young', 'affiliations': 'Google'},
    {'name': 'Huiyang Zhou', 'affiliations': 'North Carolina State University'},
    {'name': 'Yuhao Zhu', 'affiliations': 'University of Rochester'}
]

committee_chairs_2021 = [
    {'name': 'Murali Annavaram', 'affiliations': 'University of Southern California'},
    {'name': 'Nael Abu-Ghazaleh', 'affiliations': 'University of California, Riverside'},
    {'name': 'Alaa R. Alameldeen', 'affiliations': 'Intel'},
    {'name': 'Hari Angepat', 'affiliations': 'Microsoft Azure'},
    {'name': 'Newsha Ardalani', 'affiliations': 'Baidu Research'},
    {'name': 'Amro Awad', 'affiliations': 'North Carolina State University'},
    {'name': 'Evgeny Bolotin', 'affiliations': 'NVIDIA'},
    {'name': 'Mainak Chaudhuri', 'affiliations': 'Indian Institute of Technology, Kanpur'},
    {'name': 'Lizhong Chen', 'affiliations': 'Oregon State University'},
    {'name': 'Derek Chiou', 'affiliations': 'The University of Texas at Austin'},
    {'name': 'Eric S. Chung', 'affiliations': 'Microsoft'},
    {'name': 'Jason Clemons', 'affiliations': 'NVIDIA'},
    {'name': 'Srini Devadas', 'affiliations': 'Massachusetts Institute of Technology'},
    {'name': 'Ronald Dreslinski', 'affiliations': 'University of Michigan'},
    {'name': 'Zidong Du', 'affiliations': 'Chinese Academy of Sciences'},
    {'name': 'Sandhya Dwarkadas', 'affiliations': 'University of Rochester'},
    {'name': 'Hadi Esmaeilzadeh', 'affiliations': 'University of California, San Diego'},
    {'name': 'Christopher W. Fletcher', 'affiliations': 'University of Illinois at Urbana-Champaign'},
    {'name': 'Antonio Gonzalez', 'affiliations': 'Universitat Politecnica de Catalunya'},
    {'name': 'R. Govindarajan', 'affiliations': 'Indian Institute of Science'},
    {'name': 'Paul V. Gratz', 'affiliations': 'Texas A&M University'},
    {'name': 'Anthony Gutierrez', 'affiliations': 'AMD Research'},
    {'name': 'James C. Hoe', 'affiliations': 'Carnegie Mellon University'},
    {'name': 'Peter Hofstee', 'affiliations': 'IBM'},
    {'name': 'Yipeng Huang', 'affiliations': 'Princeton University'},
    {'name': 'Jaehyuk Huh', 'affiliations': 'KAIST'},
    {'name': 'Koji Inoue', 'affiliations': 'Kyushu University'},
    {'name': 'Engin Ipek', 'affiliations': 'University of Rochester'},
    {'name': 'Bruce Jacob', 'affiliations': 'University of Maryland'},
    {'name': 'Akanksha Jain', 'affiliations': 'The University of Texas at Austin'},
    {'name': 'Hyeran Jeon', 'affiliations': 'University of California, Merced'},
    {'name': 'Adwait Jog', 'affiliations': 'College of William & Mary'},
    {'name': 'Russ Joseph', 'affiliations': 'Northwestern University'},
    {'name': 'Stefanos Kaxiras', 'affiliations': 'Uppsala University'},
    {'name': 'Samira Khan', 'affiliations': 'University of Virginia'},
    {'name': 'Eun Jung Kim', 'affiliations': 'Texas A&M University'},
    {'name': 'Jangwoo Kim', 'affiliations': 'Seoul National University'},
    {'name': 'John Kim', 'affiliations': 'KAIST'},
    {'name': 'Michel Kinsy', 'affiliations': 'Boston University'},
    {'name': 'Gunjae Koo', 'affiliations': 'Korea University'},
    {'name': 'Tushar Krishna', 'affiliations': 'Georgia Institute of Technology'},
    {'name': 'Hsien-Hsin Sean Lee', 'affiliations': 'Facebook'},
    {'name': 'Benjamin C. Lee', 'affiliations': 'Duke University'},
    {'name': 'Jing-Jia Liou', 'affiliations': 'National Tsing Hua University'},
    {'name': 'Mieszko Lis', 'affiliations': 'University of British Columbia'},
    {'name': 'Ahmed Louri', 'affiliations': 'George Washington University'},
    {'name': 'Brandon Lucia', 'affiliations': 'Carnegie Mellon University'},
    {'name': 'Divya Mahajan', 'affiliations': 'Microsoft'},
    {'name': 'Amirsaman Memaripour', 'affiliations': 'MongoDB'},
    {'name': 'Joshua San Miguel', 'affiliations': 'University of Wisconsin-Madison'},
    {'name': 'Vijaykrishnan Narayanan', 'affiliations': 'Pennsylvania State University'},
    {'name': 'Satish Narayanasamy', 'affiliations': 'University of Michigan'},
    {'name': 'Tony Nowatzki', 'affiliations': 'University of California, Los Angeles'},
    {'name': 'Soner Onder', 'affiliations': 'Michigan Technological University'},
    {'name': 'Fanny Nina Paravecino', 'affiliations': 'Microsoft'},
    {'name': 'Gennady Pekhimenko', 'affiliations': 'University of Toronto'},
    {'name': 'Dmitry Ponomarev', 'affiliations': 'Binghamton University'},
    {'name': 'Milos Prvulovic', 'affiliations': 'Georgia Institute of Technology'},
    {'name': 'Xuehai Qian', 'affiliations': 'University of Southern California'},
    {'name': 'Brandon Reagen', 'affiliations': 'Facebook'},
    {'name': 'Steve Reinhardt', 'affiliations': 'Microsoft'},
    {'name': 'Minsoo Rhu', 'affiliations': 'KAIST'},
    {'name': 'Won Woo Ro', 'affiliations': 'Yonsei University'},
    {'name': 'Timothy G. Rogers', 'affiliations': 'Purdue University'},
    {'name': 'Eric Rotenberg', 'affiliations': 'North Carolina State University'},
    {'name': 'Jack Sampson', 'affiliations': 'Pennsylvania State University'},
    {'name': 'Smruti Ranjan Sarangi', 'affiliations': 'Indian Institute of Technology, Delhi'},
    {'name': 'Xipeng Shen', 'affiliations': 'North Carolina State University'},
    {'name': 'Timothy Sherwood', 'affiliations': 'University of California, Santa Barbara'},
    {'name': 'Seunghee Shin', 'affiliations': 'Binghamton University'},
    {'name': 'Ryota Shioya', 'affiliations': 'University of Tokyo'},
    {'name': 'Anand Sivasubramaniam', 'affiliations': 'Pennsylvania State University'},
    {'name': 'Ravi Soundararajan', 'affiliations': 'VMware'},
    {'name': 'Vilas Sridharan', 'affiliations': 'AMD'},
    {'name': 'Per Stenström', 'affiliations': 'Chalmers University of Technology'},
    {'name': 'Lavanya Subramanian', 'affiliations': 'Facebook'},
    {'name': 'Sreenivas Subramoney', 'affiliations': 'Intel'},
    {'name': 'Jakub Szefer', 'affiliations': 'Yale University'},
    {'name': 'Xulong Tang', 'affiliations': 'University of Pittsburgh'},
    {'name': 'Michael Taylor', 'affiliations': 'University of Washington'},
    {'name': 'Mohit Tiwari', 'affiliations': 'The University of Texas at Austin'},
    {'name': 'Po-An Tsai', 'affiliations': 'Massachusetts Institute of Technology'},
    {'name': 'Hung-Wei Tseng', 'affiliations': 'University of California, Riverside'},
    {'name': 'Bhuvan Urgaonkar', 'affiliations': 'Pennsylvania State University'},
    {'name': 'Nandita Vijaykumar', 'affiliations': 'University of Toronto'},
    {'name': 'Daniel Wong', 'affiliations': 'University of California, Riverside'},
    {'name': 'Yuan Xie', 'affiliations': 'University of California, Santa Barbara'},
    {'name': 'Menjia Yan', 'affiliations': 'Massachusetts Institute of Technology'},
    {'name': 'Amir Yazdanbakhsh', 'affiliations': 'Google Research'},
    {'name': 'Hongil Yoon', 'affiliations': 'Google'}
]


committee_chairs_2020 = [
    {'name': 'Michel Kinsy', 'affiliations': 'Boston University'},
    {'name': 'Amro Awad', 'affiliations': 'University of Central Florida'},
    {'name': 'Seunghee Shin', 'affiliations': 'Binghamton University'},
    {'name': 'Lide Duan', 'affiliations': 'Alibaba'},
    {'name': 'Xu Liu', 'affiliations': 'Williams & Mary'},
    {'name': 'Hung-Wei Tseng', 'affiliations': 'University of California, Riverside'},
    {'name': 'Jun Yang', 'affiliations': 'University of Pittsburgh'},
    {'name': 'Guru Venkataramani', 'affiliations': 'George Washington University'},
    {'name': 'Omer Khan', 'affiliations': 'University of Connecticut'},
    {'name': 'Lu Peng', 'affiliations': 'Louisiana State University'},
    {'name': 'Jishen Zhao', 'affiliations': 'University of California, San Diego'},
    {'name': 'Lin Zhong', 'affiliations': 'Rice University'},
    {'name': 'Felix Lin', 'affiliations': 'Purdue University'},
    {'name': 'Lizy John', 'affiliations': 'University of Texas, Austin'},
    {'name': 'Ulya Karpuzcu', 'affiliations': 'University of Minnesota'},
    {'name': 'Antonia Zhai', 'affiliations': 'University of Minnesota'},
    {'name': 'Antonio Gonzalez', 'affiliations': 'Universitat Politècnica de Catalunya'},
    {'name': 'Per Stenstrom', 'affiliations': 'Chalmers University of Technology'},
    {'name': 'Aasheesh Kolli', 'affiliations': 'Penn State University'},
    {'name': 'Chita Das', 'affiliations': 'Penn State University'},
    {'name': 'Pedro Trancoso', 'affiliations': 'Chalmers University of Technology'},
    {'name': 'Hong Wang', 'affiliations': 'Intel'},
    {'name': 'Keiji Kimura', 'affiliations': 'Waseda University'},
    {'name': 'Koji Inoue', 'affiliations': 'Kyushu University'},
    {'name': 'Xiaochen Guo', 'affiliations': 'Lehigh University'},
    {'name': 'Alaa Alameldeen', 'affiliations': 'Intel'},
    {'name': 'Ahmed Louri', 'affiliations': 'George Washington University'},
    {'name': 'William Wang', 'affiliations': 'ARM'},
    {'name': 'Newsha Ardalani', 'affiliations': 'Baidu'},
    {'name': 'Tosiron Adegbija', 'affiliations': 'University of Arizona'},
    {'name': 'Daniel Jimenez', 'affiliations': 'Texas A&M University'},
    {'name': 'Tam Chantem', 'affiliations': 'Virginia Tech'},
    {'name': 'Wendy Elsasser', 'affiliations': 'ARM'},
    {'name': 'Julio Sahuquillo', 'affiliations': 'Universitat Politecnica de Valencia'},
    {'name': 'Eric (Yun) Liang', 'affiliations': 'Peking University'},
    {'name': 'Radu Teodorescu', 'affiliations': 'Ohio State University'},
    {'name': 'Paul Gratz', 'affiliations': 'Texas A&M University'},
    {'name': 'Jian Huang', 'affiliations': 'University of Illinois, Urbana-Champaign'},
    {'name': 'Nael Abu-Ghazaleh', 'affiliations': 'University of California, Riverside'},
    {'name': 'Peter Varman', 'affiliations': 'Rice University'},
    {'name': 'Huiyang Zhou', 'affiliations': 'North Carolina State University'},
    {'name': 'Ashish Venkat', 'affiliations': 'University of Virginia'},
    {'name': 'Abdullah Muzahid', 'affiliations': 'Texas A&M University'},
    {'name': 'Gautham Chinya', 'affiliations': 'Intel'},
    {'name': 'Devesh Tiwari', 'affiliations': 'Northeastern University'},
    {'name': 'Adwait Jog', 'affiliations': 'College of William & Mary'},
    {'name': 'Jing Li', 'affiliations': 'University of Wisconsin'},
    {'name': 'Russ Joseph', 'affiliations': 'Northwestern University'},
    {'name': 'Karu Sankaralingam', 'affiliations': 'University of Wisconsin'},
    {'name': 'Chia-Lin Yang', 'affiliations': 'National Taiwan University'},
    {'name': 'Lizhong Chen', 'affiliations': 'Oregon State University'},
    {'name': 'Arthur Perais', 'affiliations': 'Microsoft'},
    {'name': 'Fan Yao', 'affiliations': 'University of Central Florida'},
    {'name': 'Lei Liu', 'affiliations': 'Chinese Academy of Sciences'},
]


committee_chairs_2019 = [
    {'name': 'Alaa Alameldeen', 'affiliations': 'Intel'},
    {'name': 'Mahdi Nazm Bojnordi', 'affiliations': 'University of Utah'},
    {'name': 'Anirudh Badam', 'affiliations': 'Microsoft'},
    {'name': 'Pradip Bose', 'affiliations': 'IBM Research'},
    {'name': 'David Brooks', 'affiliations': 'Harvard University'},
    {'name': 'Ramon Canal', 'affiliations': 'Universitat Politècnica de Catalunya'},
    {'name': 'Niladrish Chatterjee', 'affiliations': 'NVIDIA'},
    {'name': 'Liqun Cheng', 'affiliations': 'Google'},
    {'name': 'Jason Clemons', 'affiliations': 'NVIDIA'},
    {'name': 'Lieven Eeckhout', 'affiliations': 'Ghent University'},
    {'name': 'Michael Ferdman', 'affiliations': 'Stony Brook University'},
    {'name': 'Jayneel Gandhi', 'affiliations': 'VMware Research'},
    {'name': 'Antonio Gonzalez', 'affiliations': 'Universitat Politècnica de Catalunya'},
    {'name': 'R Govindarajan', 'affiliations': 'Indian Institute of Science'},
    {'name': 'Paul V. Gratz', 'affiliations': 'Texas A&M University'},
    {'name': 'Xiaochen Guo', 'affiliations': 'Lehigh University'},
    {'name': 'James C. Hoe', 'affiliations': 'Carnegie Mellon University'},
    {'name': 'Rui Hou', 'affiliations': 'Chinese Academy of Sciences'},
    {'name': 'Lisa Hsu', 'affiliations': 'Qualcomm'},
    {'name': 'Jaehyuk Huh', 'affiliations': 'Korea Advanced Institute of Science and Technology'},
    {'name': 'Hillery Hunter', 'affiliations': 'IBM Research'},
    {'name': 'Akanksha Jain', 'affiliations': 'The University of Texas at Austin'},
    {'name': 'Nuwan Jayasena', 'affiliations': 'AMD'},
    {'name': 'Lizy Kurian John', 'affiliations': 'The University of Texas at Austin'},
    {'name': 'Ulya Karpuzcu', 'affiliations': 'University of Minnesota/Brown University'},
    {'name': 'John Kim', 'affiliations': 'Korea Advanced Institute of Science and Technology'},
    {'name': 'Avinash Karanth', 'affiliations': 'Ohio University'},
    {'name': 'Aasheesh Kolli', 'affiliations': 'Pennsylvania State University'},
    {'name': 'Benjamin Lee', 'affiliations': 'Duke University'},
    {'name': 'David Lo', 'affiliations': 'Google'},
    {'name': 'Pierre Michaud', 'affiliations': 'INRIA'},
    {'name': 'Andreas Moshovos', 'affiliations': 'University of Toronto'},
    {'name': 'Vijayanand Nagarajan', 'affiliations': 'University of Edinburgh'},
    {'name': 'Vijaykrishnan Narayanan', 'affiliations': 'Pennsylvania State University'},
    {'name': 'Shruti Padmanabha', 'affiliations': 'Facebook'},
    {'name': 'Tom Pawlowski', 'affiliations': 'Micron'},
    {'name': 'Dmitry Ponomarev', 'affiliations': 'Binghamton University'},
    {'name': 'Xuehai Qian', 'affiliations': 'University of Southern California'},
    {'name': 'Moinuddin Qureshi', 'affiliations': 'Georgia Tech'},
    {'name': 'Steve Reinhardt', 'affiliations': 'Microsoft'},
    {'name': 'Minsoo Rhu', 'affiliations': 'Korea Advanced Institute of Science and Technology'},
    {'name': 'Joshua San Miguel', 'affiliations': 'University of Wisconsin-Madison'},
    {'name': 'Vivek Seshadri', 'affiliations': 'Microsoft Research India'},
    {'name': 'Arrvindh Shriraman', 'affiliations': 'Simon Fraser University'},
    {'name': 'Yan Solihin', 'affiliations': 'North Carolina State University'},
    {'name': 'Phillip Stanley-Marbell', 'affiliations': 'University of Cambridge'},
    {'name': 'Sreenivas Subramoney', 'affiliations': 'Intel Labs'},
    {'name': 'Guangyu Sun', 'affiliations': 'Peking University'},
    {'name': 'Elvira Teran', 'affiliations': 'Texas A&M International University'},
    {'name': 'Josep Torrellas', 'affiliations': 'University of Illinois at Urbana-Champaign'},
    {'name': 'Paul Whatmough', 'affiliations': 'ARM/Harvard University'},
    {'name': 'Lisa Wu', 'affiliations': 'University of California, Berkeley'},
    {'name': 'Jun Yang', 'affiliations': 'University of Pittsburgh'},
    {'name': 'Cliff Young', 'affiliations': 'Google'},
    {'name': 'Jason Zebchuk', 'affiliations': 'Cavium'},
    {'name': 'Jishen Zhao', 'affiliations': 'University of California, San Diego'},
    {'name': 'Yuhao Zhu', 'affiliations': 'University of Rochester'},
]

from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

def disambiguate_authors(chairs_list, previous_list):
    disambiguated_list = []
    used_names = set()

    for chair in chairs_list:
        best_match = None
        max_similarity = 0

        for prev_chair in previous_list:
            similarity = similar(chair['name'], prev_chair['name'])
            if similarity > max_similarity and chair['affiliation'] == prev_chair['affiliation']:
                max_similarity = similarity
                best_match = prev_chair

        if best_match is not None and best_match['name'] not in used_names:
            disambiguated_list.append(best_match)
            used_names.add(best_match['name'])
        else:
            disambiguated_list.append(chair)

    return disambiguated_list

# Combine all the committee chairs lists
all_chairs = committee_chairs_2023 + committee_chairs_2022 + committee_chairs_2021 + committee_chairs_2020

# Disambiguate and remove duplicates
unique_chairs = disambiguate_authors(all_chairs, all_chairs)

print(unique_chairs)

import csv

# Specify the filename for the CSV file
csv_filename = 'HPCA_PC.csv'

# Define the field names for the CSV header
field_names = ['name', 'affiliation']

# Write the data to the CSV file
with open(csv_filename, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=field_names)

    # Write the header
    writer.writeheader()

    # Write the committee_chairs data
    writer.writerows(unique_chairs)

print(f"The data has been written to {csv_filename}")
